from sqlalchemy.orm import Session

from app.models.gaming_vc import GamingVC

GAMING_VCS = [
    # ═══════════════════════════════════════════
    # TOP-TIER GAMING VCs
    # ═══════════════════════════════════════════
    {
        "name": "Andreessen Horowitz (a16z) Games", "url": "https://a16z.com/games/",
        "description": "a16z GAMES is the dedicated gaming investment arm of Andreessen Horowitz, one of Silicon Valley's most prominent VC firms. They invest across gaming infrastructure, studios, and platforms.",
        "short_description": "Top-tier VC with dedicated gaming fund",
        "founded_year": 2019, "headquarters": "San Francisco, CA", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a", "series-b", "growth"],
        "investment_focus": ["gaming", "game-infrastructure", "game-studios", "UGC-platforms", "live-service"],
        "gaming_subsectors": ["pc-gaming", "mobile-gaming", "console", "game-tools", "game-engines", "social-gaming"],
        "thesis": "Games are the future of entertainment and social interaction. We invest in bold founders building the next generation of interactive entertainment.",
        "fund_size": "$600M (Games Fund I)", "total_aum": "$35B+ (firm-wide)",
        "typical_check_size": "$5M - $100M",
        "notable_portfolio": [
            {"name": "Roblox", "status": "public"},
            {"name": "Overwolf", "status": "active"},
            {"name": "Manticore Games", "status": "active"},
            {"name": "Singularity 6", "status": "active"},
            {"name": "Theorycraft Games", "status": "active"},
            {"name": "Azra Games", "status": "active"}
        ],
        "portfolio_companies_count": 40, "total_investments": 50, "total_exits": 5,
        "partners": [
            {"name": "Andrew Chen", "title": "General Partner", "focus": "gaming/consumer", "linkedin": "https://www.linkedin.com/in/andrewchen/"},
            {"name": "Jonathan Lai", "title": "Partner", "focus": "gaming", "linkedin": "https://www.linkedin.com/in/jonathanlai1/"},
            {"name": "James Gwertzman", "title": "General Partner", "focus": "gaming infrastructure"},
        ],
        "team_size": 15,
        "contact_email": "games@a16z.com", "pitch_email": "games@a16z.com",
        "social_twitter": "@a16z", "social_linkedin": "https://www.linkedin.com/company/a16z/",
        "twitter_followers": 1000000,
        "blog_url": "https://a16z.com/gaming/", "newsletter_url": "https://a16z.com/newsletter/",
        "podcast_url": "https://a16z.com/podcasts/",
        "events_attended": ["GDC", "E3", "Gamescom", "Game Awards"],
        "tier": "top-tier", "priority": 1,
        "tags": ["top-tier", "mega-fund", "gaming-focused", "infrastructure", "studios"],
    },
    {
        "name": "BITKRAFT Ventures", "url": "https://www.bitkraft.vc",
        "description": "BITKRAFT Ventures is a global investment platform dedicated to gaming, esports, and interactive media. Founded by Jens Hilgers, an esports pioneer. One of the most active gaming-focused VCs globally.",
        "short_description": "Leading gaming-native VC fund",
        "founded_year": 2017, "headquarters": "Berlin / New York / San Francisco", "region": "EU", "country": "Germany",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed", "series-a", "series-b"],
        "investment_focus": ["gaming", "esports", "interactive-media", "game-tech", "streaming"],
        "gaming_subsectors": ["esports", "game-studios", "game-tools", "streaming-tech", "social-gaming", "mobile-gaming"],
        "thesis": "We believe interactive entertainment will be the dominant form of media. We back founders who are building the future of play.",
        "fund_size": "$275M (Fund II)", "total_aum": "$500M+",
        "typical_check_size": "$1M - $15M",
        "notable_portfolio": [
            {"name": "Overwolf", "status": "active"},
            {"name": "Avalon", "status": "active"},
            {"name": "Mainframe Industries", "status": "active"},
            {"name": "Hiro Capital", "status": "active"},
            {"name": "nWay", "status": "active"}
        ],
        "portfolio_companies_count": 80, "total_investments": 100, "total_exits": 12,
        "partners": [
            {"name": "Jens Hilgers", "title": "Founding Partner", "focus": "esports/gaming", "linkedin": "https://www.linkedin.com/in/jenshilgers/"},
            {"name": "Malte Barth", "title": "Founding Partner", "focus": "gaming"},
            {"name": "Scott Rupp", "title": "Managing Partner", "focus": "gaming"},
            {"name": "Moritz Baier-Lentz", "title": "Partner", "focus": "gaming/esports"},
        ],
        "team_size": 25,
        "contact_email": "info@bitkraft.vc", "pitch_email": "deals@bitkraft.vc",
        "social_twitter": "@BITKRAFTvc", "social_linkedin": "https://www.linkedin.com/company/bitkraft/",
        "twitter_followers": 25000,
        "blog_url": "https://www.bitkraft.vc/insights",
        "events_attended": ["GDC", "Gamescom", "TwitchCon", "Slush"],
        "tier": "top-tier", "priority": 1,
        "tags": ["gaming-native", "esports-pioneer", "global", "active-investor"],
    },
    {
        "name": "Griffin Gaming Partners", "url": "https://griffingp.com",
        "description": "Gaming-focused venture fund led by industry veterans. Invests exclusively in gaming and gaming-adjacent companies across all stages.",
        "short_description": "Gaming-exclusive VC led by industry veterans",
        "founded_year": 2019, "headquarters": "San Francisco, CA", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a", "series-b", "growth"],
        "investment_focus": ["gaming", "game-studios", "game-tech", "esports", "gaming-infrastructure"],
        "gaming_subsectors": ["pc-gaming", "mobile-gaming", "console", "esports", "game-tools", "VR/AR"],
        "thesis": "We are gamers investing in gaming. Our team brings decades of experience operating and investing in the games industry.",
        "fund_size": "$750M (combined)", "total_aum": "$750M+",
        "typical_check_size": "$2M - $50M",
        "notable_portfolio": [
            {"name": "Rec Room", "status": "active"},
            {"name": "Frost Giant Studios", "status": "active"},
            {"name": "Lightforge Games", "status": "active"},
            {"name": "Pocket Worlds", "status": "active"}
        ],
        "portfolio_companies_count": 50, "total_investments": 60, "total_exits": 8,
        "partners": [
            {"name": "Nick Tuosto", "title": "Co-Founder & General Partner", "focus": "gaming M&A"},
            {"name": "Phil Sanderson", "title": "Co-Founder & General Partner", "focus": "gaming investment"},
            {"name": "Peter Levin", "title": "General Partner", "focus": "gaming/entertainment"},
        ],
        "team_size": 12,
        "contact_email": "info@griffingp.com", "pitch_email": "deals@griffingp.com",
        "social_twitter": "@GriffinGP", "social_linkedin": "https://www.linkedin.com/company/griffin-gaming-partners/",
        "events_attended": ["GDC", "DICE", "Game Awards"],
        "tier": "top-tier", "priority": 1,
        "tags": ["gaming-only", "industry-veterans", "all-stages", "large-checks"],
    },
    {
        "name": "Makers Fund", "url": "https://www.makersfund.com",
        "description": "Global venture fund focused exclusively on interactive entertainment. Invests in game studios, platforms, and technology across all stages and geographies.",
        "short_description": "Global gaming-focused VC fund",
        "founded_year": 2016, "headquarters": "Singapore / San Francisco", "region": "APAC", "country": "Singapore",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a", "series-b", "growth"],
        "investment_focus": ["gaming", "interactive-entertainment", "game-tech", "game-studios"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "game-tools", "esports", "game-studios"],
        "thesis": "Interactive entertainment is the most important form of media globally. We invest across the entire value chain.",
        "fund_size": "$500M+", "total_aum": "$1B+",
        "typical_check_size": "$2M - $30M",
        "notable_portfolio": [
            {"name": "Hoyoverse (miHoYo)", "status": "active"},
            {"name": "Rec Room", "status": "active"},
            {"name": "Dream Games", "status": "active"},
            {"name": "Playco", "status": "active"}
        ],
        "portfolio_companies_count": 70, "total_investments": 80, "total_exits": 10,
        "partners": [
            {"name": "Jay Chi", "title": "Founder & Managing Partner", "focus": "gaming/Asia"},
            {"name": "Michael Cheung", "title": "Partner", "focus": "gaming"},
        ],
        "team_size": 20,
        "contact_email": "info@makersfund.com", "pitch_email": "pitch@makersfund.com",
        "social_twitter": "@MakersFund", "social_linkedin": "https://www.linkedin.com/company/makers-fund/",
        "events_attended": ["GDC", "Tokyo Game Show", "Gamescom", "ChinaJoy"],
        "tier": "top-tier", "priority": 1,
        "tags": ["global", "asia-focus", "gaming-only", "large-fund"],
    },
    {
        "name": "Konvoy Ventures", "url": "https://www.konvoy.vc",
        "description": "Gaming-focused venture capital firm investing in the tools, platforms, and infrastructure powering the gaming ecosystem.",
        "short_description": "Gaming infrastructure-focused VC",
        "founded_year": 2019, "headquarters": "Denver, CO", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed", "series-a"],
        "investment_focus": ["gaming-infrastructure", "game-tech", "esports-tech", "streaming-tech"],
        "gaming_subsectors": ["game-tools", "game-engines", "esports-infrastructure", "streaming", "analytics"],
        "thesis": "We invest in the picks and shovels of gaming - the tools, infrastructure, and platforms that power the $200B+ gaming industry.",
        "fund_size": "$150M (Fund III)", "total_aum": "$250M+",
        "typical_check_size": "$500K - $5M",
        "notable_portfolio": [
            {"name": "Overwolf", "status": "active"},
            {"name": "Hathora", "status": "active"},
            {"name": "Anzu", "status": "active"},
            {"name": "Carry1st", "status": "active"}
        ],
        "portfolio_companies_count": 60, "total_investments": 70, "total_exits": 5,
        "partners": [
            {"name": "Josh Chapman", "title": "Managing Partner", "focus": "gaming infrastructure"},
            {"name": "Jackson Vaughan", "title": "Managing Partner", "focus": "gaming-tech"},
        ],
        "team_size": 10,
        "contact_email": "info@konvoy.vc", "pitch_email": "pitch@konvoy.vc",
        "social_twitter": "@KonvoyVentures", "social_linkedin": "https://www.linkedin.com/company/konvoy-ventures/",
        "blog_url": "https://www.konvoy.vc/blog",
        "newsletter_url": "https://www.konvoy.vc/newsletter",
        "events_attended": ["GDC", "E3", "TwitchCon"],
        "tier": "top-tier", "priority": 1,
        "tags": ["infrastructure", "early-stage", "gaming-tools", "active-newsletter"],
    },

    # ═══════════════════════════════════════════
    # MID-TIER GAMING VCs
    # ═══════════════════════════════════════════
    {
        "name": "Hiro Capital", "url": "https://www.hirocapital.com",
        "description": "European gaming VC fund investing in games, esports, and the metaverse. Named after the protagonist of Snow Crash.",
        "short_description": "European gaming & metaverse VC",
        "founded_year": 2019, "headquarters": "London, UK", "region": "UK", "country": "United Kingdom",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a"],
        "investment_focus": ["gaming", "esports", "metaverse", "game-studios"],
        "gaming_subsectors": ["pc-gaming", "esports", "VR/AR", "game-studios", "metaverse"],
        "thesis": "Games and esports are the future of entertainment. We invest in the intersection of games, esports, and the metaverse.",
        "fund_size": "$100M", "typical_check_size": "$1M - $10M",
        "notable_portfolio": [
            {"name": "Improbable", "status": "active"},
            {"name": "Hadean", "status": "active"},
            {"name": "GRID Esports", "status": "active"}
        ],
        "portfolio_companies_count": 25,
        "partners": [
            {"name": "Luke Alvarez", "title": "Managing Partner", "focus": "gaming"},
            {"name": "Ian Livingstone", "title": "Co-Founder", "focus": "gaming legend (Games Workshop)"},
            {"name": "Cherry Freeman", "title": "Partner", "focus": "gaming/esports"},
        ],
        "team_size": 8,
        "contact_email": "info@hirocapital.com",
        "social_twitter": "@HiroCapital", "social_linkedin": "https://www.linkedin.com/company/hiro-capital/",
        "events_attended": ["GDC", "Gamescom", "Develop Brighton"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["european", "metaverse", "esports", "early-stage"],
    },
    {
        "name": "Play Ventures", "url": "https://www.playventures.vc",
        "description": "Helsinki-based gaming VC focused on mobile and casual games. Founded by gaming industry veterans from Supercell and Rovio.",
        "short_description": "Nordic mobile gaming VC",
        "founded_year": 2018, "headquarters": "Helsinki, Finland", "region": "EU", "country": "Finland",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed", "series-a"],
        "investment_focus": ["mobile-gaming", "casual-games", "game-studios", "hypercasual"],
        "gaming_subsectors": ["mobile-gaming", "casual-gaming", "game-studios", "game-tech"],
        "thesis": "We invest in the best mobile game studios globally. Our team has built some of the biggest mobile games in history.",
        "fund_size": "$135M (Fund II)", "typical_check_size": "$500K - $5M",
        "notable_portfolio": [
            {"name": "Homa Games", "status": "active"},
            {"name": "Playstack", "status": "active"},
            {"name": "Metacore Games", "status": "active"}
        ],
        "portfolio_companies_count": 40,
        "partners": [
            {"name": "Henric Suuronen", "title": "Co-Founder & General Partner", "focus": "mobile gaming"},
            {"name": "Harri Manninen", "title": "Co-Founder & General Partner", "focus": "mobile gaming"},
        ],
        "team_size": 10,
        "contact_email": "hello@playventures.vc", "pitch_email": "pitch@playventures.vc",
        "social_twitter": "@playaborern", "social_linkedin": "https://www.linkedin.com/company/play-ventures/",
        "events_attended": ["GDC", "PGC (Pocket Gamer Connects)", "Slush"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["mobile-gaming", "nordic", "supercell-alumni", "early-stage"],
    },
    {
        "name": "London Venture Partners (LVP)", "url": "https://www.londonvp.com",
        "description": "One of the first gaming-only VC funds. Invests in game studios and gaming technology across Europe and globally.",
        "short_description": "Pioneer gaming-only European VC",
        "founded_year": 2010, "headquarters": "London, UK", "region": "UK", "country": "United Kingdom",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a", "series-b"],
        "investment_focus": ["game-studios", "game-tech", "gaming-infrastructure"],
        "gaming_subsectors": ["pc-gaming", "console", "mobile-gaming", "game-studios", "game-tools"],
        "thesis": "We have been investing in games since 2010 - one of the first funds dedicated to the sector. We back exceptional game makers.",
        "fund_size": "$150M (Fund III)", "typical_check_size": "$1M - $10M",
        "notable_portfolio": [
            {"name": "Unity Technologies", "status": "public"},
            {"name": "Supercell", "status": "exit"},
            {"name": "PlayFab (Microsoft)", "status": "exit"},
            {"name": "NaturalMotion (Zynga)", "status": "exit"}
        ],
        "portfolio_companies_count": 50, "total_exits": 15,
        "partners": [
            {"name": "David Lau-Kee", "title": "Founding Partner", "focus": "games"},
            {"name": "David Gardner", "title": "Founding Partner", "focus": "games"},
        ],
        "team_size": 8,
        "contact_email": "info@londonvp.com", "pitch_email": "pitch@londonvp.com",
        "social_twitter": "@LondonVP", "social_linkedin": "https://www.linkedin.com/company/london-venture-partners/",
        "events_attended": ["GDC", "Develop Brighton", "Gamescom"],
        "tier": "top-tier", "priority": 1,
        "tags": ["pioneer", "european", "gaming-only", "strong-exits"],
    },
    {
        "name": "Galaxy Interactive", "url": "https://galaxyinteractive.io",
        "description": "Growth-stage fund investing in interactive entertainment and the convergence of content and technology. Part of Galaxy Digital.",
        "short_description": "Growth-stage interactive entertainment fund",
        "founded_year": 2018, "headquarters": "New York, NY", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["series-a", "series-b", "growth"],
        "investment_focus": ["interactive-entertainment", "gaming", "web3-gaming", "metaverse", "game-tech"],
        "gaming_subsectors": ["game-studios", "VR/AR", "web3-gaming", "streaming-tech", "social-gaming"],
        "thesis": "Interactive entertainment is converging across gaming, social, and media. We invest at the frontier of this convergence.",
        "fund_size": "$325M", "typical_check_size": "$5M - $30M",
        "notable_portfolio": [
            {"name": "Immutable", "status": "active"},
            {"name": "Candy Digital", "status": "active"},
            {"name": "Upland", "status": "active"}
        ],
        "portfolio_companies_count": 30,
        "partners": [
            {"name": "Sam Englebardt", "title": "Co-Founder", "focus": "interactive entertainment"},
            {"name": "Richard Kim", "title": "General Partner", "focus": "gaming/web3"},
        ],
        "team_size": 15,
        "contact_email": "info@galaxyinteractive.io",
        "social_twitter": "@GalaxyInteract", "social_linkedin": "https://www.linkedin.com/company/galaxy-interactive/",
        "events_attended": ["GDC", "DICE Summit", "Web Summit"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["growth-stage", "web3", "metaverse", "convergence"],
    },
    {
        "name": "Transcend Fund", "url": "https://www.transcendfund.com",
        "description": "Early-stage gaming VC focused on diverse and underrepresented founders in the gaming industry.",
        "short_description": "Gaming VC for diverse founders",
        "founded_year": 2020, "headquarters": "Los Angeles, CA", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed"],
        "investment_focus": ["gaming", "game-studios", "diverse-founders"],
        "gaming_subsectors": ["game-studios", "game-tools", "mobile-gaming", "pc-gaming"],
        "thesis": "We invest in underrepresented founders building the next great games and gaming companies.",
        "fund_size": "$10M", "typical_check_size": "$100K - $500K",
        "portfolio_companies_count": 20,
        "partners": [
            {"name": "Shawn Foust", "title": "Founder & Managing Partner", "focus": "gaming/diversity"},
        ],
        "team_size": 3,
        "contact_email": "info@transcendfund.com", "pitch_email": "pitch@transcendfund.com",
        "social_twitter": "@TranscendFund", "social_linkedin": "https://www.linkedin.com/company/transcend-fund/",
        "events_attended": ["GDC", "Game Devs of Color Expo"],
        "tier": "emerging", "priority": 3,
        "tags": ["diversity", "early-stage", "indie-friendly", "underrepresented-founders"],
    },
    {
        "name": "Vgames", "url": "https://www.vgames.vc",
        "description": "Israeli gaming VC fund that invests in game studios, tools, and tech. Focused on early-stage gaming companies.",
        "short_description": "Israeli gaming VC fund",
        "founded_year": 2019, "headquarters": "Tel Aviv, Israel", "region": "IL", "country": "Israel",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed", "series-a"],
        "investment_focus": ["gaming", "game-studios", "game-tech"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "game-tools", "game-studios"],
        "thesis": "Israel has a thriving gaming ecosystem. We invest in the best Israeli and global gaming startups.",
        "fund_size": "$60M", "typical_check_size": "$500K - $3M",
        "notable_portfolio": [
            {"name": "Overwolf", "status": "active"},
            {"name": "Tripledot Studios", "status": "active"},
            {"name": "Lightneer", "status": "active"}
        ],
        "portfolio_companies_count": 30,
        "partners": [
            {"name": "Eitan Reisel", "title": "Founder & Managing Partner", "focus": "gaming"},
        ],
        "team_size": 5,
        "contact_email": "info@vgames.vc", "pitch_email": "eitan@vgames.vc",
        "social_twitter": "@vgamesvc", "social_linkedin": "https://www.linkedin.com/company/vgames/",
        "events_attended": ["GDC", "GameIS", "Slush"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["israel", "early-stage", "mobile-gaming", "gaming-focused"],
    },
    {
        "name": "1Up Ventures", "url": "https://www.1upventures.com",
        "description": "Gaming-focused venture fund founded by former Xbox and Oculus executives. Invests in indie and AA game studios.",
        "short_description": "Gaming VC by former Xbox/Oculus execs",
        "founded_year": 2020, "headquarters": "Seattle, WA", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed", "series-a"],
        "investment_focus": ["game-studios", "indie-games", "AA-games"],
        "gaming_subsectors": ["pc-gaming", "console", "VR/AR", "indie-games"],
        "thesis": "We back the next generation of game creators. Founded by people who have built, shipped, and marketed games.",
        "fund_size": "$50M", "typical_check_size": "$500K - $3M",
        "portfolio_companies_count": 20,
        "partners": [
            {"name": "Ed Fries", "title": "Co-Founder", "focus": "game studios (former Xbox VP)"},
        ],
        "team_size": 4,
        "contact_email": "hello@1upventures.com", "pitch_email": "pitch@1upventures.com",
        "social_twitter": "@1UpVentures",
        "events_attended": ["GDC", "PAX", "IndieCade"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["indie-focused", "xbox-alumni", "game-studios", "AA-games"],
    },
    {
        "name": "Lakestar", "url": "https://www.lakestar.com",
        "description": "European technology VC with significant gaming portfolio. Early investor in Spotify and other tech unicorns.",
        "short_description": "European tech VC with gaming portfolio",
        "founded_year": 2012, "headquarters": "Zurich, Switzerland", "region": "EU", "country": "Switzerland",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a", "series-b"],
        "investment_focus": ["gaming", "technology", "deep-tech", "fintech"],
        "gaming_subsectors": ["game-studios", "game-tech", "esports"],
        "fund_size": "$1B+ (firm-wide)", "typical_check_size": "$2M - $20M",
        "notable_portfolio": [
            {"name": "Spotify", "status": "public"},
            {"name": "Glovo", "status": "exit"},
        ],
        "partners": [
            {"name": "Klaus Hommels", "title": "Founder & Managing Partner"},
        ],
        "team_size": 30,
        "contact_email": "info@lakestar.com",
        "social_twitter": "@LakestarVC", "social_linkedin": "https://www.linkedin.com/company/lakestar/",
        "tier": "mid-tier", "priority": 3,
        "tags": ["european", "generalist-with-gaming", "large-fund"],
    },
    {
        "name": "Raine Group", "url": "https://www.rainegroup.com",
        "description": "Technology-focused merchant bank with deep gaming expertise. Advises on major gaming M&A deals including Activision-Microsoft.",
        "short_description": "Gaming-savvy merchant bank & investor",
        "founded_year": 2009, "headquarters": "New York, NY", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["growth", "late-stage"],
        "investment_focus": ["gaming", "media", "entertainment", "technology"],
        "gaming_subsectors": ["game-studios", "esports", "streaming"],
        "thesis": "We invest in and advise the most important companies at the intersection of technology, media, and entertainment.",
        "fund_size": "$1.5B (Raine Partners Fund)", "typical_check_size": "$10M - $100M+",
        "notable_portfolio": [
            {"name": "Epic Games", "status": "active"},
            {"name": "FaZe Clan", "status": "active"},
            {"name": "Rec Room", "status": "active"}
        ],
        "partners": [
            {"name": "Jeff Sine", "title": "Co-Founder & Partner"},
            {"name": "Joe Ravitch", "title": "Co-Founder & Partner"},
        ],
        "team_size": 50,
        "contact_email": "info@rainegroup.com",
        "social_linkedin": "https://www.linkedin.com/company/the-raine-group/",
        "events_attended": ["GDC", "E3", "DICE Summit", "Game Awards"],
        "tier": "top-tier", "priority": 1,
        "tags": ["merchant-bank", "growth-stage", "M&A", "mega-deals"],
    },

    # ═══════════════════════════════════════════
    # EMERGING / BOUTIQUE GAMING VCs
    # ═══════════════════════════════════════════
    {
        "name": "Patron (formerly Valor)", "url": "https://www.patron.vc",
        "description": "Swedish gaming VC that invests in Nordic gaming companies. Deep roots in the Nordic gaming ecosystem.",
        "short_description": "Nordic gaming-focused VC",
        "founded_year": 2018, "headquarters": "Stockholm, Sweden", "region": "EU", "country": "Sweden",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a"],
        "investment_focus": ["gaming", "game-studios", "game-tech"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "game-studios"],
        "fund_size": "$80M", "typical_check_size": "$500K - $5M",
        "portfolio_companies_count": 20,
        "team_size": 6,
        "contact_email": "info@patron.vc", "pitch_email": "pitch@patron.vc",
        "social_twitter": "@patronvc",
        "events_attended": ["GDC", "Nordic Game Conference", "Slush"],
        "tier": "emerging", "priority": 3,
        "tags": ["nordic", "gaming-focused", "early-stage"],
    },
    {
        "name": "Sisu Game Ventures", "url": "https://sisugameventures.com",
        "description": "Finnish gaming VC investing in Nordic and global game studios. Founded by gaming industry operators.",
        "short_description": "Finnish gaming VC for game studios",
        "founded_year": 2020, "headquarters": "Helsinki, Finland", "region": "EU", "country": "Finland",
        "firm_type": "venture_capital",
        "investment_stage": ["pre-seed", "seed"],
        "investment_focus": ["game-studios", "mobile-gaming"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "game-studios"],
        "fund_size": "$30M", "typical_check_size": "$200K - $2M",
        "portfolio_companies_count": 15,
        "team_size": 4,
        "contact_email": "info@sisugameventures.com", "pitch_email": "pitch@sisugameventures.com",
        "social_twitter": "@SisuGameVC",
        "events_attended": ["GDC", "PGC", "Nordic Game"],
        "tier": "emerging", "priority": 3,
        "tags": ["finnish", "mobile-gaming", "early-stage", "operator-led"],
    },
    {
        "name": "NetEase Capital", "url": "https://www.neteasecapital.com",
        "description": "Strategic investment arm of NetEase, one of China's largest gaming companies. Invests in global gaming companies.",
        "short_description": "NetEase's strategic gaming investment arm",
        "founded_year": 2015, "headquarters": "Hangzhou, China / San Francisco", "region": "CN", "country": "China",
        "firm_type": "corporate_vc",
        "investment_stage": ["series-a", "series-b", "growth"],
        "investment_focus": ["gaming", "game-studios", "game-tech", "metaverse"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "console", "MMO", "game-studios"],
        "thesis": "As one of the world's largest gaming companies, we invest in studios and tech that complement and extend our gaming ecosystem.",
        "fund_size": "N/A (balance sheet)", "typical_check_size": "$5M - $100M",
        "notable_portfolio": [
            {"name": "Quantic Dream", "status": "active"},
            {"name": "Grasshopper Manufacture", "status": "active"},
            {"name": "Bungie (minority)", "status": "active"}
        ],
        "team_size": 20,
        "contact_email": "invest@netease.com",
        "social_twitter": "@NetEaseGames",
        "events_attended": ["GDC", "ChinaJoy", "Tokyo Game Show"],
        "tier": "top-tier", "priority": 1,
        "tags": ["corporate-vc", "china", "global", "strategic-investor"],
    },
    {
        "name": "Tencent Investment", "url": "https://www.tencent.com",
        "description": "The most prolific gaming investor globally. Tencent owns or has stakes in Riot Games, Epic Games, Supercell, and hundreds more.",
        "short_description": "World's largest gaming investor",
        "founded_year": 2008, "headquarters": "Shenzhen, China", "region": "CN", "country": "China",
        "firm_type": "corporate_vc",
        "investment_stage": ["seed", "series-a", "series-b", "growth", "late-stage"],
        "investment_focus": ["gaming", "game-studios", "esports", "social", "metaverse"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "console", "esports", "game-studios", "game-tools", "streaming"],
        "thesis": "We invest in the best gaming companies globally and provide them with the resources and distribution to reach billions of players.",
        "fund_size": "N/A (balance sheet)", "total_aum": "$500B+ market cap",
        "typical_check_size": "$1M - $10B",
        "notable_portfolio": [
            {"name": "Riot Games", "status": "subsidiary"},
            {"name": "Epic Games", "status": "40% stake"},
            {"name": "Supercell", "status": "84% stake"},
            {"name": "Activision Blizzard (former)", "status": "exit"},
            {"name": "Ubisoft", "status": "minority"},
            {"name": "Discord", "status": "minority"},
            {"name": "Krafton (PUBG)", "status": "minority"}
        ],
        "portfolio_companies_count": 800, "total_investments": 1000, "total_exits": 50,
        "team_size": 200,
        "contact_email": "investorrelations@tencent.com",
        "social_twitter": "@Tencent",
        "events_attended": ["GDC", "ChinaJoy", "Gamescom", "E3", "Tokyo Game Show"],
        "tier": "top-tier", "priority": 1,
        "tags": ["mega-investor", "corporate-vc", "china", "global", "strategic"],
    },
    {
        "name": "Krafton Investment", "url": "https://www.krafton.com",
        "description": "Investment arm of Krafton (PUBG creator). Actively investing in global game studios, especially in Asia and India.",
        "short_description": "PUBG creator's investment arm",
        "founded_year": 2018, "headquarters": "Seoul, South Korea", "region": "KR", "country": "South Korea",
        "firm_type": "corporate_vc",
        "investment_stage": ["seed", "series-a", "series-b", "growth"],
        "investment_focus": ["gaming", "game-studios", "game-tech", "entertainment"],
        "gaming_subsectors": ["mobile-gaming", "pc-gaming", "game-studios", "esports"],
        "thesis": "We invest globally in studios and technology that advance interactive entertainment. Special focus on emerging markets.",
        "fund_size": "N/A (balance sheet)", "typical_check_size": "$5M - $50M",
        "notable_portfolio": [
            {"name": "Nodwin Gaming", "status": "active"},
            {"name": "Lila Games", "status": "active"},
            {"name": "Dreamotion", "status": "active"}
        ],
        "portfolio_companies_count": 30,
        "team_size": 15,
        "contact_email": "investment@krafton.com",
        "social_twitter": "@kraftaborern",
        "events_attended": ["GDC", "G-Star", "Tokyo Game Show"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["corporate-vc", "korea", "pubg", "india-focus", "emerging-markets"],
    },
    {
        "name": "MTG (Modern Times Group)", "url": "https://www.mtg.com",
        "description": "Swedish gaming and esports conglomerate investing in and acquiring gaming companies globally.",
        "short_description": "Swedish gaming & esports investor",
        "founded_year": 2018, "headquarters": "Stockholm, Sweden", "region": "EU", "country": "Sweden",
        "firm_type": "corporate_vc",
        "investment_stage": ["series-a", "growth", "acquisition"],
        "investment_focus": ["gaming", "esports"],
        "gaming_subsectors": ["esports", "game-studios", "mobile-gaming"],
        "notable_portfolio": [
            {"name": "ESL Gaming", "status": "subsidiary"},
            {"name": "DreamHack", "status": "subsidiary"},
            {"name": "InnoGames", "status": "subsidiary"},
            {"name": "Hutch", "status": "subsidiary"}
        ],
        "team_size": 20,
        "contact_email": "info@mtg.com",
        "social_twitter": "@MTaborern", "social_linkedin": "https://www.linkedin.com/company/modern-times-group/",
        "events_attended": ["GDC", "Gamescom", "DreamHack"],
        "tier": "mid-tier", "priority": 2,
        "tags": ["corporate", "esports", "acquisitions", "nordic"],
    },
    {
        "name": "Hypergryph Ventures", "url": "https://www.hypergryph.com",
        "description": "Investment arm of Hypergryph, the studio behind Arknights. Investing in game studios across Asia.",
        "short_description": "Arknights studio's investment arm",
        "founded_year": 2020, "headquarters": "Shanghai, China", "region": "CN", "country": "China",
        "firm_type": "corporate_vc",
        "investment_stage": ["seed", "series-a"],
        "investment_focus": ["game-studios", "anime-games", "mobile-gaming"],
        "gaming_subsectors": ["mobile-gaming", "anime-games", "gacha", "game-studios"],
        "typical_check_size": "$1M - $10M",
        "portfolio_companies_count": 10,
        "team_size": 5,
        "contact_email": "invest@hypergryph.com",
        "events_attended": ["ChinaJoy", "Tokyo Game Show", "Anime Expo"],
        "tier": "emerging", "priority": 3,
        "tags": ["anime-games", "china", "mobile", "gacha"],
    },
    {
        "name": "Venture Reality Fund", "url": "https://www.thevrfund.com",
        "description": "Focused exclusively on VR, AR, and spatial computing investments including gaming applications.",
        "short_description": "VR/AR gaming-focused VC",
        "founded_year": 2016, "headquarters": "San Francisco, CA", "region": "US", "country": "United States",
        "firm_type": "venture_capital",
        "investment_stage": ["seed", "series-a"],
        "investment_focus": ["VR-gaming", "AR-gaming", "spatial-computing", "metaverse"],
        "gaming_subsectors": ["VR/AR", "spatial-computing", "game-studios"],
        "thesis": "VR and AR will transform gaming and entertainment. We invest in the builders of this future.",
        "fund_size": "$50M", "typical_check_size": "$500K - $3M",
        "portfolio_companies_count": 25,
        "partners": [
            {"name": "Tipatat Chennavasin", "title": "General Partner", "focus": "VR/AR"},
        ],
        "team_size": 4,
        "contact_email": "info@thevrfund.com", "pitch_email": "pitch@thevrfund.com",
        "social_twitter": "@TheVRFund",
        "events_attended": ["GDC", "AWE", "CES", "Oculus Connect"],
        "tier": "boutique", "priority": 3,
        "tags": ["VR", "AR", "spatial-computing", "niche-focused"],
    },
]


def seed_gaming_vcs(db: Session) -> int:
    """Seed the database with known gaming VCs. Returns the number added."""
    added = 0
    for vc_data in GAMING_VCS:
        existing = db.query(GamingVC).filter(GamingVC.url == vc_data["url"]).first()
        if not existing:
            vc = GamingVC(**vc_data)
            db.add(vc)
            added += 1
    db.commit()
    return added
