from sqlalchemy.orm import Session

from app.models.investor import GamingInvestor

GAMING_INVESTORS = [
    # ═══════════════════════════════════════════
    # DEDICATED GAMING VCs
    # ═══════════════════════════════════════════
    {
        "name": "Andreessen Horowitz Games",
        "short_name": "a16z Games",
        "investor_type": "vc",
        "description": "Dedicated games practice at a16z, investing across PC/console, mobile, web3, and gaming infrastructure. Led by Jon Goldman.",
        "website": "https://a16z.com/games/",
        "founded_year": 2022,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "aum_millions": 600.0,
        "fund_size_millions": 600.0,
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "web3_gaming", "mobile_gaming", "esports"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Roblox", "url": "https://roblox.com"},
            {"name": "Discord", "url": "https://discord.com"},
            {"name": "Immutable", "url": "https://immutable.com"},
            {"name": "Mythical Games", "url": "https://mythicalgames.com"},
        ],
        "twitter_url": "https://twitter.com/a16z",
        "crunchbase_url": "https://www.crunchbase.com/organization/andreessen-horowitz",
        "is_gaming_focused": True,
    },
    {
        "name": "Bitkraft Ventures",
        "short_name": "Bitkraft",
        "investor_type": "vc",
        "description": "Global gaming and interactive entertainment VC. One of the most active dedicated gaming funds globally.",
        "website": "https://www.bitkraft.vc",
        "founded_year": 2017,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "aum_millions": 300.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "esports", "gaming_infrastructure", "mobile_gaming", "web3_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Maincraft", "url": ""},
            {"name": "Nexon", "url": "https://nexon.com"},
            {"name": "Playtika", "url": "https://playtika.com"},
        ],
        "twitter_url": "https://twitter.com/BITKRAFT",
        "crunchbase_url": "https://www.crunchbase.com/organization/bitkraft-ventures",
        "is_gaming_focused": True,
    },
    {
        "name": "Griffin Gaming Partners",
        "short_name": "Griffin Gaming",
        "investor_type": "vc",
        "description": "Dedicated gaming VC investing in gaming companies across all verticals including studios, tech, and services.",
        "website": "https://www.griffingaming.com",
        "founded_year": 2019,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 235.0,
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports", "mobile_gaming"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "Scopely", "url": "https://scopely.com"},
            {"name": "Overwolf", "url": "https://overwolf.com"},
            {"name": "Nexus Mods", "url": "https://nexusmods.com"},
        ],
        "twitter_url": "https://twitter.com/griffingamingvc",
        "crunchbase_url": "https://www.crunchbase.com/organization/griffin-gaming-partners",
        "is_gaming_focused": True,
    },
    {
        "name": "Makers Fund",
        "short_name": "Makers",
        "investor_type": "vc",
        "description": "First dedicated global gaming VC. Backed by founders, operators, and investors in gaming.",
        "website": "https://www.makersfund.com",
        "founded_year": 2017,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 200.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "mobile_gaming", "social_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Amber", "url": "https://amberstudio.com"},
            {"name": "Gamesight", "url": "https://gamesight.io"},
        ],
        "twitter_url": "https://twitter.com/MakersFund",
        "crunchbase_url": "https://www.crunchbase.com/organization/makers-fund",
        "is_gaming_focused": True,
    },
    {
        "name": "Konvoy Ventures",
        "short_name": "Konvoy",
        "investor_type": "vc",
        "description": "Gaming-focused VC investing in infrastructure and technology that powers the gaming industry.",
        "website": "https://www.konvoy.vc",
        "founded_year": 2018,
        "headquarters_city": "Denver",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 110.0,
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["gaming_infrastructure", "game_tools", "esports", "streaming"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Vindex", "url": "https://vindex.gg"},
            {"name": "SteelSeries", "url": "https://steelseries.com"},
        ],
        "twitter_url": "https://twitter.com/konvoyvc",
        "crunchbase_url": "https://www.crunchbase.com/organization/konvoy-ventures",
        "is_gaming_focused": True,
    },
    {
        "name": "Play Ventures",
        "short_name": "Play",
        "investor_type": "vc",
        "description": "Early-stage gaming VC investing in mobile, PC, and emerging gaming categories globally.",
        "website": "https://www.play.vc",
        "founded_year": 2019,
        "headquarters_city": "Helsinki",
        "headquarters_country": "Finland",
        "headquarters_region": "EU",
        "fund_size_millions": 175.0,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["mobile_gaming", "game_studios", "gaming_infrastructure"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "Metacore", "url": "https://metacore.com"},
            {"name": "Lightheart Entertainment", "url": ""},
        ],
        "twitter_url": "https://twitter.com/playventuresvc",
        "crunchbase_url": "https://www.crunchbase.com/organization/play-ventures",
        "is_gaming_focused": True,
    },
    {
        "name": "Transcend Fund",
        "short_name": "Transcend",
        "investor_type": "vc",
        "description": "Early-stage gaming and interactive entertainment VC with deep industry connections.",
        "website": "https://www.transcendfund.com",
        "founded_year": 2019,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports"],
        "active_regions": ["US"],
        "crunchbase_url": "https://www.crunchbase.com/organization/transcend-fund",
        "is_gaming_focused": True,
    },
    {
        "name": "1Up Ventures",
        "short_name": "1Up",
        "investor_type": "vc",
        "description": "Gaming-first VC fund backing the next generation of gaming companies and studios.",
        "website": "https://www.1upventures.com",
        "founded_year": 2020,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios", "web3_gaming", "gaming_infrastructure"],
        "active_regions": ["US"],
        "is_gaming_focused": True,
    },
    {
        "name": "Galaxy Interactive",
        "short_name": "Galaxy Interactive",
        "investor_type": "vc",
        "description": "Gaming and interactive entertainment investment firm, part of Galaxy Digital. Strong focus on blockchain gaming and virtual worlds.",
        "website": "https://www.galaxyinteractive.io",
        "founded_year": 2018,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 325.0,
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["web3_gaming", "vr_ar", "game_studios", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Forte", "url": "https://forte.io"},
            {"name": "Lucid Sight", "url": ""},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/galaxy-interactive",
        "is_gaming_focused": True,
    },
    {
        "name": "Overwolf Fund",
        "short_name": "Overwolf Fund",
        "investor_type": "corporate",
        "description": "Strategic fund by Overwolf backing creators and developers building gaming mods, apps, and tools for the PC gaming ecosystem.",
        "website": "https://fund.overwolf.com",
        "founded_year": 2021,
        "headquarters_city": "Tel Aviv",
        "headquarters_country": "Israel",
        "headquarters_region": "EU",
        "fund_size_millions": 50.0,
        "typical_check_min_k": 100,
        "typical_check_max_k": 5000,
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_tools", "gaming_infrastructure", "game_studios"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "CurseForge", "url": "https://curseforge.com"},
            {"name": "Nexus Mods", "url": "https://nexusmods.com"},
        ],
        "twitter_url": "https://twitter.com/overwolf",
        "is_gaming_focused": True,
    },

    # ═══════════════════════════════════════════
    # TIER-1 VCs WITH MAJOR GAMING PORTFOLIOS
    # ═══════════════════════════════════════════
    {
        "name": "Lightspeed Venture Partners",
        "short_name": "Lightspeed",
        "investor_type": "vc",
        "description": "Top-tier VC with significant gaming investments across mobile, PC, and esports.",
        "website": "https://lsvp.com",
        "founded_year": 2000,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "game_studios", "esports", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Snap", "url": "https://snap.com"},
            {"name": "Epic Games", "url": "https://epicgames.com"},
        ],
        "twitter_url": "https://twitter.com/lightspeedvp",
        "crunchbase_url": "https://www.crunchbase.com/organization/lightspeed-venture-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "Sequoia Capital",
        "short_name": "Sequoia",
        "investor_type": "vc",
        "description": "Legendary Silicon Valley VC with major gaming portfolio companies including Roblox, Epic, and more.",
        "website": "https://sequoiacap.com",
        "founded_year": 1972,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth", "late_stage"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "mobile_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Roblox", "url": "https://roblox.com"},
            {"name": "Unity Technologies", "url": "https://unity.com"},
        ],
        "twitter_url": "https://twitter.com/sequoia",
        "crunchbase_url": "https://www.crunchbase.com/organization/sequoia-capital",
        "is_gaming_focused": False,
    },
    {
        "name": "Accel Partners",
        "short_name": "Accel",
        "investor_type": "vc",
        "description": "Global VC with notable gaming investments including Supercell, Zynga, and Scopely.",
        "website": "https://accel.com",
        "founded_year": 1983,
        "headquarters_city": "Palo Alto",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "game_studios", "social_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "Scopely", "url": "https://scopely.com"},
        ],
        "twitter_url": "https://twitter.com/accel",
        "crunchbase_url": "https://www.crunchbase.com/organization/accel-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "Bessemer Venture Partners",
        "short_name": "BVP",
        "investor_type": "vc",
        "description": "Long-standing VC with investments across game studios, esports platforms, and gaming infrastructure.",
        "website": "https://bvp.com",
        "founded_year": 1911,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "Twitch", "url": "https://twitch.tv"},
        ],
        "twitter_url": "https://twitter.com/BessemerVP",
        "crunchbase_url": "https://www.crunchbase.com/organization/bessemer-venture-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "Index Ventures",
        "short_name": "Index",
        "investor_type": "vc",
        "description": "European and global VC with strong gaming and gaming-adjacent portfolio.",
        "website": "https://indexventures.com",
        "founded_year": 1996,
        "headquarters_city": "London",
        "headquarters_country": "United Kingdom",
        "headquarters_region": "EU",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["EU", "US"],
        "notable_portfolio": [
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "King", "url": "https://king.com"},
        ],
        "twitter_url": "https://twitter.com/indexventures",
        "crunchbase_url": "https://www.crunchbase.com/organization/index-ventures",
        "is_gaming_focused": False,
    },
    {
        "name": "Benchmark Capital",
        "short_name": "Benchmark",
        "investor_type": "vc",
        "description": "Elite early-stage VC with gaming investments including Discord and others.",
        "website": "https://benchmark.com",
        "founded_year": 1995,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["gaming_infrastructure", "social_gaming", "game_studios"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Discord", "url": "https://discord.com"},
        ],
        "twitter_url": "https://twitter.com/benchmarkcap",
        "crunchbase_url": "https://www.crunchbase.com/organization/benchmark",
        "is_gaming_focused": False,
    },
    {
        "name": "Insight Partners",
        "short_name": "Insight",
        "investor_type": "vc",
        "description": "Growth-stage VC with major gaming and esports portfolio including ESL and FACEIT.",
        "website": "https://insightpartners.com",
        "founded_year": 1995,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "aum_millions": 90000.0,
        "investment_stages": ["series_b", "growth", "late_stage"],
        "focus_areas": ["esports", "gaming_infrastructure", "game_studios"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "ESL Gaming", "url": "https://eslgaming.com"},
            {"name": "FACEIT", "url": "https://faceit.com"},
        ],
        "twitter_url": "https://twitter.com/insightpartners",
        "crunchbase_url": "https://www.crunchbase.com/organization/insight-venture-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "CRV (Charles River Ventures)",
        "short_name": "CRV",
        "investor_type": "vc",
        "description": "Early-stage VC with gaming portfolio including game tool companies and emerging platforms.",
        "website": "https://crv.com",
        "founded_year": 1970,
        "headquarters_city": "Cambridge",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_tools", "gaming_infrastructure", "game_studios"],
        "active_regions": ["US"],
        "twitter_url": "https://twitter.com/CRV",
        "crunchbase_url": "https://www.crunchbase.com/organization/charles-river-ventures",
        "is_gaming_focused": False,
    },
    {
        "name": "Greycroft",
        "short_name": "Greycroft",
        "investor_type": "vc",
        "description": "Multi-stage VC with mobile gaming investments and portfolio including Scopely and Bazooka.",
        "website": "https://greycroft.com",
        "founded_year": 2006,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["mobile_gaming", "game_studios"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Scopely", "url": "https://scopely.com"},
        ],
        "twitter_url": "https://twitter.com/greycroft",
        "crunchbase_url": "https://www.crunchbase.com/organization/greycroft-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "First Round Capital",
        "short_name": "First Round",
        "investor_type": "vc",
        "description": "Seed-stage VC with several gaming and gaming-infrastructure bets.",
        "website": "https://firstround.com",
        "founded_year": 2004,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios", "gaming_infrastructure"],
        "active_regions": ["US"],
        "twitter_url": "https://twitter.com/firstround",
        "crunchbase_url": "https://www.crunchbase.com/organization/first-round-capital",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # CORPORATE / STRATEGIC INVESTORS
    # ═══════════════════════════════════════════
    {
        "name": "Tencent Holdings",
        "short_name": "Tencent",
        "investor_type": "corporate",
        "description": "World's largest gaming company and prolific strategic investor. Holds stakes in Riot Games, Epic, Ubisoft, Activision-Blizzard, and hundreds more.",
        "website": "https://tencent.com",
        "founded_year": 1998,
        "headquarters_city": "Shenzhen",
        "headquarters_country": "China",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth", "late_stage"],
        "focus_areas": ["game_studios", "esports", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Riot Games", "url": "https://riotgames.com"},
            {"name": "Epic Games", "url": "https://epicgames.com"},
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "Ubisoft", "url": "https://ubisoft.com"},
        ],
        "total_known_investments": 100,
        "twitter_url": "https://twitter.com/Tencent",
        "crunchbase_url": "https://www.crunchbase.com/organization/tencent",
        "is_gaming_focused": True,
    },
    {
        "name": "NetEase Capital",
        "short_name": "NetEase",
        "investor_type": "corporate",
        "description": "Chinese internet and gaming giant with global strategic investments in game studios.",
        "website": "https://netease.com",
        "founded_year": 1997,
        "headquarters_city": "Guangzhou",
        "headquarters_country": "China",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Bungie", "url": "https://bungie.net"},
            {"name": "Quantic Dream", "url": "https://quanticdream.com"},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/netease",
        "is_gaming_focused": True,
    },
    {
        "name": "Sony Innovation Fund",
        "short_name": "Sony Ventures",
        "investor_type": "corporate",
        "description": "Sony's corporate venture arm, investing in game developers, VR/AR, and entertainment tech.",
        "website": "https://www.sonyinnovationfund.com",
        "founded_year": 2016,
        "headquarters_city": "Tokyo",
        "headquarters_country": "Japan",
        "headquarters_region": "APAC",
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "vr_ar", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Harmonix", "url": "https://harmonixmusic.com"},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/sony-innovation-fund",
        "is_gaming_focused": False,
    },
    {
        "name": "Microsoft M12",
        "short_name": "M12",
        "investor_type": "corporate",
        "description": "Microsoft's venture fund investing in enterprise and gaming technology companies.",
        "website": "https://m12.vc",
        "founded_year": 2016,
        "headquarters_city": "Redmond",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["gaming_infrastructure", "game_tools", "vr_ar"],
        "active_regions": ["US", "EU"],
        "twitter_url": "https://twitter.com/M12VC",
        "crunchbase_url": "https://www.crunchbase.com/organization/m12",
        "is_gaming_focused": False,
    },
    {
        "name": "Intel Capital",
        "short_name": "Intel Capital",
        "investor_type": "corporate",
        "description": "Intel's investment arm with focus on gaming technology, esports, and semiconductor adjacent bets.",
        "website": "https://intelcapital.com",
        "founded_year": 1991,
        "headquarters_city": "Santa Clara",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["gaming_infrastructure", "esports", "vr_ar"],
        "active_regions": ["US", "EU", "APAC"],
        "twitter_url": "https://twitter.com/intelcapital",
        "crunchbase_url": "https://www.crunchbase.com/organization/intel-capital",
        "is_gaming_focused": False,
    },
    {
        "name": "Krafton Game Union",
        "short_name": "Krafton",
        "investor_type": "corporate",
        "description": "PUBG parent company's strategic investment arm backing game studios globally.",
        "website": "https://krafton.com",
        "founded_year": 2020,
        "headquarters_city": "Seoul",
        "headquarters_country": "South Korea",
        "headquarters_region": "APAC",
        "fund_size_millions": 1000.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "mobile_gaming", "web3_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Bluehole", "url": ""},
            {"name": "RisingWings", "url": ""},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/krafton",
        "is_gaming_focused": True,
    },
    {
        "name": "Kakao Investment",
        "short_name": "Kakao",
        "investor_type": "corporate",
        "description": "Korean internet giant's investment arm, active in mobile gaming and esports.",
        "website": "https://kakaocorp.com",
        "founded_year": 2010,
        "headquarters_city": "Seongnam",
        "headquarters_country": "South Korea",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "esports", "social_gaming"],
        "active_regions": ["APAC"],
        "crunchbase_url": "https://www.crunchbase.com/organization/kakao",
        "is_gaming_focused": False,
    },
    {
        "name": "Qualcomm Ventures",
        "short_name": "Qualcomm Ventures",
        "investor_type": "corporate",
        "description": "Strategic venture arm investing in mobile gaming, XR, and connectivity-driven gaming.",
        "website": "https://qualcommventures.com",
        "founded_year": 2000,
        "headquarters_city": "San Diego",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b"],
        "focus_areas": ["mobile_gaming", "vr_ar", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "twitter_url": "https://twitter.com/qualcommventure",
        "crunchbase_url": "https://www.crunchbase.com/organization/qualcomm-ventures",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # ESPORTS & CREATOR ECONOMY FOCUSED
    # ═══════════════════════════════════════════
    {
        "name": "Excel Esports Ventures",
        "short_name": "Excel Ventures",
        "investor_type": "corporate",
        "description": "Investment arm of Excel Esports focused on the competitive gaming and creator economy ecosystem.",
        "website": "https://excelesports.com",
        "founded_year": 2021,
        "headquarters_city": "London",
        "headquarters_country": "United Kingdom",
        "headquarters_region": "EU",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["esports", "streaming", "gaming_infrastructure"],
        "active_regions": ["EU"],
        "twitter_url": "https://twitter.com/ExcelEsports",
        "is_gaming_focused": True,
    },
    {
        "name": "Greenoaks Capital",
        "short_name": "Greenoaks",
        "investor_type": "vc",
        "description": "Long-term growth investor with large bets on gaming and interactive entertainment.",
        "website": "https://greenoaks.com",
        "founded_year": 2012,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["growth", "late_stage"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Nubank", "url": "https://nubank.com.br"},
            {"name": "Duolingo", "url": "https://duolingo.com"},
        ],
        "is_gaming_focused": False,
    },
    {
        "name": "NetEase Games Investment",
        "short_name": "NetEase Games",
        "investor_type": "corporate",
        "description": "Strategic gaming investments from NetEase focusing on global game studio partnerships.",
        "website": "https://game.163.com",
        "founded_year": 2000,
        "headquarters_city": "Guangzhou",
        "headquarters_country": "China",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Blizzard Entertainment (licensed)", "url": "https://blizzard.com"},
        ],
        "is_gaming_focused": True,
    },
    {
        "name": "Comcast Ventures",
        "short_name": "Comcast Ventures",
        "investor_type": "corporate",
        "description": "Comcast NBCUniversal's VC arm with strategic gaming, streaming, and entertainment investments.",
        "website": "https://comcastventures.com",
        "founded_year": 1999,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["streaming", "esports", "gaming_infrastructure"],
        "active_regions": ["US"],
        "twitter_url": "https://twitter.com/comcastventures",
        "crunchbase_url": "https://www.crunchbase.com/organization/comcast-ventures",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # ACCELERATORS
    # ═══════════════════════════════════════════
    {
        "name": "Y Combinator",
        "short_name": "YC",
        "investor_type": "accelerator",
        "description": "World's most prestigious startup accelerator with notable gaming, game-tool, and esports alumni.",
        "website": "https://ycombinator.com",
        "founded_year": 2005,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "typical_check_min_k": 500,
        "typical_check_max_k": 500,
        "investment_stages": ["pre_seed"],
        "focus_areas": ["game_studios", "game_tools", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Twitch", "url": "https://twitch.tv"},
            {"name": "Amplitude", "url": "https://amplitude.com"},
        ],
        "twitter_url": "https://twitter.com/ycombinator",
        "crunchbase_url": "https://www.crunchbase.com/organization/y-combinator",
        "is_gaming_focused": False,
    },
    {
        "name": "GameFounders",
        "short_name": "GameFounders",
        "investor_type": "accelerator",
        "description": "World's first games-focused accelerator, backing early-stage game studios globally.",
        "website": "https://gamefounders.com",
        "founded_year": 2012,
        "headquarters_city": "Tallinn",
        "headquarters_country": "Estonia",
        "headquarters_region": "EU",
        "typical_check_min_k": 25,
        "typical_check_max_k": 50,
        "investment_stages": ["pre_seed"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["EU", "APAC"],
        "is_gaming_focused": True,
    },
    {
        "name": "GameBC",
        "short_name": "GameBC",
        "investor_type": "accelerator",
        "description": "Game-focused accelerator in British Columbia supporting indie game studios.",
        "website": "https://gamebc.ca",
        "founded_year": 2018,
        "headquarters_city": "Vancouver",
        "headquarters_country": "Canada",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios"],
        "active_regions": ["US"],
        "is_gaming_focused": True,
    },
]


def seed_investors(db: Session) -> int:
    """Seed the database with known gaming investors. Returns the number of new entries added."""
    from app.models.investor import GamingInvestor
    added = 0
    for data in GAMING_INVESTORS:
        existing = db.query(GamingInvestor).filter(GamingInvestor.name == data["name"]).first()
        if not existing:
            investor = GamingInvestor(**data)
            db.add(investor)
            added += 1
    db.commit()
    return added
