from sqlalchemy.orm import Session

from app.models.investor import GamingInvestor

GAMING_INVESTORS = [
    # ═══════════════════════════════════════════
    # DEDICATED GAMING VCs
    # ═══════════════════════════════════════════
    {
        "name": "Andreessen Horowitz Games",
        "short_name": "a16z Games",
        "investor_type": "vc",
        "description": "Dedicated games practice at a16z, investing across PC/console, mobile, web3, and gaming infrastructure. Led by Jon Goldman.",
        "website": "https://a16z.com/games/",
        "founded_year": 2022,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "aum_millions": 600.0,
        "fund_size_millions": 600.0,
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "web3_gaming", "mobile_gaming", "esports"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Roblox", "url": "https://roblox.com"},
            {"name": "Discord", "url": "https://discord.com"},
            {"name": "Immutable", "url": "https://immutable.com"},
            {"name": "Mythical Games", "url": "https://mythicalgames.com"},
        ],
        "twitter_url": "https://twitter.com/a16z",
        "crunchbase_url": "https://www.crunchbase.com/organization/andreessen-horowitz",
        "is_gaming_focused": True,
    },
    {
        "name": "Bitkraft Ventures",
        "short_name": "Bitkraft",
        "investor_type": "vc",
        "description": "Global gaming and interactive entertainment VC. One of the most active dedicated gaming funds globally.",
        "website": "https://www.bitkraft.vc",
        "founded_year": 2017,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "aum_millions": 300.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "esports", "gaming_infrastructure", "mobile_gaming", "web3_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Maincraft", "url": ""},
            {"name": "Nexon", "url": "https://nexon.com"},
            {"name": "Playtika", "url": "https://playtika.com"},
        ],
        "twitter_url": "https://twitter.com/BITKRAFT",
        "crunchbase_url": "https://www.crunchbase.com/organization/bitkraft-ventures",
        "is_gaming_focused": True,
    },
    {
        "name": "Griffin Gaming Partners",
        "short_name": "Griffin Gaming",
        "investor_type": "vc",
        "description": "Dedicated gaming VC investing in gaming companies across all verticals including studios, tech, and services.",
        "website": "https://www.griffingaming.com",
        "founded_year": 2019,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 235.0,
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports", "mobile_gaming"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "Scopely", "url": "https://scopely.com"},
            {"name": "Overwolf", "url": "https://overwolf.com"},
            {"name": "Nexus Mods", "url": "https://nexusmods.com"},
        ],
        "twitter_url": "https://twitter.com/griffingamingvc",
        "crunchbase_url": "https://www.crunchbase.com/organization/griffin-gaming-partners",
        "is_gaming_focused": True,
    },
    {
        "name": "Makers Fund",
        "short_name": "Makers",
        "investor_type": "vc",
        "description": "First dedicated global gaming VC. Backed by founders, operators, and investors in gaming.",
        "website": "https://www.makersfund.com",
        "founded_year": 2017,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 200.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "mobile_gaming", "social_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Amber", "url": "https://amberstudio.com"},
            {"name": "Gamesight", "url": "https://gamesight.io"},
        ],
        "twitter_url": "https://twitter.com/MakersFund",
        "crunchbase_url": "https://www.crunchbase.com/organization/makers-fund",
        "is_gaming_focused": True,
    },
    {
        "name": "Konvoy Ventures",
        "short_name": "Konvoy",
        "investor_type": "vc",
        "description": "Gaming-focused VC investing in infrastructure and technology that powers the gaming industry.",
        "website": "https://www.konvoy.vc",
        "founded_year": 2018,
        "headquarters_city": "Denver",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 110.0,
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["gaming_infrastructure", "game_tools", "esports", "streaming"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Vindex", "url": "https://vindex.gg"},
            {"name": "SteelSeries", "url": "https://steelseries.com"},
        ],
        "twitter_url": "https://twitter.com/konvoyvc",
        "crunchbase_url": "https://www.crunchbase.com/organization/konvoy-ventures",
        "is_gaming_focused": True,
    },
    {
        "name": "Play Ventures",
        "short_name": "Play",
        "investor_type": "vc",
        "description": "Early-stage gaming VC investing in mobile, PC, and emerging gaming categories globally.",
        "website": "https://www.play.vc",
        "founded_year": 2019,
        "headquarters_city": "Helsinki",
        "headquarters_country": "Finland",
        "headquarters_region": "EU",
        "fund_size_millions": 175.0,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["mobile_gaming", "game_studios", "gaming_infrastructure"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "Metacore", "url": "https://metacore.com"},
            {"name": "Lightheart Entertainment", "url": ""},
        ],
        "twitter_url": "https://twitter.com/playventuresvc",
        "crunchbase_url": "https://www.crunchbase.com/organization/play-ventures",
        "is_gaming_focused": True,
    },
    {
        "name": "Transcend Fund",
        "short_name": "Transcend",
        "investor_type": "vc",
        "description": "Early-stage gaming and interactive entertainment VC with deep industry connections.",
        "website": "https://www.transcendfund.com",
        "founded_year": 2019,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports"],
        "active_regions": ["US"],
        "crunchbase_url": "https://www.crunchbase.com/organization/transcend-fund",
        "is_gaming_focused": True,
    },
    {
        "name": "1Up Ventures",
        "short_name": "1Up",
        "investor_type": "vc",
        "description": "Gaming-first VC fund backing the next generation of gaming companies and studios.",
        "website": "https://www.1upventures.com",
        "founded_year": 2020,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios", "web3_gaming", "gaming_infrastructure"],
        "active_regions": ["US"],
        "is_gaming_focused": True,
    },
    {
        "name": "Galaxy Interactive",
        "short_name": "Galaxy Interactive",
        "investor_type": "vc",
        "description": "Gaming and interactive entertainment investment firm, part of Galaxy Digital. Strong focus on blockchain gaming and virtual worlds.",
        "website": "https://www.galaxyinteractive.io",
        "founded_year": 2018,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "fund_size_millions": 325.0,
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["web3_gaming", "vr_ar", "game_studios", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Forte", "url": "https://forte.io"},
            {"name": "Lucid Sight", "url": ""},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/galaxy-interactive",
        "is_gaming_focused": True,
    },
    {
        "name": "Overwolf Fund",
        "short_name": "Overwolf Fund",
        "investor_type": "corporate",
        "description": "Strategic fund by Overwolf backing creators and developers building gaming mods, apps, and tools for the PC gaming ecosystem.",
        "website": "https://fund.overwolf.com",
        "founded_year": 2021,
        "headquarters_city": "Tel Aviv",
        "headquarters_country": "Israel",
        "headquarters_region": "EU",
        "fund_size_millions": 50.0,
        "typical_check_min_k": 100,
        "typical_check_max_k": 5000,
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_tools", "gaming_infrastructure", "game_studios"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "CurseForge", "url": "https://curseforge.com"},
            {"name": "Nexus Mods", "url": "https://nexusmods.com"},
        ],
        "twitter_url": "https://twitter.com/overwolf",
        "is_gaming_focused": True,
    },

    # ═══════════════════════════════════════════
    # TIER-1 VCs WITH MAJOR GAMING PORTFOLIOS
    # ═══════════════════════════════════════════
    {
        "name": "Lightspeed Venture Partners",
        "short_name": "Lightspeed",
        "investor_type": "vc",
        "description": "Top-tier VC with significant gaming investments across mobile, PC, and esports.",
        "website": "https://lsvp.com",
        "founded_year": 2000,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "game_studios", "esports", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Snap", "url": "https://snap.com"},
            {"name": "Epic Games", "url": "https://epicgames.com"},
        ],
        "twitter_url": "https://twitter.com/lightspeedvp",
        "crunchbase_url": "https://www.crunchbase.com/organization/lightspeed-venture-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "Sequoia Capital",
        "short_name": "Sequoia",
        "investor_type": "vc",
        "description": "Legendary Silicon Valley VC with major gaming portfolio companies including Roblox, Epic, and more.",
        "website": "https://sequoiacap.com",
        "founded_year": 1972,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth", "late_stage"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "mobile_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Roblox", "url": "https://roblox.com"},
            {"name": "Unity Technologies", "url": "https://unity.com"},
        ],
        "twitter_url": "https://twitter.com/sequoia",
        "crunchbase_url": "https://www.crunchbase.com/organization/sequoia-capital",
        "is_gaming_focused": False,
    },
    {
        "name": "Accel Partners",
        "short_name": "Accel",
        "investor_type": "vc",
        "description": "Global VC with notable gaming investments including Supercell, Zynga, and Scopely.",
        "website": "https://accel.com",
        "founded_year": 1983,
        "headquarters_city": "Palo Alto",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "game_studios", "social_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "Scopely", "url": "https://scopely.com"},
        ],
        "twitter_url": "https://twitter.com/accel",
        "crunchbase_url": "https://www.crunchbase.com/organization/accel-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "Bessemer Venture Partners",
        "short_name": "BVP",
        "investor_type": "vc",
        "description": "Long-standing VC with investments across game studios, esports platforms, and gaming infrastructure.",
        "website": "https://bvp.com",
        "founded_year": 1911,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "Twitch", "url": "https://twitch.tv"},
        ],
        "twitter_url": "https://twitter.com/BessemerVP",
        "crunchbase_url": "https://www.crunchbase.com/organization/bessemer-venture-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "Index Ventures",
        "short_name": "Index",
        "investor_type": "vc",
        "description": "European and global VC with strong gaming and gaming-adjacent portfolio.",
        "website": "https://indexventures.com",
        "founded_year": 1996,
        "headquarters_city": "London",
        "headquarters_country": "United Kingdom",
        "headquarters_region": "EU",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["EU", "US"],
        "notable_portfolio": [
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "King", "url": "https://king.com"},
        ],
        "twitter_url": "https://twitter.com/indexventures",
        "crunchbase_url": "https://www.crunchbase.com/organization/index-ventures",
        "is_gaming_focused": False,
    },
    {
        "name": "Benchmark Capital",
        "short_name": "Benchmark",
        "investor_type": "vc",
        "description": "Elite early-stage VC with gaming investments including Discord and others.",
        "website": "https://benchmark.com",
        "founded_year": 1995,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["gaming_infrastructure", "social_gaming", "game_studios"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Discord", "url": "https://discord.com"},
        ],
        "twitter_url": "https://twitter.com/benchmarkcap",
        "crunchbase_url": "https://www.crunchbase.com/organization/benchmark",
        "is_gaming_focused": False,
    },
    {
        "name": "Insight Partners",
        "short_name": "Insight",
        "investor_type": "vc",
        "description": "Growth-stage VC with major gaming and esports portfolio including ESL and FACEIT.",
        "website": "https://insightpartners.com",
        "founded_year": 1995,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "aum_millions": 90000.0,
        "investment_stages": ["series_b", "growth", "late_stage"],
        "focus_areas": ["esports", "gaming_infrastructure", "game_studios"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "ESL Gaming", "url": "https://eslgaming.com"},
            {"name": "FACEIT", "url": "https://faceit.com"},
        ],
        "twitter_url": "https://twitter.com/insightpartners",
        "crunchbase_url": "https://www.crunchbase.com/organization/insight-venture-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "CRV (Charles River Ventures)",
        "short_name": "CRV",
        "investor_type": "vc",
        "description": "Early-stage VC with gaming portfolio including game tool companies and emerging platforms.",
        "website": "https://crv.com",
        "founded_year": 1970,
        "headquarters_city": "Cambridge",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_tools", "gaming_infrastructure", "game_studios"],
        "active_regions": ["US"],
        "twitter_url": "https://twitter.com/CRV",
        "crunchbase_url": "https://www.crunchbase.com/organization/charles-river-ventures",
        "is_gaming_focused": False,
    },
    {
        "name": "Greycroft",
        "short_name": "Greycroft",
        "investor_type": "vc",
        "description": "Multi-stage VC with mobile gaming investments and portfolio including Scopely and Bazooka.",
        "website": "https://greycroft.com",
        "founded_year": 2006,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["mobile_gaming", "game_studios"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Scopely", "url": "https://scopely.com"},
        ],
        "twitter_url": "https://twitter.com/greycroft",
        "crunchbase_url": "https://www.crunchbase.com/organization/greycroft-partners",
        "is_gaming_focused": False,
    },
    {
        "name": "First Round Capital",
        "short_name": "First Round",
        "investor_type": "vc",
        "description": "Seed-stage VC with several gaming and gaming-infrastructure bets.",
        "website": "https://firstround.com",
        "founded_year": 2004,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios", "gaming_infrastructure"],
        "active_regions": ["US"],
        "twitter_url": "https://twitter.com/firstround",
        "crunchbase_url": "https://www.crunchbase.com/organization/first-round-capital",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # CORPORATE / STRATEGIC INVESTORS
    # ═══════════════════════════════════════════
    {
        "name": "Tencent Holdings",
        "short_name": "Tencent",
        "investor_type": "corporate",
        "description": "World's largest gaming company and prolific strategic investor. Holds stakes in Riot Games, Epic, Ubisoft, Activision-Blizzard, and hundreds more.",
        "website": "https://tencent.com",
        "founded_year": 1998,
        "headquarters_city": "Shenzhen",
        "headquarters_country": "China",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth", "late_stage"],
        "focus_areas": ["game_studios", "esports", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Riot Games", "url": "https://riotgames.com"},
            {"name": "Epic Games", "url": "https://epicgames.com"},
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "Ubisoft", "url": "https://ubisoft.com"},
        ],
        "total_known_investments": 100,
        "twitter_url": "https://twitter.com/Tencent",
        "crunchbase_url": "https://www.crunchbase.com/organization/tencent",
        "is_gaming_focused": True,
    },
    {
        "name": "NetEase Capital",
        "short_name": "NetEase",
        "investor_type": "corporate",
        "description": "Chinese internet and gaming giant with global strategic investments in game studios.",
        "website": "https://netease.com",
        "founded_year": 1997,
        "headquarters_city": "Guangzhou",
        "headquarters_country": "China",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Bungie", "url": "https://bungie.net"},
            {"name": "Quantic Dream", "url": "https://quanticdream.com"},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/netease",
        "is_gaming_focused": True,
    },
    {
        "name": "Sony Innovation Fund",
        "short_name": "Sony Ventures",
        "investor_type": "corporate",
        "description": "Sony's corporate venture arm, investing in game developers, VR/AR, and entertainment tech.",
        "website": "https://www.sonyinnovationfund.com",
        "founded_year": 2016,
        "headquarters_city": "Tokyo",
        "headquarters_country": "Japan",
        "headquarters_region": "APAC",
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "vr_ar", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Harmonix", "url": "https://harmonixmusic.com"},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/sony-innovation-fund",
        "is_gaming_focused": False,
    },
    {
        "name": "Microsoft M12",
        "short_name": "M12",
        "investor_type": "corporate",
        "description": "Microsoft's venture fund investing in enterprise and gaming technology companies.",
        "website": "https://m12.vc",
        "founded_year": 2016,
        "headquarters_city": "Redmond",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["gaming_infrastructure", "game_tools", "vr_ar"],
        "active_regions": ["US", "EU"],
        "twitter_url": "https://twitter.com/M12VC",
        "crunchbase_url": "https://www.crunchbase.com/organization/m12",
        "is_gaming_focused": False,
    },
    {
        "name": "Intel Capital",
        "short_name": "Intel Capital",
        "investor_type": "corporate",
        "description": "Intel's investment arm with focus on gaming technology, esports, and semiconductor adjacent bets.",
        "website": "https://intelcapital.com",
        "founded_year": 1991,
        "headquarters_city": "Santa Clara",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["gaming_infrastructure", "esports", "vr_ar"],
        "active_regions": ["US", "EU", "APAC"],
        "twitter_url": "https://twitter.com/intelcapital",
        "crunchbase_url": "https://www.crunchbase.com/organization/intel-capital",
        "is_gaming_focused": False,
    },
    {
        "name": "Krafton Game Union",
        "short_name": "Krafton",
        "investor_type": "corporate",
        "description": "PUBG parent company's strategic investment arm backing game studios globally.",
        "website": "https://krafton.com",
        "founded_year": 2020,
        "headquarters_city": "Seoul",
        "headquarters_country": "South Korea",
        "headquarters_region": "APAC",
        "fund_size_millions": 1000.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "mobile_gaming", "web3_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Bluehole", "url": ""},
            {"name": "RisingWings", "url": ""},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/krafton",
        "is_gaming_focused": True,
    },
    {
        "name": "Kakao Investment",
        "short_name": "Kakao",
        "investor_type": "corporate",
        "description": "Korean internet giant's investment arm, active in mobile gaming and esports.",
        "website": "https://kakaocorp.com",
        "founded_year": 2010,
        "headquarters_city": "Seongnam",
        "headquarters_country": "South Korea",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "esports", "social_gaming"],
        "active_regions": ["APAC"],
        "crunchbase_url": "https://www.crunchbase.com/organization/kakao",
        "is_gaming_focused": False,
    },
    {
        "name": "Qualcomm Ventures",
        "short_name": "Qualcomm Ventures",
        "investor_type": "corporate",
        "description": "Strategic venture arm investing in mobile gaming, XR, and connectivity-driven gaming.",
        "website": "https://qualcommventures.com",
        "founded_year": 2000,
        "headquarters_city": "San Diego",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b"],
        "focus_areas": ["mobile_gaming", "vr_ar", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "twitter_url": "https://twitter.com/qualcommventure",
        "crunchbase_url": "https://www.crunchbase.com/organization/qualcomm-ventures",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # ESPORTS & CREATOR ECONOMY FOCUSED
    # ═══════════════════════════════════════════
    {
        "name": "Excel Esports Ventures",
        "short_name": "Excel Ventures",
        "investor_type": "corporate",
        "description": "Investment arm of Excel Esports focused on the competitive gaming and creator economy ecosystem.",
        "website": "https://excelesports.com",
        "founded_year": 2021,
        "headquarters_city": "London",
        "headquarters_country": "United Kingdom",
        "headquarters_region": "EU",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["esports", "streaming", "gaming_infrastructure"],
        "active_regions": ["EU"],
        "twitter_url": "https://twitter.com/ExcelEsports",
        "is_gaming_focused": True,
    },
    {
        "name": "Greenoaks Capital",
        "short_name": "Greenoaks",
        "investor_type": "vc",
        "description": "Long-term growth investor with large bets on gaming and interactive entertainment.",
        "website": "https://greenoaks.com",
        "founded_year": 2012,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["growth", "late_stage"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Nubank", "url": "https://nubank.com.br"},
            {"name": "Duolingo", "url": "https://duolingo.com"},
        ],
        "is_gaming_focused": False,
    },
    {
        "name": "NetEase Games Investment",
        "short_name": "NetEase Games",
        "investor_type": "corporate",
        "description": "Strategic gaming investments from NetEase focusing on global game studio partnerships.",
        "website": "https://game.163.com",
        "founded_year": 2000,
        "headquarters_city": "Guangzhou",
        "headquarters_country": "China",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Blizzard Entertainment (licensed)", "url": "https://blizzard.com"},
        ],
        "is_gaming_focused": True,
    },
    {
        "name": "Comcast Ventures",
        "short_name": "Comcast Ventures",
        "investor_type": "corporate",
        "description": "Comcast NBCUniversal's VC arm with strategic gaming, streaming, and entertainment investments.",
        "website": "https://comcastventures.com",
        "founded_year": 1999,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["streaming", "esports", "gaming_infrastructure"],
        "active_regions": ["US"],
        "twitter_url": "https://twitter.com/comcastventures",
        "crunchbase_url": "https://www.crunchbase.com/organization/comcast-ventures",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # ACCELERATORS
    # ═══════════════════════════════════════════
    {
        "name": "Y Combinator",
        "short_name": "YC",
        "investor_type": "accelerator",
        "description": "World's most prestigious startup accelerator with notable gaming, game-tool, and esports alumni.",
        "website": "https://ycombinator.com",
        "founded_year": 2005,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "typical_check_min_k": 500,
        "typical_check_max_k": 500,
        "investment_stages": ["pre_seed"],
        "focus_areas": ["game_studios", "game_tools", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Twitch", "url": "https://twitch.tv"},
            {"name": "Amplitude", "url": "https://amplitude.com"},
        ],
        "twitter_url": "https://twitter.com/ycombinator",
        "crunchbase_url": "https://www.crunchbase.com/organization/y-combinator",
        "is_gaming_focused": False,
    },
    {
        "name": "GameFounders",
        "short_name": "GameFounders",
        "investor_type": "accelerator",
        "description": "World's first games-focused accelerator, backing early-stage game studios globally.",
        "website": "https://gamefounders.com",
        "founded_year": 2012,
        "headquarters_city": "Tallinn",
        "headquarters_country": "Estonia",
        "headquarters_region": "EU",
        "typical_check_min_k": 25,
        "typical_check_max_k": 50,
        "investment_stages": ["pre_seed"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["EU", "APAC"],
        "is_gaming_focused": True,
    },
    {
        "name": "GameBC",
        "short_name": "GameBC",
        "investor_type": "accelerator",
        "description": "Game-focused accelerator in British Columbia supporting indie game studios.",
        "website": "https://gamebc.ca",
        "founded_year": 2018,
        "headquarters_city": "Vancouver",
        "headquarters_country": "Canada",
        "headquarters_region": "US",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios"],
        "active_regions": ["US"],
        "is_gaming_focused": True,
    },

    # ═══════════════════════════════════════════
    # DEDICATED GAMING VCs — ADDITIONAL
    # ═══════════════════════════════════════════
    {
        "name": "Hiro Capital",
        "short_name": "Hiro",
        "investor_type": "vc",
        "description": "European VC focused on gaming, esports, metaverse, and sports tech. Partners include Ian Livingstone and Cherry Freeman.",
        "website": "https://www.hirocapital.com",
        "founded_year": 2019,
        "headquarters_city": "London",
        "headquarters_country": "United Kingdom",
        "headquarters_region": "EU",
        "fund_size_millions": 120.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "esports", "vr_ar", "gaming_infrastructure"],
        "active_regions": ["EU", "US"],
        "notable_portfolio": [
            {"name": "Antstream Arcade", "url": "https://antstream.com"},
            {"name": "nDreams", "url": "https://ndreams.com"},
        ],
        "twitter_url": "https://twitter.com/HiroCapital_",
        "crunchbase_url": "https://www.crunchbase.com/organization/hiro-capital",
        "is_gaming_focused": True,
    },
    {
        "name": "Vgames",
        "short_name": "Vgames",
        "investor_type": "vc",
        "description": "Israel-based venture fund exclusively focused on gaming. Backed by gaming executives and operators.",
        "website": "https://www.vgames.vc",
        "founded_year": 2019,
        "headquarters_city": "Tel Aviv",
        "headquarters_country": "Israel",
        "headquarters_region": "EU",
        "fund_size_millions": 80.0,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "Overwolf", "url": "https://overwolf.com"},
            {"name": "Playtika", "url": "https://playtika.com"},
        ],
        "twitter_url": "https://twitter.com/VgamesFund",
        "crunchbase_url": "https://www.crunchbase.com/organization/vgames",
        "is_gaming_focused": True,
    },
    {
        "name": "Lumikai",
        "short_name": "Lumikai",
        "investor_type": "vc",
        "description": "India's first dedicated gaming and interactive media VC fund, backing the next wave of Indian game studios and tech.",
        "website": "https://www.lumikai.com",
        "founded_year": 2021,
        "headquarters_city": "Bengaluru",
        "headquarters_country": "India",
        "headquarters_region": "APAC",
        "fund_size_millions": 50.0,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure", "esports"],
        "active_regions": ["APAC"],
        "notable_portfolio": [
            {"name": "WinZO", "url": "https://winzogames.com"},
            {"name": "Gameberry Labs", "url": ""},
        ],
        "twitter_url": "https://twitter.com/LumikaiVC",
        "crunchbase_url": "https://www.crunchbase.com/organization/lumikai",
        "is_gaming_focused": True,
    },
    {
        "name": "GameGroove Capital",
        "short_name": "GameGroove",
        "investor_type": "vc",
        "description": "Vienna-based gaming VC backing early-stage game studios and gaming technology companies across Europe.",
        "website": "https://www.gamegroovecapital.com",
        "founded_year": 2020,
        "headquarters_city": "Vienna",
        "headquarters_country": "Austria",
        "headquarters_region": "EU",
        "investment_stages": ["pre_seed", "seed"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["EU"],
        "is_gaming_focused": True,
    },

    # ═══════════════════════════════════════════
    # CORPORATE / STRATEGIC — ADDITIONAL
    # ═══════════════════════════════════════════
    {
        "name": "Animoca Brands",
        "short_name": "Animoca",
        "investor_type": "corporate",
        "description": "Hong Kong-based Web3 gaming publisher and prolific investor in blockchain gaming, NFTs, and the open metaverse.",
        "website": "https://www.animocabrands.com",
        "founded_year": 2014,
        "headquarters_city": "Hong Kong",
        "headquarters_country": "Hong Kong",
        "headquarters_region": "APAC",
        "aum_millions": 2000.0,
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["web3_gaming", "game_studios", "nft_gaming", "metaverse"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "The Sandbox", "url": "https://sandbox.game"},
            {"name": "Axie Infinity", "url": "https://axieinfinity.com"},
            {"name": "OpenSea", "url": "https://opensea.io"},
        ],
        "total_known_investments": 380,
        "twitter_url": "https://twitter.com/animocabrands",
        "crunchbase_url": "https://www.crunchbase.com/organization/animoca-brands",
        "is_gaming_focused": True,
    },
    {
        "name": "Savvy Games Group",
        "short_name": "Savvy Games",
        "investor_type": "corporate",
        "description": "Saudi Arabian sovereign wealth-backed gaming investment group. Part of the Saudi Vision 2030 initiative with a $38B commitment to gaming.",
        "website": "https://www.savvygames.com",
        "founded_year": 2021,
        "headquarters_city": "Riyadh",
        "headquarters_country": "Saudi Arabia",
        "headquarters_region": "ME",
        "fund_size_millions": 38000.0,
        "investment_stages": ["series_b", "growth", "late_stage"],
        "focus_areas": ["game_studios", "esports", "gaming_infrastructure", "mobile_gaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Scopely", "url": "https://scopely.com"},
            {"name": "ESL Gaming", "url": "https://eslgaming.com"},
            {"name": "FACEIT", "url": "https://faceit.com"},
        ],
        "twitter_url": "https://twitter.com/SavvyGamesGroup",
        "crunchbase_url": "https://www.crunchbase.com/organization/savvy-gaming-group",
        "is_gaming_focused": True,
    },
    {
        "name": "Embracer Group",
        "short_name": "Embracer",
        "investor_type": "corporate",
        "description": "Swedish gaming conglomerate and acquirer of studios across PC, console, mobile, and board games. Owns THQ Nordic, Deep Silver, Gearbox, and many more.",
        "website": "https://www.embracer.com",
        "founded_year": 2011,
        "headquarters_city": "Karlstad",
        "headquarters_country": "Sweden",
        "headquarters_region": "EU",
        "investment_stages": ["growth", "late_stage"],
        "focus_areas": ["game_studios", "mobile_gaming", "tabletop"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "THQ Nordic", "url": "https://thqnordic.com"},
            {"name": "Gearbox Software", "url": "https://gearboxsoftware.com"},
            {"name": "Deep Silver", "url": "https://deepsilver.com"},
            {"name": "Saber Interactive", "url": "https://saber.games"},
        ],
        "total_known_investments": 130,
        "twitter_url": "https://twitter.com/EmbracerGroup",
        "crunchbase_url": "https://www.crunchbase.com/organization/embracer-group",
        "is_gaming_focused": True,
    },
    {
        "name": "Modern Times Group",
        "short_name": "MTG",
        "investor_type": "corporate",
        "description": "Swedish international digital entertainment company focused on esports and gaming through ESL Gaming, DreamHack, and mobile game studios.",
        "website": "https://www.mtg.com",
        "founded_year": 1992,
        "headquarters_city": "Stockholm",
        "headquarters_country": "Sweden",
        "headquarters_region": "EU",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["esports", "game_studios", "mobile_gaming"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "ESL Gaming", "url": "https://eslgaming.com"},
            {"name": "DreamHack", "url": "https://dreamhack.com"},
            {"name": "InnoGames", "url": "https://innogames.com"},
        ],
        "twitter_url": "https://twitter.com/MTGab",
        "crunchbase_url": "https://www.crunchbase.com/organization/modern-times-group",
        "is_gaming_focused": True,
    },
    {
        "name": "Lego Ventures",
        "short_name": "Lego Ventures",
        "investor_type": "corporate",
        "description": "LEGO Group's venture arm investing in companies that explore play, creativity, and learning — including gaming and interactive entertainment.",
        "website": "https://www.legoventures.com",
        "founded_year": 2019,
        "headquarters_city": "Billund",
        "headquarters_country": "Denmark",
        "headquarters_region": "EU",
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "social_gaming", "edtech_gaming", "vr_ar"],
        "active_regions": ["EU", "US"],
        "notable_portfolio": [
            {"name": "Epic Games", "url": "https://epicgames.com"},
            {"name": "Rec Room", "url": "https://recroom.com"},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/lego-ventures",
        "is_gaming_focused": False,
    },
    {
        "name": "Take-Two Interactive Ventures",
        "short_name": "Take-Two Ventures",
        "investor_type": "corporate",
        "description": "Strategic investment and partnership arm of Take-Two Interactive (Rockstar, 2K, Zynga). Backs game studios and adjacent technology companies.",
        "website": "https://www.take2games.com",
        "founded_year": 2022,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Zynga", "url": "https://zynga.com"},
            {"name": "Social Point", "url": ""},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/take-two-interactive",
        "is_gaming_focused": True,
    },
    {
        "name": "Riot Games Ventures",
        "short_name": "Riot Ventures",
        "investor_type": "corporate",
        "description": "Riot Games' strategic investment arm backing companies that share their player-focused mission across gaming, esports, and entertainment.",
        "website": "https://riotgames.com",
        "founded_year": 2020,
        "headquarters_city": "Los Angeles",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["game_studios", "esports", "gaming_infrastructure", "streaming"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Mobalytics", "url": "https://mobalytics.gg"},
        ],
        "crunchbase_url": "https://www.crunchbase.com/organization/riot-games",
        "is_gaming_focused": True,
    },

    # ═══════════════════════════════════════════
    # DEDICATED GAMING VCs — ADDITIONAL WAVE
    # ═══════════════════════════════════════════
    {
        "name": "London Venture Partners",
        "short_name": "LVP",
        "investor_type": "vc",
        "description": "Europe's leading early-stage dedicated gaming VC, founded by gaming veterans. Backs game studios and gaming technology from seed to Series A.",
        "website": "https://www.londonvp.com",
        "founded_year": 2011,
        "headquarters_city": "London",
        "headquarters_country": "United Kingdom",
        "headquarters_region": "EU",
        "fund_size_millions": 150.0,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "Improbable", "url": "https://improbable.io"},
            {"name": "Space Ape Games", "url": "https://spaceapegames.com"},
            {"name": "Bossa Studios", "url": "https://bossastudios.com"},
        ],
        "twitter_url": "https://twitter.com/londonvp",
        "crunchbase_url": "https://www.crunchbase.com/organization/london-venture-partners",
        "is_gaming_focused": True,
    },
    {
        "name": "Kowloon Nights",
        "short_name": "Kowloon Nights",
        "investor_type": "vc",
        "description": "Dedicated gaming fund providing long-term, flexible capital to independent game developers worldwide. Offers revenue advances with no equity required.",
        "website": "https://kowloon.gg",
        "founded_year": 2019,
        "headquarters_city": "Luxembourg City",
        "headquarters_country": "Luxembourg",
        "headquarters_region": "EU",
        "fund_size_millions": 100.0,
        "typical_check_min_k": 200,
        "typical_check_max_k": 5000,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["game_studios", "indie_gaming", "pc_gaming", "console_gaming"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "Klei Entertainment", "url": "https://klei.com"},
            {"name": "Kitfox Games", "url": "https://kitfoxgames.com"},
        ],
        "twitter_url": "https://twitter.com/kowloon_nights",
        "crunchbase_url": "https://www.crunchbase.com/organization/kowloon-nights",
        "is_gaming_focused": True,
    },
    {
        "name": "NordicNinja VC",
        "short_name": "NordicNinja",
        "investor_type": "vc",
        "description": "Nordic-Japan bridge fund backed by Japanese corporates, investing in deep tech and gaming companies in the Nordics and Baltics.",
        "website": "https://nordicninja.vc",
        "founded_year": 2019,
        "headquarters_city": "Helsinki",
        "headquarters_country": "Finland",
        "headquarters_region": "EU",
        "fund_size_millions": 100.0,
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "mobile_gaming", "gaming_infrastructure"],
        "active_regions": ["EU", "APAC"],
        "twitter_url": "https://twitter.com/NordicNinjaVC",
        "crunchbase_url": "https://www.crunchbase.com/organization/nordicninja-vc",
        "is_gaming_focused": False,
    },
    {
        "name": "Delphi Digital",
        "short_name": "Delphi Digital",
        "investor_type": "vc",
        "description": "Crypto research and investment firm with one of the largest Web3 gaming portfolios. Active LP in numerous blockchain gaming protocols and studios.",
        "website": "https://delphidigital.io",
        "founded_year": 2018,
        "headquarters_city": "New York",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["web3_gaming", "nft_gaming", "gaming_infrastructure", "metaverse"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Axie Infinity", "url": "https://axieinfinity.com"},
            {"name": "Illuvium", "url": "https://illuvium.io"},
            {"name": "Star Atlas", "url": "https://staratlas.com"},
        ],
        "twitter_url": "https://twitter.com/Delphi_Digital",
        "crunchbase_url": "https://www.crunchbase.com/organization/delphi-digital",
        "is_gaming_focused": False,
    },
    {
        "name": "AppWorks",
        "short_name": "AppWorks",
        "investor_type": "accelerator",
        "description": "Taiwan's leading startup accelerator and fund with a strong Southeast Asia and gaming portfolio. Backs mobile and Web3 gaming studios in the Greater Southeast Asia region.",
        "website": "https://appworks.tw",
        "founded_year": 2010,
        "headquarters_city": "Taipei",
        "headquarters_country": "Taiwan",
        "headquarters_region": "APAC",
        "fund_size_millions": 150.0,
        "investment_stages": ["pre_seed", "seed", "series_a"],
        "focus_areas": ["mobile_gaming", "web3_gaming", "game_studios"],
        "active_regions": ["APAC"],
        "twitter_url": "https://twitter.com/AppWorks_TW",
        "crunchbase_url": "https://www.crunchbase.com/organization/appworks",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # TIER-1 VCs WITH GAMING — ADDITIONAL
    # ═══════════════════════════════════════════
    {
        "name": "SoftBank Vision Fund",
        "short_name": "SoftBank",
        "investor_type": "vc",
        "description": "World's largest technology investment fund with multi-billion-dollar bets across gaming infrastructure, mobile gaming, and esports.",
        "website": "https://visionfund.com",
        "founded_year": 2017,
        "headquarters_city": "Tokyo",
        "headquarters_country": "Japan",
        "headquarters_region": "APAC",
        "aum_millions": 100000.0,
        "investment_stages": ["growth", "late_stage"],
        "focus_areas": ["mobile_gaming", "gaming_infrastructure", "esports"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Supercell", "url": "https://supercell.com"},
            {"name": "Improbable", "url": "https://improbable.io"},
        ],
        "twitter_url": "https://twitter.com/SoftBank_Group",
        "crunchbase_url": "https://www.crunchbase.com/organization/softbank-capital",
        "is_gaming_focused": False,
    },
    {
        "name": "Kleiner Perkins",
        "short_name": "KPCB",
        "investor_type": "vc",
        "description": "Silicon Valley legend with historic gaming investments including EA, Riot Games, and Zynga. Continues to back gaming-adjacent technology.",
        "website": "https://kleinerperkins.com",
        "founded_year": 1972,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "mobile_gaming"],
        "active_regions": ["US"],
        "notable_portfolio": [
            {"name": "Riot Games", "url": "https://riotgames.com"},
            {"name": "Electronic Arts", "url": "https://ea.com"},
            {"name": "Zynga", "url": "https://zynga.com"},
        ],
        "twitter_url": "https://twitter.com/kleinerperkins",
        "crunchbase_url": "https://www.crunchbase.com/organization/kleiner-perkins-caufield-byers",
        "is_gaming_focused": False,
    },
    {
        "name": "GGV Capital",
        "short_name": "GGV",
        "investor_type": "vc",
        "description": "US-Asia cross-border fund with strong mobile gaming and interactive entertainment portfolios across both markets.",
        "website": "https://ggvc.com",
        "founded_year": 2000,
        "headquarters_city": "Menlo Park",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["mobile_gaming", "game_studios", "gaming_infrastructure"],
        "active_regions": ["US", "APAC"],
        "notable_portfolio": [
            {"name": "Roblox", "url": "https://roblox.com"},
            {"name": "Pocket Gems", "url": ""},
        ],
        "twitter_url": "https://twitter.com/GGVCapital",
        "crunchbase_url": "https://www.crunchbase.com/organization/ggv-capital",
        "is_gaming_focused": False,
    },
    {
        "name": "General Catalyst",
        "short_name": "General Catalyst",
        "investor_type": "vc",
        "description": "Multi-stage VC with notable gaming and gaming-tech investments, including major bets on Snap and gaming platforms.",
        "website": "https://generalcatalyst.com",
        "founded_year": 2000,
        "headquarters_city": "San Francisco",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["gaming_infrastructure", "game_studios", "social_gaming"],
        "active_regions": ["US", "EU"],
        "notable_portfolio": [
            {"name": "Snap", "url": "https://snap.com"},
            {"name": "ClassPass", "url": "https://classpass.com"},
        ],
        "twitter_url": "https://twitter.com/gcvp",
        "crunchbase_url": "https://www.crunchbase.com/organization/general-catalyst-partners",
        "is_gaming_focused": False,
    },

    # ═══════════════════════════════════════════
    # CORPORATE / STRATEGIC — ADDITIONAL
    # ═══════════════════════════════════════════
    {
        "name": "Epic Games Strategic",
        "short_name": "Epic Games",
        "investor_type": "corporate",
        "description": "Fortnite and Unreal Engine creator investing strategically in game studios, metaverse infrastructure, and creator economy companies to grow its ecosystem.",
        "website": "https://epicgames.com",
        "founded_year": 2021,
        "headquarters_city": "Cary",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "metaverse", "game_tools"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Harmonix", "url": "https://harmonixmusic.com"},
            {"name": "Bandcamp", "url": "https://bandcamp.com"},
            {"name": "Mediatonic", "url": "https://mediatonic.co.uk"},
        ],
        "twitter_url": "https://twitter.com/EpicGames",
        "crunchbase_url": "https://www.crunchbase.com/organization/epic-games",
        "is_gaming_focused": True,
    },
    {
        "name": "Nexon",
        "short_name": "Nexon",
        "investor_type": "corporate",
        "description": "Korean online gaming giant and global strategic investor backing game studios in North America, Europe, and Asia.",
        "website": "https://nexon.com",
        "founded_year": 1994,
        "headquarters_city": "Seoul",
        "headquarters_country": "South Korea",
        "headquarters_region": "APAC",
        "investment_stages": ["series_a", "series_b", "growth"],
        "focus_areas": ["game_studios", "mobile_gaming", "pc_gaming"],
        "active_regions": ["APAC", "US", "EU"],
        "notable_portfolio": [
            {"name": "Bungie", "url": "https://bungie.net"},
            {"name": "NEOPLE", "url": ""},
        ],
        "twitter_url": "https://twitter.com/NexonAmerica",
        "crunchbase_url": "https://www.crunchbase.com/organization/nexon",
        "is_gaming_focused": True,
    },
    {
        "name": "Supercell Invest",
        "short_name": "Supercell",
        "investor_type": "corporate",
        "description": "Clash of Clans creator's strategic investment arm backing promising independent game studios worldwide, offering capital and mentorship.",
        "website": "https://supercell.com",
        "founded_year": 2016,
        "headquarters_city": "Helsinki",
        "headquarters_country": "Finland",
        "headquarters_region": "EU",
        "investment_stages": ["seed", "series_a"],
        "focus_areas": ["game_studios", "mobile_gaming"],
        "active_regions": ["EU", "US", "APAC"],
        "notable_portfolio": [
            {"name": "Space Ape Games", "url": "https://spaceapegames.com"},
            {"name": "Frogmind", "url": "https://frogmind.com"},
        ],
        "twitter_url": "https://twitter.com/Supercell",
        "crunchbase_url": "https://www.crunchbase.com/organization/supercell",
        "is_gaming_focused": True,
    },
    {
        "name": "Electronic Arts Ventures",
        "short_name": "EA Ventures",
        "investor_type": "corporate",
        "description": "Electronic Arts' strategic investment arm funding companies in game technology, esports, and adjacent interactive entertainment.",
        "website": "https://ea.com",
        "founded_year": 2018,
        "headquarters_city": "Redwood City",
        "headquarters_country": "United States",
        "headquarters_region": "US",
        "investment_stages": ["seed", "series_a", "series_b"],
        "focus_areas": ["game_studios", "gaming_infrastructure", "esports", "game_tools"],
        "active_regions": ["US", "EU", "APAC"],
        "notable_portfolio": [
            {"name": "Improbable", "url": "https://improbable.io"},
            {"name": "Metalhead Software", "url": ""},
        ],
        "twitter_url": "https://twitter.com/EA",
        "crunchbase_url": "https://www.crunchbase.com/organization/electronic-arts",
        "is_gaming_focused": True,
    },
]


def seed_investors(db: Session) -> int:
    """Seed the database with known gaming investors. Returns the number of new entries added."""
    from app.models.investor import GamingInvestor
    added = 0
    for data in GAMING_INVESTORS:
        existing = db.query(GamingInvestor).filter(GamingInvestor.name == data["name"]).first()
        if not existing:
            investor = GamingInvestor(**data)
            db.add(investor)
            added += 1
    db.commit()
    return added
