from sqlalchemy.orm import Session


GAMING_STREAMERS = [
    # ═══════════════════════════════════════════
    # TWITCH — TOP ENGLISH STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Ninja",
        "primary_platform": "twitch",
        "twitch_username": "ninja",
        "twitch_url": "https://www.twitch.tv/ninja",
        "twitch_followers": 19000000,
        "twitch_avg_viewers": 15000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCYHMCKzmyTFMFb2Ve43weoA",
        "youtube_channel_name": "Ninja",
        "youtube_url": "https://www.youtube.com/c/NinjasHyper",
        "youtube_subscribers": 24000000,
        "x_username": "Ninja",
        "x_url": "https://x.com/Ninja",
        "x_followers": 7200000,
        "game_focus": ["Fortnite", "Valorant", "Battle Royale", "FPS"],
        "content_types": ["live_streaming", "highlights"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 50000000,
    },
    {
        "name": "xQc",
        "primary_platform": "twitch",
        "twitch_username": "xqc",
        "twitch_url": "https://www.twitch.tv/xqc",
        "twitch_followers": 12500000,
        "twitch_avg_viewers": 55000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCmua5-MT-OsxofiGQGEQVpQ",
        "youtube_channel_name": "xQc",
        "youtube_url": "https://www.youtube.com/c/xQcOW",
        "youtube_subscribers": 2500000,
        "x_username": "xQc",
        "x_url": "https://x.com/xQc",
        "x_followers": 1800000,
        "game_focus": ["Variety", "Just Chatting", "GTA V", "Overwatch"],
        "content_types": ["live_streaming", "reaction", "variety"],
        "language": "en",
        "country": "Canada",
        "region": "US",
        "total_followers": 17000000,
    },
    {
        "name": "Shroud",
        "primary_platform": "twitch",
        "twitch_username": "shroud",
        "twitch_url": "https://www.twitch.tv/shroud",
        "twitch_followers": 10800000,
        "twitch_avg_viewers": 30000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCoz3Kpu4iZXBvO4rw0rMmHg",
        "youtube_channel_name": "shroud",
        "youtube_url": "https://www.youtube.com/c/shroud",
        "youtube_subscribers": 7000000,
        "x_username": "shroud",
        "x_url": "https://x.com/shroud",
        "x_followers": 1700000,
        "game_focus": ["FPS", "Valorant", "CS2", "Apex Legends", "Variety"],
        "content_types": ["live_streaming", "fps_gameplay"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 19500000,
    },
    {
        "name": "NICKMERCS",
        "primary_platform": "twitch",
        "twitch_username": "nickmercs",
        "twitch_url": "https://www.twitch.tv/nickmercs",
        "twitch_followers": 7200000,
        "twitch_avg_viewers": 22000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UC3OoR0JJrTljGbMbBmDVOWw",
        "youtube_channel_name": "NICKMERCS",
        "youtube_url": "https://www.youtube.com/c/NICKMERCS",
        "youtube_subscribers": 4800000,
        "x_username": "NICKMERCS",
        "x_url": "https://x.com/NICKMERCS",
        "x_followers": 1500000,
        "game_focus": ["Warzone", "Fortnite", "Battle Royale", "FPS"],
        "content_types": ["live_streaming", "competitive"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 13500000,
    },
    {
        "name": "TimTheTatman",
        "primary_platform": "twitch",
        "twitch_username": "timthetatman",
        "twitch_url": "https://www.twitch.tv/timthetatman",
        "twitch_followers": 6200000,
        "twitch_avg_viewers": 16000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCiYLHlIBJIoF8GOzFE5vLGg",
        "youtube_channel_name": "TimTheTatman",
        "youtube_url": "https://www.youtube.com/c/timthetatman",
        "youtube_subscribers": 3500000,
        "x_username": "timthetatman",
        "x_url": "https://x.com/timthetatman",
        "x_followers": 1200000,
        "game_focus": ["Variety", "Warzone", "Fortnite", "FPS"],
        "content_types": ["live_streaming", "variety", "comedy"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 10900000,
    },
    {
        "name": "Pokimane",
        "primary_platform": "twitch",
        "twitch_username": "pokimane",
        "twitch_url": "https://www.twitch.tv/pokimane",
        "twitch_followers": 9300000,
        "twitch_avg_viewers": 18000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCi_fILPkEBlB9KVGmPbtScQ",
        "youtube_channel_name": "Pokimane",
        "youtube_url": "https://www.youtube.com/c/pokimane",
        "youtube_subscribers": 7500000,
        "x_username": "pokimanelol",
        "x_url": "https://x.com/pokimanelol",
        "x_followers": 5400000,
        "game_focus": ["Variety", "League of Legends", "Among Us", "Valorant"],
        "content_types": ["live_streaming", "just_chatting", "variety"],
        "language": "en",
        "country": "Canada",
        "region": "US",
        "total_followers": 22000000,
    },
    {
        "name": "Summit1g",
        "primary_platform": "twitch",
        "twitch_username": "summit1g",
        "twitch_url": "https://www.twitch.tv/summit1g",
        "twitch_followers": 6100000,
        "twitch_avg_viewers": 12000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCFh1XT7rsQma9BvpYBZ7kRw",
        "youtube_channel_name": "summit1g",
        "youtube_url": "https://www.youtube.com/c/summit1g",
        "youtube_subscribers": 1200000,
        "x_username": "summit1g",
        "x_url": "https://x.com/summit1g",
        "x_followers": 900000,
        "game_focus": ["Variety", "CS:GO", "Sea of Thieves", "Rust"],
        "content_types": ["live_streaming", "variety"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 8200000,
    },
    {
        "name": "Asmongold",
        "primary_platform": "twitch",
        "twitch_username": "asmongold",
        "twitch_url": "https://www.twitch.tv/asmongold",
        "twitch_followers": 4800000,
        "twitch_avg_viewers": 28000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCHVEVMdlYoS-c2aqoFYXN-A",
        "youtube_channel_name": "Asmongold TV",
        "youtube_url": "https://www.youtube.com/c/AsmongoldTV",
        "youtube_subscribers": 3100000,
        "x_username": "Asmongold",
        "x_url": "https://x.com/Asmongold",
        "x_followers": 1200000,
        "game_focus": ["MMORPG", "World of Warcraft", "FFXIV", "Variety"],
        "content_types": ["live_streaming", "reaction", "commentary"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 9100000,
    },
    {
        "name": "Mizkif",
        "primary_platform": "twitch",
        "twitch_username": "mizkif",
        "twitch_url": "https://www.twitch.tv/mizkif",
        "twitch_followers": 2400000,
        "twitch_avg_viewers": 14000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCsNSEyVZqpQi8QD-gHkKgVA",
        "youtube_channel_name": "Mizkif",
        "youtube_url": "https://www.youtube.com/c/Mizkif",
        "youtube_subscribers": 900000,
        "x_username": "REALMizkif",
        "x_url": "https://x.com/REALMizkif",
        "x_followers": 800000,
        "game_focus": ["Variety", "Just Chatting"],
        "content_types": ["live_streaming", "variety", "comedy"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 4100000,
    },
    {
        "name": "DrDisrespect",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCiWUud0dBgMdaRFDfxeAl5g",
        "youtube_channel_name": "DrDisrespect",
        "youtube_url": "https://www.youtube.com/c/DrDisrespect",
        "youtube_subscribers": 4200000,
        "x_username": "drdisrespect",
        "x_url": "https://x.com/drdisrespect",
        "x_followers": 3800000,
        "game_focus": ["FPS", "Battle Royale", "Warzone", "Competitive"],
        "content_types": ["live_streaming", "highlights", "entertainment"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 8000000,
    },
    {
        "name": "Valkyrae",
        "primary_platform": "youtube",
        "twitch_username": "valkyrae",
        "twitch_url": "https://www.twitch.tv/valkyrae",
        "twitch_followers": 3700000,
        "youtube_channel_id": "UCDkpfJMRvzx08Y9KV6SGUPQ",
        "youtube_channel_name": "Valkyrae",
        "youtube_url": "https://www.youtube.com/c/Valkyrae1",
        "youtube_subscribers": 3800000,
        "x_username": "Valkyrae",
        "x_url": "https://x.com/Valkyrae",
        "x_followers": 1600000,
        "game_focus": ["Variety", "Among Us", "Valorant", "Horror"],
        "content_types": ["live_streaming", "variety"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 9100000,
    },
    {
        "name": "Sykkuno",
        "primary_platform": "youtube",
        "twitch_username": "sykkuno",
        "twitch_url": "https://www.twitch.tv/sykkuno",
        "twitch_followers": 3600000,
        "youtube_channel_id": "UCrPseYLGpNygVi34QpGNqpA",
        "youtube_channel_name": "Sykkuno",
        "youtube_url": "https://www.youtube.com/c/Sykkuno",
        "youtube_subscribers": 3700000,
        "x_username": "Sykkuno",
        "x_url": "https://x.com/Sykkuno",
        "x_followers": 1000000,
        "game_focus": ["Variety", "Among Us", "GTA V", "Genshin Impact"],
        "content_types": ["live_streaming", "variety"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 8300000,
    },
    {
        "name": "MoistCr1TiKaL",
        "primary_platform": "twitch",
        "twitch_username": "moistcr1tikal",
        "twitch_url": "https://www.twitch.tv/moistcr1tikal",
        "twitch_followers": 2300000,
        "twitch_avg_viewers": 20000,
        "youtube_channel_id": "UCq6aw03lNILzV96UvEAASfQ",
        "youtube_channel_name": "penguinz0",
        "youtube_url": "https://www.youtube.com/c/penguinz0",
        "youtube_subscribers": 15000000,
        "x_username": "MoistCr1TiKaL",
        "x_url": "https://x.com/MoistCr1TiKaL",
        "x_followers": 2700000,
        "game_focus": ["Variety", "Action", "Fighting Games", "Souls"],
        "content_types": ["live_streaming", "commentary", "reviews", "variety"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 20000000,
    },
    {
        "name": "CouRageJD",
        "primary_platform": "youtube",
        "twitch_username": "couragejd",
        "twitch_url": "https://www.twitch.tv/couragejd",
        "youtube_channel_id": "UCR1QLdHAyMFT3p4V7-YDxhg",
        "youtube_channel_name": "CouRage",
        "youtube_url": "https://www.youtube.com/c/CouRageJD",
        "youtube_subscribers": 3300000,
        "x_username": "CouRageJD",
        "x_url": "https://x.com/CouRageJD",
        "x_followers": 1300000,
        "game_focus": ["Fortnite", "Battle Royale", "FPS", "Variety"],
        "content_types": ["live_streaming", "highlights", "variety"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 4600000,
    },
    {
        "name": "SypherPK",
        "primary_platform": "twitch",
        "twitch_username": "sypherpk",
        "twitch_url": "https://www.twitch.tv/sypherpk",
        "twitch_followers": 4900000,
        "twitch_avg_viewers": 10000,
        "youtube_channel_id": "UCeO36WDVGnTSXXQj5bGqXBQ",
        "youtube_channel_name": "SypherPK",
        "youtube_url": "https://www.youtube.com/c/SypherPK",
        "youtube_subscribers": 6000000,
        "x_username": "SypherPK",
        "x_url": "https://x.com/SypherPK",
        "x_followers": 1100000,
        "game_focus": ["Fortnite", "Battle Royale"],
        "content_types": ["live_streaming", "tutorials", "gameplay_analysis"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 12000000,
    },
    {
        "name": "DrLupo",
        "primary_platform": "twitch",
        "twitch_username": "drlupo",
        "twitch_url": "https://www.twitch.tv/drlupo",
        "twitch_followers": 4600000,
        "youtube_channel_id": "UCMEFqUTJoBBxePeGJLCHE9A",
        "youtube_channel_name": "DrLupo",
        "youtube_url": "https://www.youtube.com/c/DrLupo",
        "youtube_subscribers": 1400000,
        "x_username": "DrLupo",
        "x_url": "https://x.com/DrLupo",
        "x_followers": 1100000,
        "game_focus": ["Fortnite", "Destiny", "Battle Royale", "FPS"],
        "content_types": ["live_streaming", "charity", "competitive"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 7100000,
    },

    # ═══════════════════════════════════════════
    # YOUTUBE-PRIMARY GAMING CREATORS
    # ═══════════════════════════════════════════
    {
        "name": "PewDiePie",
        "primary_platform": "youtube",
        "youtube_channel_id": "UC-lHJZR3Gqxm24_Vd_AJ5Yw",
        "youtube_channel_name": "PewDiePie",
        "youtube_url": "https://www.youtube.com/c/PewDiePie",
        "youtube_subscribers": 111000000,
        "youtube_total_views": 29000000000,
        "x_username": "pewdiepie",
        "x_url": "https://x.com/pewdiepie",
        "x_followers": 21000000,
        "game_focus": ["Variety", "Horror", "Indie", "Minecraft"],
        "content_types": ["let's_play", "commentary", "variety"],
        "language": "en",
        "country": "Sweden",
        "region": "EU",
        "total_followers": 132000000,
    },
    {
        "name": "Markiplier",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCX6OQ3DkcsbYNE6H8uQQuVA",
        "youtube_channel_name": "Markiplier",
        "youtube_url": "https://www.youtube.com/c/markiplier",
        "youtube_subscribers": 37000000,
        "x_username": "markiplier",
        "x_url": "https://x.com/markiplier",
        "x_followers": 5900000,
        "game_focus": ["Horror", "Indie", "Variety", "Simulator"],
        "content_types": ["let's_play", "commentary", "shorts"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 43000000,
    },
    {
        "name": "jacksepticeye",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCYzPXprvl5Y-Sf0g4vX-m6g",
        "youtube_channel_name": "jacksepticeye",
        "youtube_url": "https://www.youtube.com/c/jacksepticeye",
        "youtube_subscribers": 33000000,
        "x_username": "Jack_Septic_Eye",
        "x_url": "https://x.com/Jack_Septic_Eye",
        "x_followers": 5400000,
        "game_focus": ["Variety", "Indie", "Horror", "Action-Adventure"],
        "content_types": ["let's_play", "commentary", "variety"],
        "language": "en",
        "country": "Ireland",
        "region": "EU",
        "total_followers": 38400000,
    },
    {
        "name": "VanossGaming",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCCwLl21jBEkVWQnGCGjMXHA",
        "youtube_channel_name": "VanossGaming",
        "youtube_url": "https://www.youtube.com/c/VanossGaming",
        "youtube_subscribers": 26000000,
        "x_username": "VanossGaming",
        "x_url": "https://x.com/VanossGaming",
        "x_followers": 2700000,
        "game_focus": ["GTA V", "Call of Duty", "Horror", "Co-op"],
        "content_types": ["highlights", "comedy", "montages"],
        "language": "en",
        "country": "Canada",
        "region": "US",
        "total_followers": 28700000,
    },
    {
        "name": "DanTDM",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCS5Oz6CHmeoF7vSad0qqXfw",
        "youtube_channel_name": "DanTDM",
        "youtube_url": "https://www.youtube.com/c/TheDiamondMinecart",
        "youtube_subscribers": 27000000,
        "x_username": "dantdm",
        "x_url": "https://x.com/dantdm",
        "x_followers": 2300000,
        "game_focus": ["Minecraft", "Roblox", "Pokémon", "Family"],
        "content_types": ["let's_play", "tutorials", "family_friendly"],
        "language": "en",
        "country": "United Kingdom",
        "region": "EU",
        "total_followers": 29300000,
    },
    {
        "name": "Lazarbeam",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCWaJFDFjC4pHcgI7cQ0tCcQ",
        "youtube_channel_name": "LazarBeam",
        "youtube_url": "https://www.youtube.com/c/LazarBeam",
        "youtube_subscribers": 21000000,
        "x_username": "LazarBeamYT",
        "x_url": "https://x.com/LazarBeamYT",
        "x_followers": 2800000,
        "game_focus": ["Fortnite", "Minecraft", "Variety", "Meme Gaming"],
        "content_types": ["let's_play", "comedy", "variety"],
        "language": "en",
        "country": "Australia",
        "region": "APAC",
        "total_followers": 23800000,
    },
    {
        "name": "Lachlan",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCHjjBJBAGtzmUCaFrJmGZHw",
        "youtube_channel_name": "Lachlan",
        "youtube_url": "https://www.youtube.com/c/LachlanYT",
        "youtube_subscribers": 15000000,
        "x_username": "LachlanYT",
        "x_url": "https://x.com/LachlanYT",
        "x_followers": 1400000,
        "game_focus": ["Fortnite", "Minecraft", "Battle Royale"],
        "content_types": ["let's_play", "competitive", "variety"],
        "language": "en",
        "country": "Australia",
        "region": "APAC",
        "total_followers": 16400000,
    },
    {
        "name": "TheRadBrad",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCpqXJOEqGS-TCnazcHCo0rA",
        "youtube_channel_name": "theRadBrad",
        "youtube_url": "https://www.youtube.com/c/theRadBrad",
        "youtube_subscribers": 14000000,
        "x_username": "theRadBrad",
        "x_url": "https://x.com/theRadBrad",
        "x_followers": 700000,
        "game_focus": ["AAA Walkthroughs", "Action-Adventure", "Horror", "RPG"],
        "content_types": ["walkthroughs", "let's_play", "guides"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 14700000,
    },
    {
        "name": "Typical Gamer",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCsTxWhCsm-C4kFN56WXILlQ",
        "youtube_channel_name": "Typical Gamer",
        "youtube_url": "https://www.youtube.com/c/typicalgamer",
        "youtube_subscribers": 13000000,
        "x_username": "typicalgamerYT",
        "x_url": "https://x.com/typicalgamerYT",
        "x_followers": 600000,
        "game_focus": ["GTA V", "Fortnite", "Minecraft", "Variety"],
        "content_types": ["let's_play", "highlights", "variety"],
        "language": "en",
        "country": "Canada",
        "region": "US",
        "total_followers": 13600000,
    },
    {
        "name": "Neebs Gaming",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCiDJtJKMICpb9B1qf7qjEOA",
        "youtube_channel_name": "Neebs Gaming",
        "youtube_url": "https://www.youtube.com/c/NeebsGaming",
        "youtube_subscribers": 4500000,
        "x_username": "NeebsGaming",
        "x_url": "https://x.com/NeebsGaming",
        "x_followers": 250000,
        "game_focus": ["Minecraft", "GTA V", "Battlefield", "Co-op", "Survival"],
        "content_types": ["comedy", "scripted", "let's_play", "series"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 4750000,
    },
    {
        "name": "GameXplain",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCfAPTv1LgeEWevG8X_6PUOQ",
        "youtube_channel_name": "GameXplain",
        "youtube_url": "https://www.youtube.com/c/GameXplain",
        "youtube_subscribers": 1300000,
        "x_username": "GameXplain",
        "x_url": "https://x.com/GameXplain",
        "x_followers": 390000,
        "game_focus": ["Nintendo", "Switch", "Zelda", "Mario", "Pokémon"],
        "content_types": ["news", "reviews", "analysis", "trailers"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 1690000,
    },

    # ═══════════════════════════════════════════
    # ESPORTS & COMPETITIVE
    # ═══════════════════════════════════════════
    {
        "name": "Faker",
        "primary_platform": "twitch",
        "twitch_username": "faker",
        "twitch_url": "https://www.twitch.tv/faker",
        "twitch_followers": 5200000,
        "twitch_avg_viewers": 80000,
        "twitch_is_partner": True,
        "x_username": "faker",
        "x_url": "https://x.com/faker",
        "x_followers": 2100000,
        "game_focus": ["League of Legends", "MOBA", "Esports"],
        "content_types": ["live_streaming", "competitive", "esports"],
        "language": "ko",
        "country": "South Korea",
        "region": "APAC",
        "total_followers": 7300000,
    },
    {
        "name": "Ibai",
        "primary_platform": "twitch",
        "twitch_username": "ibai",
        "twitch_url": "https://www.twitch.tv/ibai",
        "twitch_followers": 13500000,
        "twitch_avg_viewers": 70000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCpHBOi-GzW7pMrBEMqhHJZQ",
        "youtube_channel_name": "Ibai",
        "youtube_url": "https://www.youtube.com/c/ibai",
        "youtube_subscribers": 11000000,
        "x_username": "ibaillanos",
        "x_url": "https://x.com/ibaillanos",
        "x_followers": 10000000,
        "game_focus": ["Variety", "Esports", "Soccer", "Just Chatting"],
        "content_types": ["live_streaming", "events", "variety", "esports"],
        "language": "es",
        "country": "Spain",
        "region": "EU",
        "total_followers": 34500000,
    },
    {
        "name": "auronplay",
        "primary_platform": "twitch",
        "twitch_username": "auronplay",
        "twitch_url": "https://www.twitch.tv/auronplay",
        "twitch_followers": 15000000,
        "twitch_avg_viewers": 50000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCLThFOK1fJ0OkgNqMPnfBuQ",
        "youtube_channel_name": "auronplay",
        "youtube_url": "https://www.youtube.com/c/auronplay",
        "youtube_subscribers": 30000000,
        "x_username": "auronplay",
        "x_url": "https://x.com/auronplay",
        "x_followers": 4800000,
        "game_focus": ["Minecraft", "GTA V", "Variety", "Horror"],
        "content_types": ["live_streaming", "comedy", "variety"],
        "language": "es",
        "country": "Spain",
        "region": "EU",
        "total_followers": 49800000,
    },

    # ═══════════════════════════════════════════
    # JAPANESE / ASIA-PACIFIC STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Kuzuha",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCENtdFdGMVBZFAG5aDozR7g",
        "youtube_channel_name": "Kuzuha Ch.",
        "youtube_url": "https://www.youtube.com/@KuzuhaChannel",
        "youtube_subscribers": 1000000,
        "x_username": "kuzuha_1919",
        "x_url": "https://x.com/kuzuha_1919",
        "x_followers": 1500000,
        "game_focus": ["Apex Legends", "Valorant", "FPS", "Variety"],
        "content_types": ["live_streaming", "competitive"],
        "language": "ja",
        "country": "Japan",
        "region": "APAC",
        "total_followers": 2500000,
    },
    {
        "name": "Pekora",
        "primary_platform": "youtube",
        "youtube_channel_id": "UC0rs_GxRSMCuipS7Dm8bYcg",
        "youtube_channel_name": "Pekora Ch.",
        "youtube_url": "https://www.youtube.com/@PekoraChannel",
        "youtube_subscribers": 2700000,
        "x_username": "usadapekora",
        "x_url": "https://x.com/usadapekora",
        "x_followers": 2000000,
        "game_focus": ["Minecraft", "RPG", "Variety", "VTuber"],
        "content_types": ["live_streaming", "vtuber"],
        "language": "ja",
        "country": "Japan",
        "region": "APAC",
        "total_followers": 4700000,
    },

    # ═══════════════════════════════════════════
    # PORTUGUESE / BRAZILIAN STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Gaules",
        "primary_platform": "twitch",
        "twitch_username": "gaules",
        "twitch_url": "https://www.twitch.tv/gaules",
        "twitch_followers": 4200000,
        "twitch_avg_viewers": 80000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCbLMQz2JJVMmhR6UJbJbVLQ",
        "youtube_channel_name": "Gaules",
        "youtube_url": "https://www.youtube.com/@gaules",
        "youtube_subscribers": 2300000,
        "x_username": "gaules",
        "x_url": "https://x.com/gaules",
        "x_followers": 1200000,
        "game_focus": ["CS2", "CS:GO", "FPS", "Esports"],
        "content_types": ["live_streaming", "esports", "competitive"],
        "language": "pt",
        "country": "Brazil",
        "region": "US",
        "total_followers": 7700000,
    },
    {
        "name": "Cellbit",
        "primary_platform": "twitch",
        "twitch_username": "cellbit",
        "twitch_url": "https://www.twitch.tv/cellbit",
        "twitch_followers": 3100000,
        "twitch_avg_viewers": 35000,
        "twitch_is_partner": True,
        "youtube_channel_id": "UCEqKKebBMWbBuPGq9bD5S-Q",
        "youtube_channel_name": "Cellbit",
        "youtube_url": "https://www.youtube.com/@cellbit",
        "youtube_subscribers": 4500000,
        "x_username": "cellbit",
        "x_url": "https://x.com/cellbit",
        "x_followers": 800000,
        "game_focus": ["Minecraft", "RPG", "Horror", "Variety"],
        "content_types": ["live_streaming", "let's_play", "narrative"],
        "language": "pt",
        "country": "Brazil",
        "region": "US",
        "total_followers": 8400000,
    },

    # ═══════════════════════════════════════════
    # RUSSIAN STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Papich",
        "primary_platform": "twitch",
        "twitch_username": "papich",
        "twitch_url": "https://www.twitch.tv/papich",
        "twitch_followers": 1000000,
        "twitch_avg_viewers": 4000,
        "twitch_is_partner": True,
        "game_focus": ["CS:GO", "CS2", "FPS", "Variety"],
        "content_types": ["live_streaming"],
        "language": "ru",
        "country": "Russia",
        "region": "EU",
        "total_followers": 1000000,
    },
    {
        "name": "Forsen",
        "primary_platform": "twitch",
        "twitch_username": "forsen",
        "twitch_url": "https://www.twitch.tv/forsen",
        "twitch_followers": 1900000,
        "twitch_avg_viewers": 9000,
        "twitch_is_partner": True,
        "x_username": "Forsen",
        "x_url": "https://x.com/Forsen",
        "x_followers": 600000,
        "game_focus": ["Variety", "Speedrunning", "Meme Games"],
        "content_types": ["live_streaming", "variety"],
        "language": "en",
        "country": "Sweden",
        "region": "EU",
        "total_followers": 2500000,
    },

    # ═══════════════════════════════════════════
    # ESPORTS & CALL OF DUTY / WARZONE
    # ═══════════════════════════════════════════
    {
        "name": "JGOD",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCgJ6dkLnDoYr8U7dlBMSaYw",
        "youtube_channel_name": "JGOD",
        "youtube_url": "https://www.youtube.com/c/JGODYT",
        "youtube_subscribers": 1800000,
        "x_username": "JGODYT",
        "x_url": "https://x.com/JGODYT",
        "x_followers": 360000,
        "game_focus": ["Warzone", "Call of Duty", "FPS"],
        "content_types": ["tutorials", "gameplay_analysis", "guides"],
        "language": "en",
        "country": "United States",
        "region": "US",
        "total_followers": 2160000,
    },
    {
        "name": "Aculite",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCILb1gbZKRqwFP2tCG2HMEA",
        "youtube_channel_name": "Aculite",
        "youtube_url": "https://www.youtube.com/c/Aculite",
        "youtube_subscribers": 3000000,
        "game_focus": ["Apex Legends", "Warzone", "FPS", "Tactical"],
        "content_types": ["highlights", "let's_play", "montages"],
        "language": "en",
        "country": "Australia",
        "region": "APAC",
        "total_followers": 3000000,
    },
    {
        "name": "Anomaly",
        "primary_platform": "youtube",
        "youtube_channel_id": "UCo8bcnLyZH8tBIH9V1mLgqQ",
        "youtube_channel_name": "anomaly",
        "youtube_url": "https://www.youtube.com/c/anomalyxd",
        "youtube_subscribers": 3400000,
        "x_username": "AnomNomNom",
        "x_url": "https://x.com/AnomNomNom",
        "x_followers": 320000,
        "game_focus": ["CS:GO", "CS2", "Case Opening", "FPS"],
        "content_types": ["comedy", "let's_play", "cs_openings"],
        "language": "en",
        "country": "Sweden",
        "region": "EU",
        "total_followers": 3720000,
    },
]


def seed_streamers(db: Session) -> int:
    """Seed the database with known gaming streamers. Returns count of new entries added."""
    from app.models.streamer import Streamer
    added = 0
    for data in GAMING_STREAMERS:
        # Check for existing by twitch username, youtube channel id, or x username
        existing = None
        if data.get("twitch_username"):
            existing = db.query(Streamer).filter(Streamer.twitch_username == data["twitch_username"]).first()
        if not existing and data.get("youtube_channel_id"):
            existing = db.query(Streamer).filter(Streamer.youtube_channel_id == data["youtube_channel_id"]).first()
        if not existing and data.get("x_username"):
            existing = db.query(Streamer).filter(Streamer.x_username == data["x_username"]).first()

        if not existing:
            streamer = Streamer(**data)
            db.add(streamer)
            added += 1
    db.commit()
    return added
