from sqlalchemy.orm import Session

from app.models.streamer import Streamer

GAMING_STREAMERS = [
    # ═══════════════════════════════════════════
    # MEGA TIER (1M+ followers)
    # ═══════════════════════════════════════════
    {
        "name": "Ninja", "real_name": "Tyler Blevins", "url": "https://www.twitch.tv/ninja",
        "platform": "twitch", "twitch_username": "ninja", "youtube_channel": "https://www.youtube.com/user/NinjasHyper",
        "bio": "Professional gamer, streamer, and content creator. Former Halo pro turned Fortnite legend. One of the most recognized faces in gaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 19000000, "subscriber_count": 50000, "avg_viewers": 30000, "peak_viewers": 635000,
        "primary_game": "Fortnite", "games_played": ["Fortnite", "Valorant", "League of Legends", "Apex Legends"],
        "content_categories": ["FPS", "Battle Royale", "Competitive"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Ninja", "social_instagram": "ninja", "social_youtube": "NinjasHyper",
        "twitter_followers": 7000000, "instagram_followers": 12000000,
        "contact_email": "ninja@teamninjapr.com", "business_email": "business@ninja.com",
        "agency": "Loaded", "agency_url": "https://www.loaded.gg",
        "has_sponsorships": True, "past_sponsors": ["Red Bull", "Adidas", "NZXT", "Uber Eats", "Samsung"],
        "estimated_sponsorship_rate": "$50k-500k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "has_merch_store": True, "merch_url": "https://shop.ninja.com",
        "notable_achievements": ["Most followed Twitch streamer (2018-2021)", "Played Fortnite with Drake", "Times 100 Most Influential 2019"],
        "recent_milestones": ["Returned to Twitch streaming", "Launched new merch line"],
        "tags": ["fortnite", "competitive", "mainstream", "brand-friendly"],
        "audience_age_range": "13-28", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "Shroud", "real_name": "Michael Grzesiek", "url": "https://www.twitch.tv/shroud",
        "platform": "twitch", "twitch_username": "shroud", "youtube_channel": "https://www.youtube.com/user/shraborern",
        "bio": "Former CS:GO professional player for Cloud9. Known for incredible aim and FPS gameplay. The human aimbot.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 10500000, "subscriber_count": 30000, "avg_viewers": 25000, "peak_viewers": 515000,
        "primary_game": "Valorant", "games_played": ["Valorant", "CS2", "Apex Legends", "Escape from Tarkov", "New World"],
        "content_categories": ["FPS", "Tactical Shooter", "Variety"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@shraborern", "social_instagram": "shroud",
        "twitter_followers": 2500000, "instagram_followers": 3000000,
        "contact_email": "shroud@loadedgg.com", "business_email": "business@shroud.gg",
        "agency": "Loaded", "agency_url": "https://www.loaded.gg",
        "has_sponsorships": True, "past_sponsors": ["Logitech G", "Madrinas Coffee", "Postmates", "HyperX"],
        "estimated_sponsorship_rate": "$30k-200k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Former C9 CS:GO pro", "Multiple major tournament wins", "Known as 'The Human Aimbot'"],
        "tags": ["fps", "competitive", "aim-god", "tactical-shooter"],
        "audience_age_range": "18-34", "audience_top_countries": ["US", "CA", "UK", "DE"],
    },
    {
        "name": "xQc", "real_name": "Felix Lengyel", "url": "https://www.twitch.tv/xqc",
        "platform": "twitch", "twitch_username": "xqc",
        "youtube_channel": "https://www.youtube.com/channel/UCmDTrq0LNgPodDOFZiSbsww",
        "bio": "Former Overwatch League pro turned variety streamer. Known for high-energy, chaotic streams and reacting to content.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 12500000, "subscriber_count": 60000, "avg_viewers": 65000, "peak_viewers": 350000,
        "primary_game": "Variety", "games_played": ["GTA V RP", "Minecraft", "Overwatch 2", "Fortnite", "Just Chatting"],
        "content_categories": ["Variety", "Just Chatting", "FPS", "RP"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@xQc", "social_instagram": "xqcow1",
        "twitter_followers": 2200000, "instagram_followers": 1500000,
        "has_sponsorships": True, "past_sponsors": ["Lenovo Legion", "GFuel", "Samsung"],
        "estimated_sponsorship_rate": "$50k-300k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "is_esports_player": True, "esports_team": "Luminosity Gaming (former)", "esports_role": "Tank (Overwatch)",
        "notable_achievements": ["Overwatch League MVP candidate", "Most watched Twitch streamer 2022", "Set concurrent viewer records"],
        "tags": ["variety", "react", "high-energy", "massive-reach"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "UK", "FR"],
    },
    {
        "name": "Pokimane", "real_name": "Imane Anys", "url": "https://www.twitch.tv/pokimane",
        "platform": "twitch", "twitch_username": "pokimane",
        "youtube_channel": "https://www.youtube.com/c/pokimane",
        "bio": "One of the most prominent female streamers. Co-founder of OfflineTV. Known for Valorant, League, and Just Chatting content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 9300000, "subscriber_count": 15000, "avg_viewers": 15000, "peak_viewers": 200000,
        "primary_game": "Valorant", "games_played": ["Valorant", "League of Legends", "Fortnite", "Among Us"],
        "content_categories": ["FPS", "Just Chatting", "Variety"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@pokaborern", "social_instagram": "pokimane",
        "twitter_followers": 4500000, "instagram_followers": 6000000,
        "agency": "United Talent Agency", "business_email": "pokimane@unitedtalent.com",
        "has_sponsorships": True, "past_sponsors": ["CashApp", "Verizon", "NZXT", "Postmates"],
        "estimated_sponsorship_rate": "$30k-150k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Co-founder of OfflineTV", "Most followed female Twitch streamer", "Launched Midnight snack brand"],
        "tags": ["variety", "female-creator", "brand-safe", "massive-reach", "OfflineTV"],
        "audience_age_range": "16-30", "audience_gender_split": {"male": 55, "female": 40, "other": 5},
        "audience_top_countries": ["US", "CA", "UK", "AU"],
    },
    {
        "name": "TimTheTatman", "real_name": "Timothy Betar", "url": "https://www.twitch.tv/timthetatman",
        "platform": "twitch", "twitch_username": "timthetatman",
        "youtube_channel": "https://www.youtube.com/user/timthetatman",
        "bio": "Variety streamer and content creator known for Warzone, Fortnite, and Overwatch content. Part of Complexity Gaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 7500000, "subscriber_count": 20000, "avg_viewers": 20000, "peak_viewers": 300000,
        "primary_game": "Call of Duty: Warzone", "games_played": ["Warzone", "Fortnite", "Overwatch 2", "WoW"],
        "content_categories": ["FPS", "Battle Royale", "Variety"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@timthetatman", "social_instagram": "timthetatman",
        "twitter_followers": 3500000, "instagram_followers": 2500000,
        "has_sponsorships": True, "past_sponsors": ["AT&T", "Monster Energy", "Chipotle", "Audio-Technica"],
        "notable_achievements": ["Complexity Gaming co-owner", "Won Fortnite Celebrity Pro-Am", "NFL Sunday Ticket streaming"],
        "tags": ["warzone", "brand-friendly", "family-friendly", "competitive"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "CA", "UK"],
    },

    # ═══════════════════════════════════════════
    # MACRO TIER (500K-1M followers)
    # ═══════════════════════════════════════════
    {
        "name": "Valkyrae", "real_name": "Rachell Hofstetter", "url": "https://www.youtube.com/c/Valkyrae",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/Valkyrae",
        "bio": "YouTube Gaming co-owner and content creator. Known for Valorant, Fortnite, and Among Us. Co-owner of 100 Thieves.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 4000000, "avg_viewers": 20000, "peak_viewers": 170000,
        "primary_game": "Valorant", "games_played": ["Valorant", "Among Us", "Fortnite", "GTA V RP"],
        "content_categories": ["FPS", "Social Deduction", "Variety"], "content_style": "entertainment",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Valkyrae", "social_instagram": "valkyrae",
        "twitter_followers": 2800000, "instagram_followers": 3800000,
        "has_sponsorships": True, "past_sponsors": ["YouTube Gaming", "100 Thieves"],
        "notable_achievements": ["YouTube Gaming co-owner", "100 Thieves co-owner", "Content Creator of the Year 2020"],
        "tags": ["youtube-gaming", "female-creator", "esports-adjacent", "100thieves"],
        "audience_age_range": "16-28", "audience_top_countries": ["US", "PH", "CA"],
    },
    {
        "name": "DrDisrespect", "real_name": "Herschel Beahm IV", "url": "https://www.youtube.com/c/DrDisrespect",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/DrDisrespect",
        "bio": "The Two-Time. Back-to-back 1993-1994 Blockbuster Video Game Champion. Known for his character, high production value streams, and FPS gameplay.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 4500000, "avg_viewers": 25000, "peak_viewers": 510000,
        "primary_game": "Call of Duty", "games_played": ["Warzone", "PUBG", "Apex Legends", "Fortnite", "Deadrop"],
        "content_categories": ["FPS", "Battle Royale", "Shooter"], "content_style": "entertainment",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@DrDisrespect", "social_instagram": "drdisrespect",
        "twitter_followers": 2200000, "instagram_followers": 1800000,
        "has_sponsorships": True, "past_sponsors": ["Turtle Beach", "Roccat", "ASUS ROG", "Mountain Dew Game Fuel"],
        "notable_achievements": ["Former Sledgehammer Games level designer", "Developing own game studio (Midnight Society)", "Iconic streaming persona"],
        "tags": ["fps", "entertainment", "high-production", "character-streamer"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "DE", "CA"],
    },
    {
        "name": "Lirik", "url": "https://www.twitch.tv/lirik",
        "platform": "twitch", "twitch_username": "lirik",
        "bio": "One of the OG variety streamers on Twitch. Known for discovering and popularizing new games. Pioneer of variety streaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 2900000, "avg_viewers": 15000, "peak_viewers": 100000,
        "primary_game": "Variety", "games_played": ["New releases", "Indie games", "RPGs", "Survival", "MMOs"],
        "content_categories": ["Variety", "Adventure", "RPG", "Survival"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@LIRIK",
        "twitter_followers": 1200000,
        "has_sponsorships": True, "past_sponsors": ["Corsair", "DoorDash"],
        "accepts_game_codes": True,
        "notable_achievements": ["Pioneer of variety streaming", "One of first Twitch partners", "Known for discovering indie gems"],
        "tags": ["variety", "indie-friendly", "game-discovery", "og-streamer"],
        "audience_age_range": "20-35", "audience_top_countries": ["US", "EU", "CA"],
    },
    {
        "name": "CohhCarnage", "real_name": "Ben Cassell", "url": "https://www.twitch.tv/cohhcarnage",
        "platform": "twitch", "twitch_username": "cohhcarnage",
        "youtube_channel": "https://www.youtube.com/user/coaborner",
        "bio": "Family-friendly variety streamer specializing in RPGs and new game releases. Known for detailed, thorough game playthroughs.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1800000, "avg_viewers": 10000, "peak_viewers": 80000,
        "primary_game": "Variety RPG", "games_played": ["Cyberpunk 2077", "Baldur's Gate 3", "Elden Ring", "Starfield"],
        "content_categories": ["RPG", "Action-Adventure", "Variety"], "content_style": "educational",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@CohhCarnage",
        "twitter_followers": 500000,
        "contact_email": "cohh@cohhcarnage.com",
        "has_sponsorships": True, "past_sponsors": ["Corsair", "State Farm"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Known for ultra-thorough playthroughs", "One of most brand-safe streamers", "Partner with many AAA studios for launch streams"],
        "tags": ["rpg", "brand-safe", "family-friendly", "thorough", "launch-day-streamer"],
        "audience_age_range": "22-40", "audience_top_countries": ["US", "UK", "DE", "NL"],
    },
    {
        "name": "Asmongold", "real_name": "Zack Hoyt", "url": "https://www.twitch.tv/asmongold",
        "platform": "twitch", "twitch_username": "asmongold",
        "youtube_channel": "https://www.youtube.com/c/Asmongold",
        "bio": "MMO and variety streamer. Known for World of Warcraft and FFXIV content. Runs the secondary channel Zackrawrr for react content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3800000, "subscriber_count": 25000, "avg_viewers": 45000, "peak_viewers": 400000,
        "primary_game": "World of Warcraft", "games_played": ["WoW", "FFXIV", "Diablo IV", "Lost Ark", "Elden Ring"],
        "content_categories": ["MMO", "RPG", "React", "Variety"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Asmongold",
        "twitter_followers": 1500000,
        "has_sponsorships": True, "past_sponsors": ["SteelSeries", "Starforge Systems"],
        "accepts_game_codes": True,
        "notable_achievements": ["Co-founded OTK Network", "Largest MMO streamer", "Created multiple viral gaming takes"],
        "tags": ["mmo", "wow", "react", "gaming-commentary", "OTK"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "DE", "CA"],
    },

    # ═══════════════════════════════════════════
    # MID TIER (100K-500K followers)
    # ═══════════════════════════════════════════
    {
        "name": "AngryJoeShow", "real_name": "Joe Vargas", "url": "https://www.youtube.com/user/AngryJoeShow",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/user/AngryJoeShow",
        "bio": "Game reviewer and content creator known for in-depth, passionate game reviews and the Angry Joe Review series.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3700000, "avg_viewers": 50000, "peak_viewers": 200000,
        "primary_game": "Reviews", "games_played": ["AAA releases", "RPGs", "Action games"],
        "content_categories": ["Reviews", "Commentary", "News"], "content_style": "educational",
        "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@AngryJoeShow",
        "twitter_followers": 900000,
        "accepts_game_codes": True,
        "notable_achievements": ["Over 3.7M YouTube subscribers", "Known for honest brutally honest reviews", "Angry Joe Review series"],
        "tags": ["reviews", "commentary", "honest-reviews", "youtube"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "Maximilian Dood", "real_name": "Maximilian Christiansen", "url": "https://www.twitch.tv/maximilian_dood",
        "platform": "twitch", "twitch_username": "maximilian_dood",
        "youtube_channel": "https://www.youtube.com/user/Miles923",
        "bio": "Fighting game community legend. Known for FGC content, game analysis, and hosting major community events.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 800000, "avg_viewers": 8000, "peak_viewers": 50000,
        "primary_game": "Street Fighter 6", "games_played": ["Street Fighter 6", "Tekken 8", "Mortal Kombat", "Guilty Gear"],
        "content_categories": ["Fighting Games", "FGC", "Variety"], "content_style": "educational",
        "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@maximaborern",
        "twitter_followers": 400000,
        "accepts_game_codes": True,
        "notable_achievements": ["FGC community pillar", "Over 1M YouTube subscribers", "Week of series creator"],
        "tags": ["fgc", "fighting-games", "community-leader", "educational"],
        "audience_age_range": "20-38", "audience_top_countries": ["US", "JP", "MX", "BR"],
    },
    {
        "name": "Northernlion", "real_name": "Ryan Letourneau", "url": "https://www.twitch.tv/northernlion",
        "platform": "twitch", "twitch_username": "northernlion",
        "youtube_channel": "https://www.youtube.com/user/Northernlion",
        "bio": "The egg. Variety streamer and YouTube creator known for roguelike content, witty commentary, and long-running Isaac series.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 1200000, "avg_viewers": 8000, "peak_viewers": 30000,
        "primary_game": "The Binding of Isaac", "games_played": ["Isaac", "Hades", "Balatro", "Indie roguelikes"],
        "content_categories": ["Roguelike", "Indie", "Variety"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@NorthernlionLP",
        "twitter_followers": 500000,
        "accepts_game_codes": True,
        "notable_achievements": ["4000+ episode Isaac series", "Known for discovering indie gems", "Influential in roguelike genre"],
        "tags": ["roguelike", "indie", "witty", "long-form", "game-discovery"],
        "audience_age_range": "20-35", "audience_top_countries": ["US", "CA", "UK", "AU"],
    },
    {
        "name": "Sodapoppin", "real_name": "Chance Morris", "url": "https://www.twitch.tv/sodapoppin",
        "platform": "twitch", "twitch_username": "sodapoppin",
        "bio": "One of the original Twitch streamers. Known for WoW content and variety streaming. OG streamer who helped define the platform.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 8500000, "avg_viewers": 15000, "peak_viewers": 100000,
        "primary_game": "World of Warcraft", "games_played": ["WoW", "GTA V RP", "Variety", "Party games"],
        "content_categories": ["MMO", "Variety", "Just Chatting"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Sodapoppintv",
        "twitter_followers": 1400000,
        "notable_achievements": ["OG Twitch streamer", "WoW community legend", "NPC Gaming co-founder"],
        "tags": ["mmo", "wow", "og-streamer", "variety"],
        "audience_age_range": "18-32", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "Summit1g", "real_name": "Jaryd Lazar", "url": "https://www.twitch.tv/summit1g",
        "platform": "twitch", "twitch_username": "summit1g",
        "bio": "Former CS:GO professional turned variety streamer. Known for chill vibes, FPS games, and sea of thieves adventures.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 6200000, "avg_viewers": 12000, "peak_viewers": 300000,
        "primary_game": "Variety", "games_played": ["CS2", "Sea of Thieves", "GTA V RP", "Escape from Tarkov"],
        "content_categories": ["FPS", "Adventure", "Variety"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@summit1g",
        "twitter_followers": 1500000,
        "is_esports_player": True, "esports_role": "Former CS:GO pro",
        "notable_achievements": ["One of longest-running top Twitch streamers", "CS:GO pro background", "Sea of Thieves legend"],
        "tags": ["fps", "chill", "variety", "og-streamer"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "CA", "UK", "BR"],
    },

    # ═══════════════════════════════════════════
    # INTERNATIONAL STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Rubius", "real_name": "Ruben Doblas", "url": "https://www.twitch.tv/rubius",
        "platform": "twitch", "twitch_username": "rubius",
        "bio": "Spanish-speaking mega streamer. One of the biggest content creators in the Spanish-speaking world.",
        "language": "es", "region": "ES", "country": "Spain",
        "follower_count": 14500000, "avg_viewers": 50000, "peak_viewers": 1200000,
        "primary_game": "Variety", "games_played": ["Minecraft", "Fortnite", "GTA V", "Just Chatting"],
        "content_categories": ["Variety", "Entertainment", "Gaming"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Rubiu5", "social_instagram": "elrubius",
        "twitter_followers": 20000000, "instagram_followers": 16000000,
        "notable_achievements": ["Most followed Spanish Twitch streamer", "40M+ YouTube subscribers"],
        "tags": ["spanish", "mega-creator", "entertainment", "youth"],
        "audience_age_range": "13-25", "audience_top_countries": ["ES", "MX", "AR", "CO"],
    },
    {
        "name": "Gaules", "real_name": "Alexandre Borba", "url": "https://www.twitch.tv/gaules",
        "platform": "twitch", "twitch_username": "gaules",
        "bio": "Brazilian CS:GO/CS2 caster and streamer. Biggest Brazilian gaming streamer. Former professional CS 1.6 player.",
        "language": "pt", "region": "BR", "country": "Brazil",
        "follower_count": 6000000, "avg_viewers": 40000, "peak_viewers": 600000,
        "primary_game": "CS2", "games_played": ["CS2", "Valorant"],
        "content_categories": ["FPS", "Esports", "Casting"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Gaaborern",
        "twitter_followers": 1800000,
        "is_esports_player": True, "esports_role": "Former CS 1.6 pro / Caster",
        "notable_achievements": ["Biggest Brazilian Twitch streamer", "CS esports legend", "Set Brazilian concurrent viewer records"],
        "tags": ["cs2", "brazil", "esports", "casting"],
        "audience_age_range": "16-30", "audience_top_countries": ["BR", "PT"],
    },
    {
        "name": "Ibai", "real_name": "Ibai Llanos", "url": "https://www.twitch.tv/ibai",
        "platform": "twitch", "twitch_username": "ibai",
        "bio": "Spanish content creator and esports caster. Known for La Velada boxing events and massive entertainment streams.",
        "language": "es", "region": "ES", "country": "Spain",
        "follower_count": 15000000, "avg_viewers": 80000, "peak_viewers": 3400000,
        "primary_game": "Variety", "games_played": ["League of Legends", "Fortnite", "Just Chatting"],
        "content_categories": ["Entertainment", "Esports", "Events"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@IbaiLlanos", "social_instagram": "ibaillanos",
        "twitter_followers": 10000000, "instagram_followers": 10000000,
        "agency": "KOI (co-founder)",
        "has_sponsorships": True, "past_sponsors": ["Pepsi", "Adidas", "Prime"],
        "notable_achievements": ["La Velada boxing events", "Co-owner of KOI esports", "Record-breaking Twitch events", "Most watched Spanish-language stream ever"],
        "tags": ["spanish", "events", "entertainment", "esports", "boxing"],
        "audience_age_range": "14-30", "audience_top_countries": ["ES", "MX", "AR", "CO"],
    },
    {
        "name": "Fps_shaka", "real_name": "Shaka", "url": "https://www.twitch.tv/fps_shaka",
        "platform": "twitch", "twitch_username": "fps_shaka",
        "bio": "Top Japanese FPS streamer. Known for incredible Apex Legends and Valorant gameplay. Major figure in Japanese streaming.",
        "language": "ja", "region": "JP", "country": "Japan",
        "follower_count": 1200000, "avg_viewers": 15000, "peak_viewers": 80000,
        "primary_game": "Apex Legends", "games_played": ["Apex Legends", "Valorant", "PUBG"],
        "content_categories": ["FPS", "Battle Royale", "Competitive"], "content_style": "competitive",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@fps_shaka",
        "twitter_followers": 800000,
        "notable_achievements": ["Top Japanese FPS streamer", "Apex predator rank", "Japan esports community leader"],
        "tags": ["fps", "japan", "apex", "competitive"],
        "audience_age_range": "16-30", "audience_top_countries": ["JP"],
    },
    {
        "name": "Elraenn", "url": "https://www.twitch.tv/elraenn",
        "platform": "twitch", "twitch_username": "elraenn",
        "bio": "Top Turkish variety streamer. One of the most followed streamers globally. Known for gaming content and massive community events.",
        "language": "tr", "region": "TR", "country": "Turkey",
        "follower_count": 5500000, "avg_viewers": 50000, "peak_viewers": 500000,
        "primary_game": "Variety", "games_played": ["Minecraft", "GTA V", "Valorant", "League of Legends"],
        "content_categories": ["Variety", "Gaming", "Entertainment"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Elraenn",
        "twitter_followers": 3000000,
        "notable_achievements": ["Largest Turkish Twitch streamer", "Multiple Twitch records in Turkey"],
        "tags": ["turkish", "variety", "massive-community", "events"],
        "audience_age_range": "14-28", "audience_top_countries": ["TR", "DE", "AZ"],
    },
    {
        "name": "Sardoche", "real_name": "Andrzej Dubiez", "url": "https://www.twitch.tv/sardoche",
        "platform": "twitch", "twitch_username": "sardoche",
        "bio": "Top French League of Legends streamer. Known for competitive LoL gameplay and high challenger rank content.",
        "language": "fr", "region": "FR", "country": "France",
        "follower_count": 1500000, "avg_viewers": 8000, "peak_viewers": 60000,
        "primary_game": "League of Legends", "games_played": ["League of Legends", "TFT", "Valorant"],
        "content_categories": ["MOBA", "Competitive", "Strategy"], "content_style": "competitive",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Sardoche",
        "twitter_followers": 700000,
        "notable_achievements": ["Top French LoL streamer", "Challenger rank player"],
        "tags": ["league-of-legends", "french", "competitive", "moba"],
        "audience_age_range": "16-28", "audience_top_countries": ["FR", "BE", "CH", "MA"],
    },

    # ═══════════════════════════════════════════
    # SPECIALIZED / NICHE STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "DisguisedToast", "real_name": "Jeremy Wang", "url": "https://www.twitch.tv/disguisedtoast",
        "platform": "twitch", "twitch_username": "disguisedtoast",
        "bio": "Former Hearthstone pro turned variety streamer. OfflineTV member. Known for big-brain plays and strategic gaming content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3500000, "avg_viewers": 12000, "peak_viewers": 100000,
        "primary_game": "Variety", "games_played": ["TFT", "Among Us", "League of Legends", "Valorant"],
        "content_categories": ["Strategy", "Social Deduction", "Variety"], "content_style": "educational",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@DisguisedToast",
        "twitter_followers": 1200000,
        "notable_achievements": ["OfflineTV member", "Among Us streamer pioneer", "Hearthstone legend"],
        "tags": ["strategy", "offlinetv", "big-brain", "variety"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "PH", "SG"],
    },
    {
        "name": "Lethal Frag", "url": "https://www.twitch.tv/lethalfrag",
        "platform": "twitch", "twitch_username": "lethalfrag",
        "bio": "Indie game specialist and community builder. Known for supporting small developers and showcasing hidden gem indie games.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 120000, "avg_viewers": 500, "peak_viewers": 5000,
        "primary_game": "Indie Games", "games_played": ["Indie games", "Roguelikes", "Platformers"],
        "content_categories": ["Indie", "Roguelike", "Platformer"], "content_style": "educational",
        "is_variety_streamer": True, "is_partnered": True, "tier": "micro", "priority": 4,
        "social_twitter": "@LethalFrag",
        "accepts_game_codes": True,
        "notable_achievements": ["Indie game champion", "Known for discovering hidden gems", "Twitch community builder"],
        "tags": ["indie", "game-discovery", "community", "small-dev-friendly"],
        "audience_age_range": "22-40", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "SkillUp", "real_name": "Ralph Panebianco", "url": "https://www.youtube.com/c/SkillUp",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/SkillUp",
        "bio": "In-depth game reviewer and analyst. Known for thorough, thoughtful reviews and the 'This Week in Gaming' series.",
        "language": "en", "region": "AU", "country": "Australia",
        "follower_count": 1800000, "avg_viewers": 300000,
        "primary_game": "Reviews", "games_played": ["AAA releases", "RPGs", "Shooters", "Indie"],
        "content_categories": ["Reviews", "Analysis", "News"], "content_style": "educational",
        "tier": "mid", "priority": 3,
        "social_twitter": "@SkillUpYT",
        "twitter_followers": 200000,
        "accepts_game_codes": True,
        "notable_achievements": ["This Week in Gaming series", "Known for balanced in-depth reviews"],
        "tags": ["reviews", "analysis", "in-depth", "youtube", "trusted-voice"],
        "audience_age_range": "20-40", "audience_top_countries": ["US", "AU", "UK", "CA"],
    },
    {
        "name": "Girlfriend Reviews", "url": "https://www.youtube.com/c/GirlfriendReviews",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/GirlfriendReviews",
        "bio": "Unique review channel reviewing games from the perspective of watching someone else play. Humorous, heartfelt game commentary.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1600000, "avg_viewers": 500000,
        "primary_game": "Reviews", "games_played": ["AAA releases", "Indie", "RPGs", "Horror"],
        "content_categories": ["Reviews", "Comedy", "Analysis"], "content_style": "entertainment",
        "tier": "mid", "priority": 3,
        "social_twitter": "@itsgfreviews",
        "accepts_game_codes": True,
        "notable_achievements": ["Unique review format", "1.6M YouTube subscribers", "Game Awards nominee"],
        "tags": ["reviews", "comedy", "unique-format", "youtube", "couple-content"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "Amouranth", "real_name": "Kaitlyn Siragusa", "url": "https://www.twitch.tv/amouranth",
        "platform": "twitch", "twitch_username": "amouranth",
        "bio": "Top female Twitch streamer and entrepreneur. Business-focused creator with investments in multiple industries.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 6300000, "avg_viewers": 8000, "peak_viewers": 60000,
        "primary_game": "Variety", "games_played": ["Just Chatting", "ASMR", "Fortnite", "Overwatch"],
        "content_categories": ["Just Chatting", "Variety", "IRL"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 3,
        "social_twitter": "@Amouranth", "social_instagram": "amouranth",
        "twitter_followers": 2000000, "instagram_followers": 6500000,
        "has_sponsorships": True,
        "notable_achievements": ["Most-watched female streamer", "Entrepreneur and investor", "Business empire beyond streaming"],
        "tags": ["variety", "female-creator", "entrepreneur", "massive-reach"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "DE", "FR"],
    },
    {
        "name": "Kaicenat", "real_name": "Kai Cenat", "url": "https://www.twitch.tv/kaicenat",
        "platform": "twitch", "twitch_username": "kaicenat",
        "bio": "Record-breaking Twitch streamer known for marathon subathon streams and viral moments. Brought mainstream attention to Twitch.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 14000000, "avg_viewers": 100000, "peak_viewers": 700000,
        "primary_game": "Variety", "games_played": ["GTA V", "Fortnite", "Just Chatting", "Elden Ring"],
        "content_categories": ["Variety", "Entertainment", "Just Chatting"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@KaiCenat", "social_instagram": "kaicenat",
        "twitter_followers": 3000000, "instagram_followers": 9000000,
        "has_sponsorships": True, "past_sponsors": ["McDonald's", "Nike", "Cash App"],
        "estimated_sponsorship_rate": "$100k-500k per deal",
        "notable_achievements": ["Most subscribed Twitch streamer ever", "Broke Twitch sub records multiple times", "Cultural phenomenon"],
        "tags": ["variety", "entertainment", "record-breaker", "gen-z", "viral"],
        "audience_age_range": "13-25", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "IShowSpeed", "real_name": "Darren Watkins Jr.", "url": "https://www.youtube.com/c/IShowSpeed",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/IShowSpeed",
        "bio": "High-energy YouTube streamer known for gaming content, IRL streams, and viral moments. Massive global reach.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 25000000, "avg_viewers": 200000, "peak_viewers": 3000000,
        "primary_game": "Variety", "games_played": ["FIFA", "Fortnite", "Minecraft", "Horror games"],
        "content_categories": ["Gaming", "IRL", "Entertainment"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@ishowspeedsui",
        "twitter_followers": 5000000,
        "has_sponsorships": True, "past_sponsors": ["Pepsi", "Nike"],
        "notable_achievements": ["25M+ YouTube subscribers", "Global IRL stream tours", "Broke YouTube live records"],
        "tags": ["youtube", "entertainment", "viral", "global-reach", "gen-z"],
        "audience_age_range": "10-22", "audience_top_countries": ["US", "UK", "BR", "IN", "PH"],
    },
]


def seed_streamers(db: Session) -> int:
    """Seed the database with known gaming streamers. Returns the number added."""
    added = 0
    for streamer_data in GAMING_STREAMERS:
        existing = db.query(Streamer).filter(Streamer.url == streamer_data["url"]).first()
        if not existing:
            streamer = Streamer(**streamer_data)
            db.add(streamer)
            added += 1
    db.commit()
    return added
