from sqlalchemy.orm import Session

from app.models.streamer import Streamer

GAMING_STREAMERS = [
    # ═══════════════════════════════════════════
    # MEGA TIER (1M+ followers)
    # ═══════════════════════════════════════════
    {
        "name": "Ninja", "real_name": "Tyler Blevins", "url": "https://www.twitch.tv/ninja",
        "platform": "twitch", "twitch_username": "ninja", "youtube_channel": "https://www.youtube.com/user/NinjasHyper",
        "bio": "Professional gamer, streamer, and content creator. Former Halo pro turned Fortnite legend. One of the most recognized faces in gaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 19000000, "subscriber_count": 50000, "avg_viewers": 30000, "peak_viewers": 635000,
        "primary_game": "Fortnite", "games_played": ["Fortnite", "Valorant", "League of Legends", "Apex Legends"],
        "content_categories": ["FPS", "Battle Royale", "Competitive"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Ninja", "social_instagram": "ninja", "social_youtube": "NinjasHyper",
        "twitter_followers": 7000000, "instagram_followers": 12000000,
        "contact_email": "ninja@teamninjapr.com", "business_email": "business@ninja.com",
        "agency": "Loaded", "agency_url": "https://www.loaded.gg",
        "has_sponsorships": True, "past_sponsors": ["Red Bull", "Adidas", "NZXT", "Uber Eats", "Samsung"],
        "estimated_sponsorship_rate": "$50k-500k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "has_merch_store": True, "merch_url": "https://shop.ninja.com",
        "notable_achievements": ["Most followed Twitch streamer (2018-2021)", "Played Fortnite with Drake", "Times 100 Most Influential 2019"],
        "recent_milestones": ["Returned to Twitch streaming", "Launched new merch line"],
        "tags": ["fortnite", "competitive", "mainstream", "brand-friendly"],
        "audience_age_range": "13-28", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "Shroud", "real_name": "Michael Grzesiek", "url": "https://www.twitch.tv/shroud",
        "platform": "twitch", "twitch_username": "shroud", "youtube_channel": "https://www.youtube.com/user/shraborern",
        "bio": "Former CS:GO professional player for Cloud9. Known for incredible aim and FPS gameplay. The human aimbot.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 10500000, "subscriber_count": 30000, "avg_viewers": 25000, "peak_viewers": 515000,
        "primary_game": "Valorant", "games_played": ["Valorant", "CS2", "Apex Legends", "Escape from Tarkov", "New World"],
        "content_categories": ["FPS", "Tactical Shooter", "Variety"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@shraborern", "social_instagram": "shroud",
        "twitter_followers": 2500000, "instagram_followers": 3000000,
        "contact_email": "shroud@loadedgg.com", "business_email": "business@shroud.gg",
        "agency": "Loaded", "agency_url": "https://www.loaded.gg",
        "has_sponsorships": True, "past_sponsors": ["Logitech G", "Madrinas Coffee", "Postmates", "HyperX"],
        "estimated_sponsorship_rate": "$30k-200k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Former C9 CS:GO pro", "Multiple major tournament wins", "Known as 'The Human Aimbot'"],
        "tags": ["fps", "competitive", "aim-god", "tactical-shooter"],
        "audience_age_range": "18-34", "audience_top_countries": ["US", "CA", "UK", "DE"],
    },
    {
        "name": "xQc", "real_name": "Felix Lengyel", "url": "https://www.twitch.tv/xqc",
        "platform": "twitch", "twitch_username": "xqc",
        "youtube_channel": "https://www.youtube.com/channel/UCmDTrq0LNgPodDOFZiSbsww",
        "bio": "Former Overwatch League pro turned variety streamer. Known for high-energy, chaotic streams and reacting to content.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 12500000, "subscriber_count": 60000, "avg_viewers": 65000, "peak_viewers": 350000,
        "primary_game": "Variety", "games_played": ["GTA V RP", "Minecraft", "Overwatch 2", "Fortnite", "Just Chatting"],
        "content_categories": ["Variety", "Just Chatting", "FPS", "RP"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@xQc", "social_instagram": "xqcow1",
        "twitter_followers": 2200000, "instagram_followers": 1500000,
        "has_sponsorships": True, "past_sponsors": ["Lenovo Legion", "GFuel", "Samsung"],
        "estimated_sponsorship_rate": "$50k-300k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "is_esports_player": True, "esports_team": "Luminosity Gaming (former)", "esports_role": "Tank (Overwatch)",
        "notable_achievements": ["Overwatch League MVP candidate", "Most watched Twitch streamer 2022", "Set concurrent viewer records"],
        "tags": ["variety", "react", "high-energy", "massive-reach"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "UK", "FR"],
    },
    {
        "name": "Pokimane", "real_name": "Imane Anys", "url": "https://www.twitch.tv/pokimane",
        "platform": "twitch", "twitch_username": "pokimane",
        "youtube_channel": "https://www.youtube.com/c/pokimane",
        "bio": "One of the most prominent female streamers. Co-founder of OfflineTV. Known for Valorant, League, and Just Chatting content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 9300000, "subscriber_count": 15000, "avg_viewers": 15000, "peak_viewers": 200000,
        "primary_game": "Valorant", "games_played": ["Valorant", "League of Legends", "Fortnite", "Among Us"],
        "content_categories": ["FPS", "Just Chatting", "Variety"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@pokaborern", "social_instagram": "pokimane",
        "twitter_followers": 4500000, "instagram_followers": 6000000,
        "agency": "United Talent Agency", "business_email": "pokimane@unitedtalent.com",
        "has_sponsorships": True, "past_sponsors": ["CashApp", "Verizon", "NZXT", "Postmates"],
        "estimated_sponsorship_rate": "$30k-150k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Co-founder of OfflineTV", "Most followed female Twitch streamer", "Launched Midnight snack brand"],
        "tags": ["variety", "female-creator", "brand-safe", "massive-reach", "OfflineTV"],
        "audience_age_range": "16-30", "audience_gender_split": {"male": 55, "female": 40, "other": 5},
        "audience_top_countries": ["US", "CA", "UK", "AU"],
    },
    {
        "name": "TimTheTatman", "real_name": "Timothy Betar", "url": "https://www.twitch.tv/timthetatman",
        "platform": "twitch", "twitch_username": "timthetatman",
        "youtube_channel": "https://www.youtube.com/user/timthetatman",
        "bio": "Variety streamer and content creator known for Warzone, Fortnite, and Overwatch content. Part of Complexity Gaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 7500000, "subscriber_count": 20000, "avg_viewers": 20000, "peak_viewers": 300000,
        "primary_game": "Call of Duty: Warzone", "games_played": ["Warzone", "Fortnite", "Overwatch 2", "WoW"],
        "content_categories": ["FPS", "Battle Royale", "Variety"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@timthetatman", "social_instagram": "timthetatman",
        "twitter_followers": 3500000, "instagram_followers": 2500000,
        "has_sponsorships": True, "past_sponsors": ["AT&T", "Monster Energy", "Chipotle", "Audio-Technica"],
        "notable_achievements": ["Complexity Gaming co-owner", "Won Fortnite Celebrity Pro-Am", "NFL Sunday Ticket streaming"],
        "tags": ["warzone", "brand-friendly", "family-friendly", "competitive"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "CA", "UK"],
    },

    # ═══════════════════════════════════════════
    # MACRO TIER (500K-1M followers)
    # ═══════════════════════════════════════════
    {
        "name": "Valkyrae", "real_name": "Rachell Hofstetter", "url": "https://www.youtube.com/c/Valkyrae",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/Valkyrae",
        "bio": "YouTube Gaming co-owner and content creator. Known for Valorant, Fortnite, and Among Us. Co-owner of 100 Thieves.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 4000000, "avg_viewers": 20000, "peak_viewers": 170000,
        "primary_game": "Valorant", "games_played": ["Valorant", "Among Us", "Fortnite", "GTA V RP"],
        "content_categories": ["FPS", "Social Deduction", "Variety"], "content_style": "entertainment",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Valkyrae", "social_instagram": "valkyrae",
        "twitter_followers": 2800000, "instagram_followers": 3800000,
        "has_sponsorships": True, "past_sponsors": ["YouTube Gaming", "100 Thieves"],
        "notable_achievements": ["YouTube Gaming co-owner", "100 Thieves co-owner", "Content Creator of the Year 2020"],
        "tags": ["youtube-gaming", "female-creator", "esports-adjacent", "100thieves"],
        "audience_age_range": "16-28", "audience_top_countries": ["US", "PH", "CA"],
    },
    {
        "name": "DrDisrespect", "real_name": "Herschel Beahm IV", "url": "https://www.youtube.com/c/DrDisrespect",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/DrDisrespect",
        "bio": "The Two-Time. Back-to-back 1993-1994 Blockbuster Video Game Champion. Known for his character, high production value streams, and FPS gameplay.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 4500000, "avg_viewers": 25000, "peak_viewers": 510000,
        "primary_game": "Call of Duty", "games_played": ["Warzone", "PUBG", "Apex Legends", "Fortnite", "Deadrop"],
        "content_categories": ["FPS", "Battle Royale", "Shooter"], "content_style": "entertainment",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@DrDisrespect", "social_instagram": "drdisrespect",
        "twitter_followers": 2200000, "instagram_followers": 1800000,
        "has_sponsorships": True, "past_sponsors": ["Turtle Beach", "Roccat", "ASUS ROG", "Mountain Dew Game Fuel"],
        "notable_achievements": ["Former Sledgehammer Games level designer", "Developing own game studio (Midnight Society)", "Iconic streaming persona"],
        "tags": ["fps", "entertainment", "high-production", "character-streamer"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "DE", "CA"],
    },
    {
        "name": "Lirik", "url": "https://www.twitch.tv/lirik",
        "platform": "twitch", "twitch_username": "lirik",
        "bio": "One of the OG variety streamers on Twitch. Known for discovering and popularizing new games. Pioneer of variety streaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 2900000, "avg_viewers": 15000, "peak_viewers": 100000,
        "primary_game": "Variety", "games_played": ["New releases", "Indie games", "RPGs", "Survival", "MMOs"],
        "content_categories": ["Variety", "Adventure", "RPG", "Survival"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@LIRIK",
        "twitter_followers": 1200000,
        "has_sponsorships": True, "past_sponsors": ["Corsair", "DoorDash"],
        "accepts_game_codes": True,
        "notable_achievements": ["Pioneer of variety streaming", "One of first Twitch partners", "Known for discovering indie gems"],
        "tags": ["variety", "indie-friendly", "game-discovery", "og-streamer"],
        "audience_age_range": "20-35", "audience_top_countries": ["US", "EU", "CA"],
    },
    {
        "name": "CohhCarnage", "real_name": "Ben Cassell", "url": "https://www.twitch.tv/cohhcarnage",
        "platform": "twitch", "twitch_username": "cohhcarnage",
        "youtube_channel": "https://www.youtube.com/user/coaborner",
        "bio": "Family-friendly variety streamer specializing in RPGs and new game releases. Known for detailed, thorough game playthroughs.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1800000, "avg_viewers": 10000, "peak_viewers": 80000,
        "primary_game": "Variety RPG", "games_played": ["Cyberpunk 2077", "Baldur's Gate 3", "Elden Ring", "Starfield"],
        "content_categories": ["RPG", "Action-Adventure", "Variety"], "content_style": "educational",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@CohhCarnage",
        "twitter_followers": 500000,
        "contact_email": "cohh@cohhcarnage.com",
        "has_sponsorships": True, "past_sponsors": ["Corsair", "State Farm"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Known for ultra-thorough playthroughs", "One of most brand-safe streamers", "Partner with many AAA studios for launch streams"],
        "tags": ["rpg", "brand-safe", "family-friendly", "thorough", "launch-day-streamer"],
        "audience_age_range": "22-40", "audience_top_countries": ["US", "UK", "DE", "NL"],
    },
    {
        "name": "Asmongold", "real_name": "Zack Hoyt", "url": "https://www.twitch.tv/asmongold",
        "platform": "twitch", "twitch_username": "asmongold",
        "youtube_channel": "https://www.youtube.com/c/Asmongold",
        "bio": "MMO and variety streamer. Known for World of Warcraft and FFXIV content. Runs the secondary channel Zackrawrr for react content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3800000, "subscriber_count": 25000, "avg_viewers": 45000, "peak_viewers": 400000,
        "primary_game": "World of Warcraft", "games_played": ["WoW", "FFXIV", "Diablo IV", "Lost Ark", "Elden Ring"],
        "content_categories": ["MMO", "RPG", "React", "Variety"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Asmongold",
        "twitter_followers": 1500000,
        "has_sponsorships": True, "past_sponsors": ["SteelSeries", "Starforge Systems"],
        "accepts_game_codes": True,
        "notable_achievements": ["Co-founded OTK Network", "Largest MMO streamer", "Created multiple viral gaming takes"],
        "tags": ["mmo", "wow", "react", "gaming-commentary", "OTK"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "DE", "CA"],
    },

    # ═══════════════════════════════════════════
    # MID TIER (100K-500K followers)
    # ═══════════════════════════════════════════
    {
        "name": "AngryJoeShow", "real_name": "Joe Vargas", "url": "https://www.youtube.com/user/AngryJoeShow",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/user/AngryJoeShow",
        "bio": "Game reviewer and content creator known for in-depth, passionate game reviews and the Angry Joe Review series.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3700000, "avg_viewers": 50000, "peak_viewers": 200000,
        "primary_game": "Reviews", "games_played": ["AAA releases", "RPGs", "Action games"],
        "content_categories": ["Reviews", "Commentary", "News"], "content_style": "educational",
        "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@AngryJoeShow",
        "twitter_followers": 900000,
        "accepts_game_codes": True,
        "notable_achievements": ["Over 3.7M YouTube subscribers", "Known for honest brutally honest reviews", "Angry Joe Review series"],
        "tags": ["reviews", "commentary", "honest-reviews", "youtube"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "Maximilian Dood", "real_name": "Maximilian Christiansen", "url": "https://www.twitch.tv/maximilian_dood",
        "platform": "twitch", "twitch_username": "maximilian_dood",
        "youtube_channel": "https://www.youtube.com/user/Miles923",
        "bio": "Fighting game community legend. Known for FGC content, game analysis, and hosting major community events.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 800000, "avg_viewers": 8000, "peak_viewers": 50000,
        "primary_game": "Street Fighter 6", "games_played": ["Street Fighter 6", "Tekken 8", "Mortal Kombat", "Guilty Gear"],
        "content_categories": ["Fighting Games", "FGC", "Variety"], "content_style": "educational",
        "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@maximaborern",
        "twitter_followers": 400000,
        "accepts_game_codes": True,
        "notable_achievements": ["FGC community pillar", "Over 1M YouTube subscribers", "Week of series creator"],
        "tags": ["fgc", "fighting-games", "community-leader", "educational"],
        "audience_age_range": "20-38", "audience_top_countries": ["US", "JP", "MX", "BR"],
    },
    {
        "name": "Northernlion", "real_name": "Ryan Letourneau", "url": "https://www.twitch.tv/northernlion",
        "platform": "twitch", "twitch_username": "northernlion",
        "youtube_channel": "https://www.youtube.com/user/Northernlion",
        "bio": "The egg. Variety streamer and YouTube creator known for roguelike content, witty commentary, and long-running Isaac series.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 1200000, "avg_viewers": 8000, "peak_viewers": 30000,
        "primary_game": "The Binding of Isaac", "games_played": ["Isaac", "Hades", "Balatro", "Indie roguelikes"],
        "content_categories": ["Roguelike", "Indie", "Variety"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@NorthernlionLP",
        "twitter_followers": 500000,
        "accepts_game_codes": True,
        "notable_achievements": ["4000+ episode Isaac series", "Known for discovering indie gems", "Influential in roguelike genre"],
        "tags": ["roguelike", "indie", "witty", "long-form", "game-discovery"],
        "audience_age_range": "20-35", "audience_top_countries": ["US", "CA", "UK", "AU"],
    },
    {
        "name": "Sodapoppin", "real_name": "Chance Morris", "url": "https://www.twitch.tv/sodapoppin",
        "platform": "twitch", "twitch_username": "sodapoppin",
        "bio": "One of the original Twitch streamers. Known for WoW content and variety streaming. OG streamer who helped define the platform.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 8500000, "avg_viewers": 15000, "peak_viewers": 100000,
        "primary_game": "World of Warcraft", "games_played": ["WoW", "GTA V RP", "Variety", "Party games"],
        "content_categories": ["MMO", "Variety", "Just Chatting"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Sodapoppintv",
        "twitter_followers": 1400000,
        "notable_achievements": ["OG Twitch streamer", "WoW community legend", "NPC Gaming co-founder"],
        "tags": ["mmo", "wow", "og-streamer", "variety"],
        "audience_age_range": "18-32", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "Summit1g", "real_name": "Jaryd Lazar", "url": "https://www.twitch.tv/summit1g",
        "platform": "twitch", "twitch_username": "summit1g",
        "bio": "Former CS:GO professional turned variety streamer. Known for chill vibes, FPS games, and sea of thieves adventures.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 6200000, "avg_viewers": 12000, "peak_viewers": 300000,
        "primary_game": "Variety", "games_played": ["CS2", "Sea of Thieves", "GTA V RP", "Escape from Tarkov"],
        "content_categories": ["FPS", "Adventure", "Variety"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@summit1g",
        "twitter_followers": 1500000,
        "is_esports_player": True, "esports_role": "Former CS:GO pro",
        "notable_achievements": ["One of longest-running top Twitch streamers", "CS:GO pro background", "Sea of Thieves legend"],
        "tags": ["fps", "chill", "variety", "og-streamer"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "CA", "UK", "BR"],
    },

    # ═══════════════════════════════════════════
    # INTERNATIONAL STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Rubius", "real_name": "Ruben Doblas", "url": "https://www.twitch.tv/rubius",
        "platform": "twitch", "twitch_username": "rubius",
        "bio": "Spanish-speaking mega streamer. One of the biggest content creators in the Spanish-speaking world.",
        "language": "es", "region": "ES", "country": "Spain",
        "follower_count": 14500000, "avg_viewers": 50000, "peak_viewers": 1200000,
        "primary_game": "Variety", "games_played": ["Minecraft", "Fortnite", "GTA V", "Just Chatting"],
        "content_categories": ["Variety", "Entertainment", "Gaming"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Rubiu5", "social_instagram": "elrubius",
        "twitter_followers": 20000000, "instagram_followers": 16000000,
        "notable_achievements": ["Most followed Spanish Twitch streamer", "40M+ YouTube subscribers"],
        "tags": ["spanish", "mega-creator", "entertainment", "youth"],
        "audience_age_range": "13-25", "audience_top_countries": ["ES", "MX", "AR", "CO"],
    },
    {
        "name": "Gaules", "real_name": "Alexandre Borba", "url": "https://www.twitch.tv/gaules",
        "platform": "twitch", "twitch_username": "gaules",
        "bio": "Brazilian CS:GO/CS2 caster and streamer. Biggest Brazilian gaming streamer. Former professional CS 1.6 player.",
        "language": "pt", "region": "BR", "country": "Brazil",
        "follower_count": 6000000, "avg_viewers": 40000, "peak_viewers": 600000,
        "primary_game": "CS2", "games_played": ["CS2", "Valorant"],
        "content_categories": ["FPS", "Esports", "Casting"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Gaaborern",
        "twitter_followers": 1800000,
        "is_esports_player": True, "esports_role": "Former CS 1.6 pro / Caster",
        "notable_achievements": ["Biggest Brazilian Twitch streamer", "CS esports legend", "Set Brazilian concurrent viewer records"],
        "tags": ["cs2", "brazil", "esports", "casting"],
        "audience_age_range": "16-30", "audience_top_countries": ["BR", "PT"],
    },
    {
        "name": "Ibai", "real_name": "Ibai Llanos", "url": "https://www.twitch.tv/ibai",
        "platform": "twitch", "twitch_username": "ibai",
        "bio": "Spanish content creator and esports caster. Known for La Velada boxing events and massive entertainment streams.",
        "language": "es", "region": "ES", "country": "Spain",
        "follower_count": 15000000, "avg_viewers": 80000, "peak_viewers": 3400000,
        "primary_game": "Variety", "games_played": ["League of Legends", "Fortnite", "Just Chatting"],
        "content_categories": ["Entertainment", "Esports", "Events"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@IbaiLlanos", "social_instagram": "ibaillanos",
        "twitter_followers": 10000000, "instagram_followers": 10000000,
        "agency": "KOI (co-founder)",
        "has_sponsorships": True, "past_sponsors": ["Pepsi", "Adidas", "Prime"],
        "notable_achievements": ["La Velada boxing events", "Co-owner of KOI esports", "Record-breaking Twitch events", "Most watched Spanish-language stream ever"],
        "tags": ["spanish", "events", "entertainment", "esports", "boxing"],
        "audience_age_range": "14-30", "audience_top_countries": ["ES", "MX", "AR", "CO"],
    },
    {
        "name": "Fps_shaka", "real_name": "Shaka", "url": "https://www.twitch.tv/fps_shaka",
        "platform": "twitch", "twitch_username": "fps_shaka",
        "bio": "Top Japanese FPS streamer. Known for incredible Apex Legends and Valorant gameplay. Major figure in Japanese streaming.",
        "language": "ja", "region": "JP", "country": "Japan",
        "follower_count": 1200000, "avg_viewers": 15000, "peak_viewers": 80000,
        "primary_game": "Apex Legends", "games_played": ["Apex Legends", "Valorant", "PUBG"],
        "content_categories": ["FPS", "Battle Royale", "Competitive"], "content_style": "competitive",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@fps_shaka",
        "twitter_followers": 800000,
        "notable_achievements": ["Top Japanese FPS streamer", "Apex predator rank", "Japan esports community leader"],
        "tags": ["fps", "japan", "apex", "competitive"],
        "audience_age_range": "16-30", "audience_top_countries": ["JP"],
    },
    {
        "name": "Elraenn", "url": "https://www.twitch.tv/elraenn",
        "platform": "twitch", "twitch_username": "elraenn",
        "bio": "Top Turkish variety streamer. One of the most followed streamers globally. Known for gaming content and massive community events.",
        "language": "tr", "region": "TR", "country": "Turkey",
        "follower_count": 5500000, "avg_viewers": 50000, "peak_viewers": 500000,
        "primary_game": "Variety", "games_played": ["Minecraft", "GTA V", "Valorant", "League of Legends"],
        "content_categories": ["Variety", "Gaming", "Entertainment"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Elraenn",
        "twitter_followers": 3000000,
        "notable_achievements": ["Largest Turkish Twitch streamer", "Multiple Twitch records in Turkey"],
        "tags": ["turkish", "variety", "massive-community", "events"],
        "audience_age_range": "14-28", "audience_top_countries": ["TR", "DE", "AZ"],
    },
    {
        "name": "Sardoche", "real_name": "Andrzej Dubiez", "url": "https://www.twitch.tv/sardoche",
        "platform": "twitch", "twitch_username": "sardoche",
        "bio": "Top French League of Legends streamer. Known for competitive LoL gameplay and high challenger rank content.",
        "language": "fr", "region": "FR", "country": "France",
        "follower_count": 1500000, "avg_viewers": 8000, "peak_viewers": 60000,
        "primary_game": "League of Legends", "games_played": ["League of Legends", "TFT", "Valorant"],
        "content_categories": ["MOBA", "Competitive", "Strategy"], "content_style": "competitive",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Sardoche",
        "twitter_followers": 700000,
        "notable_achievements": ["Top French LoL streamer", "Challenger rank player"],
        "tags": ["league-of-legends", "french", "competitive", "moba"],
        "audience_age_range": "16-28", "audience_top_countries": ["FR", "BE", "CH", "MA"],
    },

    # ═══════════════════════════════════════════
    # SPECIALIZED / NICHE STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "DisguisedToast", "real_name": "Jeremy Wang", "url": "https://www.twitch.tv/disguisedtoast",
        "platform": "twitch", "twitch_username": "disguisedtoast",
        "bio": "Former Hearthstone pro turned variety streamer. OfflineTV member. Known for big-brain plays and strategic gaming content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3500000, "avg_viewers": 12000, "peak_viewers": 100000,
        "primary_game": "Variety", "games_played": ["TFT", "Among Us", "League of Legends", "Valorant"],
        "content_categories": ["Strategy", "Social Deduction", "Variety"], "content_style": "educational",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@DisguisedToast",
        "twitter_followers": 1200000,
        "notable_achievements": ["OfflineTV member", "Among Us streamer pioneer", "Hearthstone legend"],
        "tags": ["strategy", "offlinetv", "big-brain", "variety"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "PH", "SG"],
    },
    {
        "name": "Lethal Frag", "url": "https://www.twitch.tv/lethalfrag",
        "platform": "twitch", "twitch_username": "lethalfrag",
        "bio": "Indie game specialist and community builder. Known for supporting small developers and showcasing hidden gem indie games.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 120000, "avg_viewers": 500, "peak_viewers": 5000,
        "primary_game": "Indie Games", "games_played": ["Indie games", "Roguelikes", "Platformers"],
        "content_categories": ["Indie", "Roguelike", "Platformer"], "content_style": "educational",
        "is_variety_streamer": True, "is_partnered": True, "tier": "micro", "priority": 4,
        "social_twitter": "@LethalFrag",
        "accepts_game_codes": True,
        "notable_achievements": ["Indie game champion", "Known for discovering hidden gems", "Twitch community builder"],
        "tags": ["indie", "game-discovery", "community", "small-dev-friendly"],
        "audience_age_range": "22-40", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "SkillUp", "real_name": "Ralph Panebianco", "url": "https://www.youtube.com/c/SkillUp",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/SkillUp",
        "bio": "In-depth game reviewer and analyst. Known for thorough, thoughtful reviews and the 'This Week in Gaming' series.",
        "language": "en", "region": "AU", "country": "Australia",
        "follower_count": 1800000, "avg_viewers": 300000,
        "primary_game": "Reviews", "games_played": ["AAA releases", "RPGs", "Shooters", "Indie"],
        "content_categories": ["Reviews", "Analysis", "News"], "content_style": "educational",
        "tier": "mid", "priority": 3,
        "social_twitter": "@SkillUpYT",
        "twitter_followers": 200000,
        "accepts_game_codes": True,
        "notable_achievements": ["This Week in Gaming series", "Known for balanced in-depth reviews"],
        "tags": ["reviews", "analysis", "in-depth", "youtube", "trusted-voice"],
        "audience_age_range": "20-40", "audience_top_countries": ["US", "AU", "UK", "CA"],
    },
    {
        "name": "Girlfriend Reviews", "url": "https://www.youtube.com/c/GirlfriendReviews",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/GirlfriendReviews",
        "bio": "Unique review channel reviewing games from the perspective of watching someone else play. Humorous, heartfelt game commentary.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1600000, "avg_viewers": 500000,
        "primary_game": "Reviews", "games_played": ["AAA releases", "Indie", "RPGs", "Horror"],
        "content_categories": ["Reviews", "Comedy", "Analysis"], "content_style": "entertainment",
        "tier": "mid", "priority": 3,
        "social_twitter": "@itsgfreviews",
        "accepts_game_codes": True,
        "notable_achievements": ["Unique review format", "1.6M YouTube subscribers", "Game Awards nominee"],
        "tags": ["reviews", "comedy", "unique-format", "youtube", "couple-content"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "Amouranth", "real_name": "Kaitlyn Siragusa", "url": "https://www.twitch.tv/amouranth",
        "platform": "twitch", "twitch_username": "amouranth",
        "bio": "Top female Twitch streamer and entrepreneur. Business-focused creator with investments in multiple industries.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 6300000, "avg_viewers": 8000, "peak_viewers": 60000,
        "primary_game": "Variety", "games_played": ["Just Chatting", "ASMR", "Fortnite", "Overwatch"],
        "content_categories": ["Just Chatting", "Variety", "IRL"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 3,
        "social_twitter": "@Amouranth", "social_instagram": "amouranth",
        "twitter_followers": 2000000, "instagram_followers": 6500000,
        "has_sponsorships": True,
        "notable_achievements": ["Most-watched female streamer", "Entrepreneur and investor", "Business empire beyond streaming"],
        "tags": ["variety", "female-creator", "entrepreneur", "massive-reach"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "DE", "FR"],
    },
    {
        "name": "Kaicenat", "real_name": "Kai Cenat", "url": "https://www.twitch.tv/kaicenat",
        "platform": "twitch", "twitch_username": "kaicenat",
        "bio": "Record-breaking Twitch streamer known for marathon subathon streams and viral moments. Brought mainstream attention to Twitch.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 14000000, "avg_viewers": 100000, "peak_viewers": 700000,
        "primary_game": "Variety", "games_played": ["GTA V", "Fortnite", "Just Chatting", "Elden Ring"],
        "content_categories": ["Variety", "Entertainment", "Just Chatting"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@KaiCenat", "social_instagram": "kaicenat",
        "twitter_followers": 3000000, "instagram_followers": 9000000,
        "has_sponsorships": True, "past_sponsors": ["McDonald's", "Nike", "Cash App"],
        "estimated_sponsorship_rate": "$100k-500k per deal",
        "notable_achievements": ["Most subscribed Twitch streamer ever", "Broke Twitch sub records multiple times", "Cultural phenomenon"],
        "tags": ["variety", "entertainment", "record-breaker", "gen-z", "viral"],
        "audience_age_range": "13-25", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "IShowSpeed", "real_name": "Darren Watkins Jr.", "url": "https://www.youtube.com/c/IShowSpeed",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/c/IShowSpeed",
        "bio": "High-energy YouTube streamer known for gaming content, IRL streams, and viral moments. Massive global reach.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 25000000, "avg_viewers": 200000, "peak_viewers": 3000000,
        "primary_game": "Variety", "games_played": ["FIFA", "Fortnite", "Minecraft", "Horror games"],
        "content_categories": ["Gaming", "IRL", "Entertainment"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@ishowspeedsui",
        "twitter_followers": 5000000,
        "has_sponsorships": True, "past_sponsors": ["Pepsi", "Nike"],
        "notable_achievements": ["25M+ YouTube subscribers", "Global IRL stream tours", "Broke YouTube live records"],
        "tags": ["youtube", "entertainment", "viral", "global-reach", "gen-z"],
        "audience_age_range": "10-22", "audience_top_countries": ["US", "UK", "BR", "IN", "PH"],
    },

    # ═══════════════════════════════════════════
    # ADDITIONAL TWITCH STREAMERS
    # ═══════════════════════════════════════════
    {
        "name": "Auronplay", "real_name": "Raúl Álvarez Genes", "url": "https://www.twitch.tv/auronplay",
        "platform": "twitch", "twitch_username": "auronplay",
        "youtube_channel": "https://www.youtube.com/c/auronplay",
        "bio": "One of the biggest Spanish-speaking content creators. Known for interactive community events and variety gaming content.",
        "language": "es", "region": "ES", "country": "Spain",
        "follower_count": 17000000, "avg_viewers": 60000, "peak_viewers": 800000,
        "primary_game": "Variety", "games_played": ["Minecraft", "GTA V", "Among Us", "Just Chatting"],
        "content_categories": ["Variety", "Entertainment", "Community Events"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@auronplay", "social_instagram": "auronplay",
        "twitter_followers": 14900000, "instagram_followers": 8000000,
        "has_sponsorships": True, "past_sponsors": ["Vodafone", "Prime Gaming", "Domino's"],
        "estimated_sponsorship_rate": "$50k-300k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["17M+ Twitch followers", "One of top 3 most-followed Twitch channels globally", "La Velada participant"],
        "tags": ["spanish", "variety", "massive-reach", "community-events"],
        "audience_age_range": "14-28", "audience_top_countries": ["ES", "MX", "AR", "CO", "CL"],
    },
    {
        "name": "Tyler1", "real_name": "Tyler Steinkamp", "url": "https://www.twitch.tv/loltyler1",
        "platform": "twitch", "twitch_username": "loltyler1",
        "youtube_channel": "https://www.youtube.com/c/loltyler1",
        "bio": "Reformed League of Legends streamer. Known for high Challenger rank, intense gameplay, and passionate community.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 5800000, "avg_viewers": 45000, "peak_viewers": 300000,
        "primary_game": "League of Legends", "games_played": ["League of Legends", "Teamfight Tactics", "Valorant"],
        "content_categories": ["MOBA", "Competitive", "Just Chatting"], "content_style": "competitive",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@loltyler1", "social_instagram": "tyler1",
        "twitter_followers": 1200000, "instagram_followers": 800000,
        "has_sponsorships": True, "past_sponsors": ["Kinder Bueno", "GFuel", "Logitech G"],
        "estimated_sponsorship_rate": "$20k-100k per deal",
        "accepts_game_codes": False, "accepts_sponsored_streams": True,
        "notable_achievements": ["Highest public elo NA multiple seasons", "Alpha Male of Twitch persona", "League icon"],
        "tags": ["league-of-legends", "competitive", "moba", "high-energy"],
        "audience_age_range": "16-28", "audience_top_countries": ["US", "CA", "UK", "KR"],
    },
    {
        "name": "Ludwig", "real_name": "Ludwig Ahgren", "url": "https://www.youtube.com/@ludwig",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@ludwig",
        "twitch_username": "ludwigahgren",
        "bio": "Content creator and event organizer. Known for 31-day subathon world record and major esports events like Mogul Money and Chess events.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 4500000, "avg_viewers": 30000, "peak_viewers": 280000,
        "primary_game": "Variety", "games_played": ["Chess", "Smash Bros", "Variety", "Trackmania", "Poker"],
        "content_categories": ["Variety", "Events", "Chess", "Competitive"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@LudwigAhgren", "social_instagram": "ludwigahgren",
        "twitter_followers": 800000, "instagram_followers": 600000,
        "agency": "Night Media",
        "has_sponsorships": True, "past_sponsors": ["Backbone", "Chime", "DoorDash", "BetterHelp"],
        "estimated_sponsorship_rate": "$30k-150k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["31-day subathon record (283,066 subs)", "Mogul Money event creator", "Chess tournament organizer"],
        "tags": ["variety", "events", "chess", "youtube-exclusive", "creative"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "UK", "AU"],
    },
    {
        "name": "Sykkuno", "real_name": "Thomas Sykkuno", "url": "https://www.twitch.tv/sykkuno",
        "platform": "twitch", "twitch_username": "sykkuno",
        "youtube_channel": "https://www.youtube.com/c/Sykkuno",
        "bio": "OfflineTV-adjacent variety streamer known for Among Us content and wholesome, engaging personality.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3900000, "avg_viewers": 15000, "peak_viewers": 120000,
        "primary_game": "Variety", "games_played": ["Among Us", "Valorant", "GTA V RP", "League of Legends"],
        "content_categories": ["Social Deduction", "Variety", "FPS"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@Sykkuno",
        "twitter_followers": 900000,
        "agency": "United Talent Agency", "business_email": "sykkuno@unitedtalent.com",
        "has_sponsorships": True, "past_sponsors": ["Crunchyroll", "NordVPN"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["OfflineTV adjacent creator", "Among Us community pivotal figure"],
        "tags": ["variety", "wholesome", "among-us", "social-deduction"],
        "audience_age_range": "14-28", "audience_top_countries": ["US", "CA", "PH", "AU"],
    },
    {
        "name": "HasanAbi", "real_name": "Hasan Piker", "url": "https://www.twitch.tv/hasanabi",
        "platform": "twitch", "twitch_username": "hasanabi",
        "bio": "Political commentator and variety gamer. One of the most watched political streamers. Known for gaming, reaction content, and news commentary.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3200000, "avg_viewers": 25000, "peak_viewers": 200000,
        "primary_game": "Variety", "games_played": ["GTA V RP", "Valorant", "Apex Legends", "Just Chatting"],
        "content_categories": ["Variety", "Just Chatting", "Political Commentary"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@hasanthehun", "social_instagram": "hasanthehun",
        "twitter_followers": 1600000, "instagram_followers": 500000,
        "has_sponsorships": True, "past_sponsors": ["Night Media", "Cuts Clothing"],
        "estimated_sponsorship_rate": "$20k-100k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["Broke Twitch political streaming records", "Known for long format streams", "Huffington Post alumnus"],
        "tags": ["political", "variety", "commentary", "long-format"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "CA", "UK"],
    },
    {
        "name": "Nickmercs", "real_name": "Nick Kolcheff", "url": "https://www.twitch.tv/nickmercs",
        "platform": "twitch", "twitch_username": "nickmercs",
        "youtube_channel": "https://www.youtube.com/c/NICKMERCS",
        "bio": "FPS gaming specialist and Warzone champion. Part of FaZe Clan. Known for hyped-up competitive gameplay and massive Warzone streams.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 7000000, "avg_viewers": 30000, "peak_viewers": 250000,
        "primary_game": "Call of Duty: Warzone", "games_played": ["Warzone", "Apex Legends", "Fortnite", "Valorant"],
        "content_categories": ["FPS", "Battle Royale", "Competitive"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@NICKMERCS", "social_instagram": "nickmercs",
        "twitter_followers": 2500000, "instagram_followers": 2000000,
        "agency": "Paradigm Sports Management",
        "has_sponsorships": True, "past_sponsors": ["Scuf Gaming", "Prime Hydration", "Mountain Dew"],
        "estimated_sponsorship_rate": "$40k-200k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "is_esports_player": True, "esports_team": "FaZe Clan",
        "notable_achievements": ["FaZe Clan co-owner", "MFAM community icon", "Warzone world records"],
        "tags": ["fps", "warzone", "faze-clan", "competitive", "high-energy"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "UK"],
    },
    {
        "name": "CouRageJD", "real_name": "Jack Dunlop", "url": "https://www.twitch.tv/couragejd",
        "platform": "twitch", "twitch_username": "couragejd",
        "youtube_channel": "https://www.youtube.com/c/CouRageJD",
        "bio": "Call of Duty streamer and esports commentator. 100 Thieves co-owner. Known for competitive FPS content and high-energy personality.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 3000000, "avg_viewers": 12000, "peak_viewers": 100000,
        "primary_game": "Call of Duty", "games_played": ["Call of Duty", "Warzone", "Fortnite", "Valorant"],
        "content_categories": ["FPS", "Battle Royale", "Esports"], "content_style": "competitive",
        "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@CouRageJD", "social_instagram": "couragejd",
        "twitter_followers": 790000, "instagram_followers": 600000,
        "has_sponsorships": True, "past_sponsors": ["Scuf Gaming", "State Farm"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "is_esports_player": True, "esports_team": "100 Thieves (co-owner)",
        "notable_achievements": ["100 Thieves co-owner", "Former Activision esports commentator", "CWL commentator"],
        "tags": ["fps", "call-of-duty", "100thieves", "commentator", "competitive"],
        "audience_age_range": "16-30", "audience_top_countries": ["US", "CA", "UK"],
    },
    {
        "name": "Mizkif", "real_name": "Matthew Rinaudo", "url": "https://www.twitch.tv/mizkif",
        "platform": "twitch", "twitch_username": "mizkif",
        "bio": "Variety streamer and OTK Network co-founder. Known for community events, reality TV-style streams, and educational gaming content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 2100000, "avg_viewers": 20000, "peak_viewers": 120000,
        "primary_game": "Variety", "games_played": ["Mario Kart", "Just Chatting", "Various games", "Learning games"],
        "content_categories": ["Variety", "Just Chatting", "Community Events"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@REALMizkif", "social_instagram": "mizkif",
        "twitter_followers": 700000, "instagram_followers": 400000,
        "has_sponsorships": True, "past_sponsors": ["Starforge Systems", "GFuel"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["OTK Network co-founder", "Streamer Awards creator", "School me series"],
        "tags": ["variety", "community-events", "otk", "entertainment"],
        "audience_age_range": "18-30", "audience_top_countries": ["US", "CA", "UK"],
    },
    {
        "name": "LilyPichu", "real_name": "Lily Ki", "url": "https://www.twitch.tv/lilypichu",
        "platform": "twitch", "twitch_username": "lilypichu",
        "youtube_channel": "https://www.youtube.com/c/LilyPichu",
        "bio": "OfflineTV member and multi-talented creator. Known for variety gaming, music production, and voice acting in addition to streaming.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 2600000, "avg_viewers": 10000, "peak_viewers": 60000,
        "primary_game": "Variety", "games_played": ["Valorant", "League of Legends", "Minecraft", "Piano lessons"],
        "content_categories": ["Variety", "Music", "Just Chatting", "Creative"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "macro", "priority": 2,
        "social_twitter": "@LilyPichu", "social_instagram": "lilypichu",
        "twitter_followers": 1000000, "instagram_followers": 900000,
        "has_sponsorships": True, "past_sponsors": ["Crunchyroll", "Twitch"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["OfflineTV founding member", "Voice actress (League of Legends)", "Music artist with original songs"],
        "tags": ["variety", "music", "offlinetv", "wholesome", "creative"],
        "audience_age_range": "14-28", "audience_top_countries": ["US", "CA", "PH", "AU"],
    },
    {
        "name": "Tfue", "real_name": "Turner Tenney", "url": "https://www.twitch.tv/tfue",
        "platform": "twitch", "twitch_username": "tfue",
        "youtube_channel": "https://www.youtube.com/c/Tfue",
        "bio": "One of the most skilled competitive Fortnite players. Known for incredible building mechanics and FPS accuracy. Former FaZe Clan member.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 11000000, "avg_viewers": 20000, "peak_viewers": 400000,
        "primary_game": "Fortnite", "games_played": ["Fortnite", "Warzone", "Valorant", "CS2"],
        "content_categories": ["FPS", "Battle Royale", "Competitive"], "content_style": "competitive",
        "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@TTfue", "social_instagram": "ttfue",
        "twitter_followers": 2000000, "instagram_followers": 3000000,
        "has_sponsorships": True, "past_sponsors": ["Logitech G", "Various gaming brands"],
        "estimated_sponsorship_rate": "$30k-150k per deal",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "is_esports_player": True, "esports_role": "Former FaZe Clan competitive player",
        "notable_achievements": ["Top Fortnite competitive player", "First place multiple FNCS events", "FaZe Clan lawsuit victory"],
        "tags": ["fortnite", "competitive", "fps", "building", "mechanical-skill"],
        "audience_age_range": "14-24", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "Juansguarnizo", "real_name": "Juan Sebastián Guarnizo", "url": "https://www.twitch.tv/juansguarnizo",
        "platform": "twitch", "twitch_username": "juansguarnizo",
        "bio": "Colombian variety streamer and one of the largest Spanish-speaking Twitch channels. Known for community collaborations and La Velada events.",
        "language": "es", "region": "CO", "country": "Colombia",
        "follower_count": 11600000, "avg_viewers": 50000, "peak_viewers": 600000,
        "primary_game": "Variety", "games_played": ["Minecraft", "GTA V", "Just Chatting", "Among Us"],
        "content_categories": ["Variety", "Entertainment", "Community Events"], "content_style": "entertainment",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mega", "priority": 1,
        "social_twitter": "@juansguarnizo", "social_instagram": "juansguarnizo",
        "twitter_followers": 5000000, "instagram_followers": 6000000,
        "has_sponsorships": True, "past_sponsors": ["Prime Gaming", "Mastercard"],
        "notable_achievements": ["Top 5 most-followed Twitch channels globally", "La Velada boxing participant", "Record Colombian Twitch stream"],
        "tags": ["spanish", "colombia", "variety", "mega-creator", "events"],
        "audience_age_range": "14-30", "audience_top_countries": ["CO", "MX", "ES", "AR", "VE"],
    },
    {
        "name": "Fuslie", "real_name": "Leslie Fu", "url": "https://www.twitch.tv/fuslie",
        "platform": "twitch", "twitch_username": "fuslie",
        "youtube_channel": "https://www.youtube.com/c/fuslie",
        "bio": "Variety streamer and 100 Thieves content creator. OfflineTV-adjacent. Known for Among Us, GTA RP, and variety content.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1200000, "avg_viewers": 5000, "peak_viewers": 40000,
        "primary_game": "Variety", "games_played": ["Among Us", "GTA V RP", "Valorant", "League of Legends"],
        "content_categories": ["Social Deduction", "Variety", "Just Chatting"], "content_style": "casual",
        "is_variety_streamer": True, "is_partnered": True, "tier": "mid", "priority": 3,
        "social_twitter": "@fuslie", "social_instagram": "fuslie",
        "twitter_followers": 350000, "instagram_followers": 400000,
        "agency": "United Talent Agency", "business_email": "fuslie@unitedtalent.com",
        "has_sponsorships": True, "past_sponsors": ["Crunchyroll"],
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["100 Thieves content creator", "OfflineTV adjacent", "Among Us community figure"],
        "tags": ["variety", "wholesome", "offlinetv-adjacent", "100thieves"],
        "audience_age_range": "16-28", "audience_top_countries": ["US", "CA", "PH"],
    },

    # ═══════════════════════════════════════════
    # YOUTUBE GAMING CHANNELS
    # ═══════════════════════════════════════════
    {
        "name": "PewDiePie", "real_name": "Felix Kjellberg", "url": "https://www.youtube.com/@PewDiePie",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@PewDiePie",
        "bio": "The most-subscribed individual YouTuber. Gaming icon who helped define YouTube culture. Known for variety gaming, commentary, and anime content.",
        "language": "en", "region": "SE", "country": "Sweden",
        "follower_count": 110000000, "avg_viewers": 3000000, "total_views": 29000000000,
        "primary_game": "Variety", "games_played": ["Minecraft", "Horror games", "Indie games", "Variety"],
        "content_categories": ["Gaming", "Commentary", "Variety", "Anime"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@pewdiepie", "social_instagram": "pewdiepie",
        "twitter_followers": 22000000, "instagram_followers": 23000000,
        "has_sponsorships": True, "past_sponsors": ["G Fuel", "Honey", "Skillshare"],
        "estimated_sponsorship_rate": "$300k-1M per video",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "has_merch_store": True,
        "notable_achievements": ["Most subscribed individual YouTuber (2013-2022)", "110M+ subscribers", "YouTube pioneer"],
        "tags": ["youtube", "mega-creator", "gaming-pioneer", "global-icon"],
        "audience_age_range": "14-30", "audience_top_countries": ["US", "UK", "IN", "BR", "DE"],
    },
    {
        "name": "Markiplier", "real_name": "Mark Fischbach", "url": "https://www.youtube.com/@markiplier",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@markiplier",
        "bio": "YouTube gaming icon known for horror game playthroughs, charity work, and passionate community. One of YouTube's most charitable creators.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 38000000, "avg_viewers": 2000000, "total_views": 19000000000,
        "primary_game": "Horror Games", "games_played": ["Five Nights at Freddy's", "Resident Evil", "Indie horror", "Among Us"],
        "content_categories": ["Horror", "Indie Games", "Variety", "Comedy"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@markiplier", "social_instagram": "markipliergram",
        "twitter_followers": 7000000, "instagram_followers": 8000000,
        "has_sponsorships": True, "past_sponsors": ["G Fuel", "Check", "Audible"],
        "estimated_sponsorship_rate": "$200k-800k per video",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "has_merch_store": True,
        "notable_achievements": ["Raised $3M+ for charity", "FNAF movie connection", "One of YouTube's biggest charity streamers"],
        "tags": ["youtube", "horror", "charity", "fnaf", "mega-creator"],
        "audience_age_range": "14-32", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "DanTDM", "real_name": "Daniel Middleton", "url": "https://www.youtube.com/@DanTDM",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@DanTDM",
        "bio": "Family-friendly gaming YouTuber. Known for Minecraft, Roblox, and kid-safe gaming content. Hugely influential with younger gaming audiences.",
        "language": "en", "region": "UK", "country": "United Kingdom",
        "follower_count": 28000000, "avg_viewers": 1500000, "total_views": 20000000000,
        "primary_game": "Minecraft", "games_played": ["Minecraft", "Roblox", "Pokemon", "Indie games"],
        "content_categories": ["Minecraft", "Family Gaming", "Sandbox", "Adventure"], "content_style": "educational",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@DanTDM", "social_instagram": "dantdm",
        "twitter_followers": 5000000, "instagram_followers": 3000000,
        "has_sponsorships": True, "past_sponsors": ["Minecraft", "Nintendo", "Lego"],
        "accepts_game_codes": True,
        "has_merch_store": True,
        "notable_achievements": ["Guinness World Record for most views on Minecraft YouTube", "28M+ subscribers", "World Tour live shows"],
        "tags": ["youtube", "minecraft", "family-friendly", "kids", "mega-creator"],
        "audience_age_range": "8-22", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "VanossGaming", "real_name": "Evan Fong", "url": "https://www.youtube.com/@VanossGaming",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@VanossGaming",
        "bio": "Comedy gaming YouTuber known for group game sessions with friends. Pioneered the comedy gaming genre with GTA V and Call of Duty content.",
        "language": "en", "region": "CA", "country": "Canada",
        "follower_count": 26000000, "avg_viewers": 1000000, "total_views": 14000000000,
        "primary_game": "GTA V", "games_played": ["GTA V", "Call of Duty", "Fortnite", "Among Us", "Garry's Mod"],
        "content_categories": ["Comedy", "Variety", "Multiplayer"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@VanossGaming", "social_instagram": "vanoss",
        "twitter_followers": 4000000, "instagram_followers": 5000000,
        "has_sponsorships": True,
        "accepts_game_codes": True,
        "has_merch_store": True,
        "notable_achievements": ["26M+ subscribers", "Pioneer of comedy gaming videos", "Animated series creator"],
        "tags": ["youtube", "comedy", "gta", "group-gaming", "mega-creator"],
        "audience_age_range": "14-28", "audience_top_countries": ["US", "CA", "UK", "MX"],
    },
    {
        "name": "MrBeast Gaming", "url": "https://www.youtube.com/@MrBeastGaming",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@MrBeastGaming",
        "bio": "Gaming-focused channel from MrBeast. Known for massive gaming challenges, huge prize pools, and Minecraft competitions with creator communities.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 48000000, "avg_viewers": 5000000, "total_views": 10000000000,
        "primary_game": "Minecraft", "games_played": ["Minecraft", "Squid Game recreations", "Battle Royale", "Variety challenges"],
        "content_categories": ["Gaming Challenges", "Variety", "Competition"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@MrBeast", "social_instagram": "mrbeast",
        "twitter_followers": 25000000, "instagram_followers": 55000000,
        "has_sponsorships": True, "past_sponsors": ["Honey", "ShopFi", "Feastables"],
        "estimated_sponsorship_rate": "$500k-2M per integration",
        "accepts_game_codes": True,
        "notable_achievements": ["48M gaming channel subs", "Squid Game recreations", "Most viewed gaming events on YouTube"],
        "tags": ["youtube", "mega-creator", "challenges", "prizes", "mrbeast"],
        "audience_age_range": "10-28", "audience_top_countries": ["US", "UK", "IN", "BR"],
    },
    {
        "name": "Jacksepticeye", "real_name": "Seán McLoughlin", "url": "https://www.youtube.com/@jacksepticeye",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@jacksepticeye",
        "bio": "Irish gaming YouTuber known for energetic personality and variety gaming. Major charity fundraiser and mental health advocate.",
        "language": "en", "region": "IE", "country": "Ireland",
        "follower_count": 32000000, "avg_viewers": 1500000, "total_views": 14000000000,
        "primary_game": "Variety", "games_played": ["Indie games", "Horror", "Variety", "Story games"],
        "content_categories": ["Variety", "Indie Games", "Horror", "Comedy"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@Jack_Septic_Eye", "social_instagram": "jacksepticeye",
        "twitter_followers": 6000000, "instagram_followers": 9000000,
        "has_sponsorships": True, "past_sponsors": ["Amp Energy", "Skillshare", "NordVPN"],
        "accepts_game_codes": True,
        "has_merch_store": True,
        "notable_achievements": ["Raised $15M+ for charity", "32M subscribers", "Mental health advocate", "CLOAK brand co-founder"],
        "tags": ["youtube", "charity", "irish", "family-friendly", "mega-creator"],
        "audience_age_range": "14-30", "audience_top_countries": ["US", "UK", "IE", "CA", "AU"],
    },
    {
        "name": "Techno Gamerz", "real_name": "Ujjwal Chaurasia", "url": "https://www.youtube.com/@TechnoGamerzOfficial",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@TechnoGamerzOfficial",
        "bio": "India's biggest gaming YouTuber. Known for GTA V, BGMI, and Minecraft Hindi gaming content. Massive influence on Indian gaming culture.",
        "language": "hi", "region": "IN", "country": "India",
        "follower_count": 47000000, "avg_viewers": 3000000, "total_views": 8000000000,
        "primary_game": "GTA V", "games_played": ["GTA V", "BGMI", "Minecraft", "Free Fire"],
        "content_categories": ["Gaming", "Mobile Gaming", "Variety"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mega", "priority": 1,
        "social_twitter": "@ujjwalgamer", "social_instagram": "techno_gamerz",
        "twitter_followers": 2000000, "instagram_followers": 14000000,
        "has_sponsorships": True, "past_sponsors": ["Loco", "BGMI", "MPL India"],
        "accepts_game_codes": True,
        "notable_achievements": ["India's most subscribed gaming channel", "47M+ subscribers", "Cultural icon for Indian gamers"],
        "tags": ["youtube", "hindi", "india", "gta", "bgmi", "mega-creator"],
        "audience_age_range": "12-28", "audience_top_countries": ["IN"],
    },
    {
        "name": "TheRadBrad", "real_name": "Bradley Colburn", "url": "https://www.youtube.com/@theRadBrad",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@theRadBrad",
        "bio": "Story game walkthrough specialist. Known for complete, spoiler-free walkthroughs of major story-driven games. YouTube gaming pioneer.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 14000000, "avg_viewers": 500000, "total_views": 7000000000,
        "primary_game": "Story Games", "games_played": ["The Last of Us", "God of War", "Cyberpunk 2077", "Red Dead Redemption", "Horror games"],
        "content_categories": ["Walkthroughs", "Story Games", "Adventure"], "content_style": "educational",
        "is_variety_streamer": False, "tier": "macro", "priority": 2,
        "social_twitter": "@theRadBrad", "social_instagram": "theradbrad",
        "twitter_followers": 800000, "instagram_followers": 700000,
        "accepts_game_codes": True,
        "notable_achievements": ["Pioneered YouTube game walkthroughs", "14M subscribers", "Trusted resource for story game completions"],
        "tags": ["youtube", "walkthroughs", "story-games", "spoiler-free", "trusted"],
        "audience_age_range": "18-40", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "GameGrumps", "url": "https://www.youtube.com/@GameGrumps",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@GameGrumps",
        "bio": "Comedy gaming duo channel founded by Arin Hanson and Dan Avidan. Known for witty banter and entertainment-focused game playthroughs.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 5800000, "avg_viewers": 300000, "total_views": 4000000000,
        "primary_game": "Variety", "games_played": ["Variety", "Mario games", "Indie games", "Classic games", "RPGs"],
        "content_categories": ["Comedy", "Variety", "Retro Gaming"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "macro", "priority": 2,
        "social_twitter": "@GameGrumps", "social_instagram": "gamegrumps",
        "twitter_followers": 1000000, "instagram_followers": 500000,
        "has_sponsorships": True, "past_sponsors": ["NordVPN", "DoorDash"],
        "accepts_game_codes": True,
        "has_merch_store": True,
        "notable_achievements": ["5.8M subscribers", "Pioneer of 'let's play' format", "Multiple game adaptations"],
        "tags": ["youtube", "comedy", "duo", "lets-play", "variety"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },
    {
        "name": "videogamedunkey", "url": "https://www.youtube.com/@videogamedunkey",
        "platform": "youtube", "youtube_channel": "https://www.youtube.com/@videogamedunkey",
        "bio": "Beloved gaming critic and commentator known for sharp comedy and unconventional game reviews. Founded Bigmode publishing label.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 7500000, "avg_viewers": 2000000, "total_views": 3500000000,
        "primary_game": "Variety", "games_played": ["League of Legends (former)", "Indie games", "AAA games", "Variety"],
        "content_categories": ["Reviews", "Comedy", "Commentary", "Critique"], "content_style": "educational",
        "is_variety_streamer": True, "tier": "macro", "priority": 2,
        "social_twitter": "@videogamedunkey",
        "twitter_followers": 600000,
        "accepts_game_codes": True,
        "notable_achievements": ["Founded Bigmode game publishing", "Cultural influence on gaming discourse", "Known for unconventional review scale"],
        "tags": ["youtube", "comedy", "reviews", "critique", "influential", "bigmode"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "CA", "AU"],
    },

    # ═══════════════════════════════════════════
    # TIKTOK GAMING CREATORS
    # ═══════════════════════════════════════════
    {
        "name": "Zeff Gaming", "url": "https://www.tiktok.com/@zeff_gaming",
        "platform": "tiktok", "tiktok_username": "zeff_gaming",
        "bio": "Popular TikTok gaming creator known for short-form gaming content, tips, and entertainment across multiple popular titles.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1400000,
        "primary_game": "Variety", "games_played": ["Fortnite", "Minecraft", "Variety"],
        "content_categories": ["Gaming Tips", "Short-form", "Entertainment"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mid", "priority": 3,
        "social_tiktok": "@zeff_gaming",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["1.4M TikTok followers", "Viral gaming content creator"],
        "tags": ["tiktok", "short-form", "gaming-tips", "variety"],
        "audience_age_range": "13-25", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "CupQuakely", "url": "https://www.tiktok.com/@cupquakely",
        "platform": "tiktok", "tiktok_username": "cupquakely",
        "bio": "TikTok gaming creator known for variety gaming content and humorous takes on popular games.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1500000,
        "primary_game": "Variety", "games_played": ["Variety", "Minecraft", "Horror games"],
        "content_categories": ["Gaming", "Comedy", "Short-form"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mid", "priority": 3,
        "social_tiktok": "@cupquakely",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["1.5M TikTok followers", "Consistent viral gaming content"],
        "tags": ["tiktok", "gaming", "comedy", "short-form"],
        "audience_age_range": "13-25", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "Cozy Games TikTok", "url": "https://www.tiktok.com/@cozy.games",
        "platform": "tiktok", "tiktok_username": "cozy.games",
        "bio": "TikTok creator specializing in cozy and relaxing gaming content. Showcases wholesome games like Stardew Valley, Animal Crossing, and more.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 696000,
        "primary_game": "Cozy Games", "games_played": ["Stardew Valley", "Animal Crossing", "Unpacking", "Spiritfarer"],
        "content_categories": ["Cozy Gaming", "Lifestyle", "Relaxing Content"], "content_style": "casual",
        "is_variety_streamer": True, "tier": "micro", "priority": 4,
        "social_tiktok": "@cozy.games",
        "accepts_game_codes": True,
        "notable_achievements": ["696K TikTok followers", "Leading cozy gaming TikTok account"],
        "tags": ["tiktok", "cozy-games", "stardew", "animal-crossing", "wholesome"],
        "audience_age_range": "18-35", "audience_top_countries": ["US", "UK", "AU", "CA"],
    },
    {
        "name": "RapidReacts", "url": "https://www.tiktok.com/@rapidreacts",
        "platform": "tiktok", "tiktok_username": "rapidreacts",
        "bio": "Gaming reaction and commentary creator on TikTok. Known for entertaining reactions to gaming news, trailers, and gameplay moments.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 1300000,
        "primary_game": "Variety", "games_played": ["Variety", "Gaming news", "Trailers"],
        "content_categories": ["Gaming Reactions", "Commentary", "Short-form"], "content_style": "entertainment",
        "is_variety_streamer": True, "tier": "mid", "priority": 3,
        "social_tiktok": "@rapidreacts",
        "accepts_game_codes": True, "accepts_sponsored_streams": True,
        "notable_achievements": ["1.3M TikTok followers", "Viral gaming reaction content"],
        "tags": ["tiktok", "reactions", "gaming-news", "commentary"],
        "audience_age_range": "15-30", "audience_top_countries": ["US", "UK", "CA"],
    },
    {
        "name": "GameTheory TikTok", "url": "https://www.tiktok.com/@gametheoristofficial",
        "platform": "tiktok", "tiktok_username": "gametheoristofficial",
        "bio": "TikTok presence of The Game Theorists. Short-form game theory content covering lore, hidden secrets, and analysis of popular games.",
        "language": "en", "region": "US", "country": "United States",
        "follower_count": 483000,
        "primary_game": "Game Theory/Analysis", "games_played": ["FNAF", "Minecraft", "Pokemon", "Various games"],
        "content_categories": ["Game Theory", "Analysis", "Lore", "Short-form"], "content_style": "educational",
        "is_variety_streamer": False, "tier": "micro", "priority": 4,
        "social_tiktok": "@gametheoristofficial",
        "accepts_game_codes": True,
        "notable_achievements": ["Extension of 20M+ YouTube channel", "Viral game theory content on TikTok"],
        "tags": ["tiktok", "game-theory", "lore", "analysis", "educational"],
        "audience_age_range": "13-25", "audience_top_countries": ["US", "UK", "CA"],
    },
]


def seed_streamers(db: Session) -> int:
    """Seed the database with known gaming streamers. Returns the number added."""
    added = 0
    for streamer_data in GAMING_STREAMERS:
        existing = db.query(Streamer).filter(Streamer.url == streamer_data["url"]).first()
        if not existing:
            streamer = Streamer(**streamer_data)
            db.add(streamer)
            added += 1
    db.commit()
    return added
