from sqlalchemy.orm import Session

from app.models.outlet import GamingOutlet

GAMING_STREAMER_SOURCES = [
    # ═══════════════════════════════════════════
    # TWITCH STREAMERS - Top Gaming Streamers
    # ═══════════════════════════════════════════
    {"name": "xQc", "url": "https://www.twitch.tv/xqc", "rss_feed_url": None, "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "One of the most-watched gaming streamers on Twitch", "social_twitter": "https://twitter.com/xQc", "social_youtube": "https://www.youtube.com/@xQcOW", "scraper_config": {"platform": "twitch", "channel_name": "xqc"}},
    {"name": "Shroud", "url": "https://www.twitch.tv/shroud", "rss_feed_url": None, "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Former CS:GO pro turned top gaming streamer", "social_twitter": "https://twitter.com/shroud", "social_youtube": "https://www.youtube.com/@shroud", "scraper_config": {"platform": "twitch", "channel_name": "shroud"}},
    {"name": "Pokimane", "url": "https://www.twitch.tv/pokimane", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top female gaming streamer and content creator", "social_twitter": "https://twitter.com/pokimane", "social_youtube": "https://www.youtube.com/@pokimane", "scraper_config": {"platform": "twitch", "channel_name": "pokimane"}},
    {"name": "Ninja", "url": "https://www.twitch.tv/ninja", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Iconic gaming streamer known for Fortnite", "social_twitter": "https://twitter.com/Ninja", "social_youtube": "https://www.youtube.com/@Ninja", "scraper_config": {"platform": "twitch", "channel_name": "ninja"}},
    {"name": "TimTheTatman", "url": "https://www.twitch.tv/timthetatman", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Popular variety gaming streamer", "social_twitter": "https://twitter.com/timthetatman", "scraper_config": {"platform": "twitch", "channel_name": "timthetatman"}},
    {"name": "Summit1g", "url": "https://www.twitch.tv/summit1g", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Veteran variety gaming streamer", "social_twitter": "https://twitter.com/summit1g", "scraper_config": {"platform": "twitch", "channel_name": "summit1g"}},
    {"name": "DrDisrespect", "url": "https://www.youtube.com/@DrDisrespect", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "The Two-Time, iconic gaming entertainer", "social_twitter": "https://twitter.com/DrDisrespect", "social_youtube": "https://www.youtube.com/@DrDisrespect", "scraper_config": {"platform": "youtube", "channel_id": "UCcJL2ld6kxy_nuV5uyIMGbg"}},
    {"name": "Tarik", "url": "https://www.twitch.tv/tarik", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "CS2 content creator and former pro player", "social_twitter": "https://twitter.com/tarik_tv", "scraper_config": {"platform": "twitch", "channel_name": "tarik"}},
    {"name": "Kai Cenat", "url": "https://www.twitch.tv/kaicenat", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Record-breaking Twitch streamer and entertainer", "social_twitter": "https://twitter.com/KaiCenat", "social_youtube": "https://www.youtube.com/@KaiCenat", "scraper_config": {"platform": "twitch", "channel_name": "kaicenat"}},
    {"name": "Valkyrae", "url": "https://www.youtube.com/@Valkyrae", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "YouTube Gaming co-owner and top creator", "social_twitter": "https://twitter.com/Valkyrae", "social_youtube": "https://www.youtube.com/@Valkyrae", "scraper_config": {"platform": "youtube", "channel_id": "UCWxlUwW9BgGISaakjGM37aw"}},
    {"name": "Sykkuno", "url": "https://www.youtube.com/@Sykkuno", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Popular variety gaming content creator", "social_twitter": "https://twitter.com/Sykkuno", "scraper_config": {"platform": "youtube", "channel_id": "UCRAJ7Pv4TETYUqf9mYLYCbQ"}},
    {"name": "Aceu", "url": "https://www.twitch.tv/aceu", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "FPS gaming streamer known for Valorant and Apex Legends", "social_twitter": "https://twitter.com/acesu", "scraper_config": {"platform": "twitch", "channel_name": "aceu"}},

    # ═══════════════════════════════════════════
    # YOUTUBE GAMING CREATORS
    # ═══════════════════════════════════════════
    {"name": "PewDiePie", "url": "https://www.youtube.com/@PewDiePie", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC-lHJZR3Gqxm24_Vd_AJ5Yw", "language": "en", "region": "EU", "country": "Sweden", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Most subscribed individual gaming YouTuber", "social_twitter": "https://twitter.com/pewdiepie", "scraper_config": {"platform": "youtube", "channel_id": "UC-lHJZR3Gqxm24_Vd_AJ5Yw"}},
    {"name": "Markiplier", "url": "https://www.youtube.com/@markiplier", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC7_YxT-KID8kRbqZo7MyscQ", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top gaming YouTuber known for horror and indie games", "social_twitter": "https://twitter.com/markiplier", "scraper_config": {"platform": "youtube", "channel_id": "UC7_YxT-KID8kRbqZo7MyscQ"}},
    {"name": "Jacksepticeye", "url": "https://www.youtube.com/@jacksepticeye", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCYzPXprvl5Y-Sf0g4vX-m6g", "language": "en", "region": "EU", "country": "Ireland", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Irish gaming YouTuber and co-founder of Cloak brand", "social_twitter": "https://twitter.com/jacksepticeye", "scraper_config": {"platform": "youtube", "channel_id": "UCYzPXprvl5Y-Sf0g4vX-m6g"}},
    {"name": "CouRageJD", "url": "https://www.youtube.com/@CouRageJD", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCaYLBJfw6d8XUmBHdMGkbPg", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Gaming content creator and YouTube star", "social_twitter": "https://twitter.com/CouRageJD", "scraper_config": {"platform": "youtube", "channel_id": "UCaYLBJfw6d8XUmBHdMGkbPg"}},
    {"name": "Ludwig", "url": "https://www.youtube.com/@ludwig", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCrPseYLGpNygVi34QpGNqpA", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Gaming creator and YouTube mogul", "social_twitter": "https://twitter.com/LudwigAhgren", "scraper_config": {"platform": "youtube", "channel_id": "UCrPseYLGpNygVi34QpGNqpA"}},
    {"name": "Typical Gamer", "url": "https://www.youtube.com/@TypicalGamer", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCgFXm4TI8htWmCyJ6cVPG_A", "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Fortnite and GTA V content creator", "social_twitter": "https://twitter.com/TypicalGamer", "scraper_config": {"platform": "youtube", "channel_id": "UCgFXm4TI8htWmCyJ6cVPG_A"}},
    {"name": "SSSniperWolf", "url": "https://www.youtube.com/@SSSniperWolf", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCpB959t8iPrxQWj7G6n0ctQ", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Gaming and reaction content creator", "social_twitter": "https://twitter.com/sssniperwolf", "scraper_config": {"platform": "youtube", "channel_id": "UCpB959t8iPrxQWj7G6n0ctQ"}},
    {"name": "Technoblade (Archive)", "url": "https://www.youtube.com/@Technoblade", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCelMeixAOTs2OQAAi9wU8sQ", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 3, "category": "gaming_streamer", "description": "Legendary Minecraft content creator", "scraper_config": {"platform": "youtube", "channel_id": "UCelMeixAOTs2OQAAi9wU8sQ"}},

    # ═══════════════════════════════════════════
    # INTERNATIONAL GAMING STREAMERS
    # ═══════════════════════════════════════════
    {"name": "ibai", "url": "https://www.twitch.tv/ibai", "rss_feed_url": None, "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Spain's biggest gaming streamer and entertainer", "social_twitter": "https://twitter.com/IbaiLlanos", "social_youtube": "https://www.youtube.com/@IbaiLlanos", "scraper_config": {"platform": "twitch", "channel_name": "ibai"}},
    {"name": "Rubius", "url": "https://www.twitch.tv/rubius", "rss_feed_url": None, "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top Spanish-speaking gaming creator", "social_twitter": "https://twitter.com/Rubiu5", "social_youtube": "https://www.youtube.com/@Rubiu5", "scraper_config": {"platform": "twitch", "channel_name": "rubius"}},
    {"name": "Gaules", "url": "https://www.twitch.tv/gaules", "rss_feed_url": None, "language": "pt", "region": "BR", "country": "Brazil", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Brazil's biggest CS2 streamer and caster", "social_twitter": "https://twitter.com/Gaules", "scraper_config": {"platform": "twitch", "channel_name": "gaules"}},
    {"name": "Loud Coringa", "url": "https://www.twitch.tv/loudcoringa", "rss_feed_url": None, "language": "pt", "region": "BR", "country": "Brazil", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Member of LOUD, Brazil's top gaming org", "social_twitter": "https://twitter.com/LOUDCoringa", "scraper_config": {"platform": "twitch", "channel_name": "loudcoringa"}},
    {"name": "Joueur Du Grenier", "url": "https://www.youtube.com/@joueurdugrenier", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC_yP2DpIgs5Y1uWC0T03Chw", "language": "fr", "region": "FR", "country": "France", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top French retro gaming YouTuber", "social_twitter": "https://twitter.com/JoueurDuGrenier", "scraper_config": {"platform": "youtube", "channel_id": "UC_yP2DpIgs5Y1uWC0T03Chw"}},
    {"name": "Sardoche", "url": "https://www.twitch.tv/sardoche", "rss_feed_url": None, "language": "fr", "region": "FR", "country": "France", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "French gaming streamer known for LoL content", "social_twitter": "https://twitter.com/Sardoche", "scraper_config": {"platform": "twitch", "channel_name": "sardoche"}},
    {"name": "Stylishnoob", "url": "https://www.twitch.tv/stylishnoob4", "rss_feed_url": None, "language": "ja", "region": "JP", "country": "Japan", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top Japanese FPS gaming streamer", "social_twitter": "https://twitter.com/stylishnoob", "scraper_config": {"platform": "twitch", "channel_name": "stylishnoob4"}},
    {"name": "SaudiGamer (صلوح)", "url": "https://www.youtube.com/@SaudiGamer", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCKSrEK2FMXUeMvrjb-fHHjg", "language": "ar", "region": "SA", "country": "Saudi Arabia", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top Arabic gaming YouTuber", "scraper_config": {"platform": "youtube", "channel_id": "UCKSrEK2FMXUeMvrjb-fHHjg"}},
    {"name": "CarryMinati", "url": "https://www.youtube.com/@CarryMinati", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCj22tfcQrWMFIGCRTolIwFg", "language": "hi", "region": "IN", "country": "India", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "India's biggest gaming and entertainment YouTuber", "social_twitter": "https://twitter.com/CarryMinati", "scraper_config": {"platform": "youtube", "channel_id": "UCj22tfcQrWMFIGCRTolIwFg"}},
    {"name": "Mortal (Naman Mathur)", "url": "https://www.youtube.com/@MortaLyt", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCkGi1jbKwveqPgeULuFJnRQ", "language": "hi", "region": "IN", "country": "India", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Indian BGMI/PUBG gaming streamer and esports star", "social_twitter": "https://twitter.com/MortaLyt", "scraper_config": {"platform": "youtube", "channel_id": "UCkGi1jbKwveqPgeULuFJnRQ"}},
]


def seed_streamer_sources(db: Session) -> int:
    """Seed the database with gaming streamer sources. Returns the number of new sources added."""
    added = 0
    for source_data in GAMING_STREAMER_SOURCES:
        existing = db.query(GamingOutlet).filter(GamingOutlet.url == source_data["url"]).first()
        if not existing:
            outlet = GamingOutlet(**source_data)
            db.add(outlet)
            added += 1
    db.commit()
    return added
