from sqlalchemy.orm import Session

from app.models.outlet import GamingOutlet

GAMING_STREAMER_SOURCES = [
    # ═══════════════════════════════════════════
    # TWITCH STREAMERS - Top Gaming Streamers
    # ═══════════════════════════════════════════
    {"name": "xQc", "url": "https://www.twitch.tv/xqc", "rss_feed_url": None, "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "One of the most-watched gaming streamers on Twitch", "social_twitter": "https://twitter.com/xQc", "social_youtube": "https://www.youtube.com/@xQcOW", "scraper_config": {"platform": "twitch", "channel_name": "xqc"}},
    {"name": "Shroud", "url": "https://www.twitch.tv/shroud", "rss_feed_url": None, "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Former CS:GO pro turned top gaming streamer", "social_twitter": "https://twitter.com/shroud", "social_youtube": "https://www.youtube.com/@shroud", "scraper_config": {"platform": "twitch", "channel_name": "shroud"}},
    {"name": "Pokimane", "url": "https://www.twitch.tv/pokimane", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top female gaming streamer and content creator", "social_twitter": "https://twitter.com/pokimane", "social_youtube": "https://www.youtube.com/@pokimane", "scraper_config": {"platform": "twitch", "channel_name": "pokimane"}},
    {"name": "Ninja", "url": "https://www.twitch.tv/ninja", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Iconic gaming streamer known for Fortnite", "social_twitter": "https://twitter.com/Ninja", "social_youtube": "https://www.youtube.com/@Ninja", "scraper_config": {"platform": "twitch", "channel_name": "ninja"}},
    {"name": "TimTheTatman", "url": "https://www.twitch.tv/timthetatman", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Popular variety gaming streamer", "social_twitter": "https://twitter.com/timthetatman", "scraper_config": {"platform": "twitch", "channel_name": "timthetatman"}},
    {"name": "Summit1g", "url": "https://www.twitch.tv/summit1g", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Veteran variety gaming streamer", "social_twitter": "https://twitter.com/summit1g", "scraper_config": {"platform": "twitch", "channel_name": "summit1g"}},
    {"name": "DrDisrespect", "url": "https://www.youtube.com/@DrDisrespect", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "The Two-Time, iconic gaming entertainer", "social_twitter": "https://twitter.com/DrDisrespect", "social_youtube": "https://www.youtube.com/@DrDisrespect", "scraper_config": {"platform": "youtube", "channel_id": "UCcJL2ld6kxy_nuV5uyIMGbg"}},
    {"name": "Tarik", "url": "https://www.twitch.tv/tarik", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "CS2 content creator and former pro player", "social_twitter": "https://twitter.com/tarik_tv", "scraper_config": {"platform": "twitch", "channel_name": "tarik"}},
    {"name": "Kai Cenat", "url": "https://www.twitch.tv/kaicenat", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Record-breaking Twitch streamer and entertainer", "social_twitter": "https://twitter.com/KaiCenat", "social_youtube": "https://www.youtube.com/@KaiCenat", "scraper_config": {"platform": "twitch", "channel_name": "kaicenat"}},
    {"name": "Valkyrae", "url": "https://www.youtube.com/@Valkyrae", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "YouTube Gaming co-owner and top creator", "social_twitter": "https://twitter.com/Valkyrae", "social_youtube": "https://www.youtube.com/@Valkyrae", "scraper_config": {"platform": "youtube", "channel_id": "UCWxlUwW9BgGISaakjGM37aw"}},
    {"name": "Sykkuno", "url": "https://www.youtube.com/@Sykkuno", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Popular variety gaming content creator", "social_twitter": "https://twitter.com/Sykkuno", "scraper_config": {"platform": "youtube", "channel_id": "UCRAJ7Pv4TETYUqf9mYLYCbQ"}},
    {"name": "Aceu", "url": "https://www.twitch.tv/aceu", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "FPS gaming streamer known for Valorant and Apex Legends", "social_twitter": "https://twitter.com/acesu", "scraper_config": {"platform": "twitch", "channel_name": "aceu"}},

    # ═══════════════════════════════════════════
    # YOUTUBE GAMING CREATORS
    # ═══════════════════════════════════════════
    {"name": "PewDiePie", "url": "https://www.youtube.com/@PewDiePie", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC-lHJZR3Gqxm24_Vd_AJ5Yw", "language": "en", "region": "EU", "country": "Sweden", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Most subscribed individual gaming YouTuber", "social_twitter": "https://twitter.com/pewdiepie", "scraper_config": {"platform": "youtube", "channel_id": "UC-lHJZR3Gqxm24_Vd_AJ5Yw"}},
    {"name": "Markiplier", "url": "https://www.youtube.com/@markiplier", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC7_YxT-KID8kRbqZo7MyscQ", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top gaming YouTuber known for horror and indie games", "social_twitter": "https://twitter.com/markiplier", "scraper_config": {"platform": "youtube", "channel_id": "UC7_YxT-KID8kRbqZo7MyscQ"}},
    {"name": "Jacksepticeye", "url": "https://www.youtube.com/@jacksepticeye", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCYzPXprvl5Y-Sf0g4vX-m6g", "language": "en", "region": "EU", "country": "Ireland", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Irish gaming YouTuber and co-founder of Cloak brand", "social_twitter": "https://twitter.com/jacksepticeye", "scraper_config": {"platform": "youtube", "channel_id": "UCYzPXprvl5Y-Sf0g4vX-m6g"}},
    {"name": "CouRageJD", "url": "https://www.youtube.com/@CouRageJD", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCaYLBJfw6d8XUmBHdMGkbPg", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Gaming content creator and YouTube star", "social_twitter": "https://twitter.com/CouRageJD", "scraper_config": {"platform": "youtube", "channel_id": "UCaYLBJfw6d8XUmBHdMGkbPg"}},
    {"name": "Ludwig", "url": "https://www.youtube.com/@ludwig", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCrPseYLGpNygVi34QpGNqpA", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Gaming creator and YouTube mogul", "social_twitter": "https://twitter.com/LudwigAhgren", "scraper_config": {"platform": "youtube", "channel_id": "UCrPseYLGpNygVi34QpGNqpA"}},
    {"name": "Typical Gamer", "url": "https://www.youtube.com/@TypicalGamer", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCgFXm4TI8htWmCyJ6cVPG_A", "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Fortnite and GTA V content creator", "social_twitter": "https://twitter.com/TypicalGamer", "scraper_config": {"platform": "youtube", "channel_id": "UCgFXm4TI8htWmCyJ6cVPG_A"}},
    {"name": "SSSniperWolf", "url": "https://www.youtube.com/@SSSniperWolf", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCpB959t8iPrxQWj7G6n0ctQ", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Gaming and reaction content creator", "social_twitter": "https://twitter.com/sssniperwolf", "scraper_config": {"platform": "youtube", "channel_id": "UCpB959t8iPrxQWj7G6n0ctQ"}},
    {"name": "Technoblade (Archive)", "url": "https://www.youtube.com/@Technoblade", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCelMeixAOTs2OQAAi9wU8sQ", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 3, "category": "gaming_streamer", "description": "Legendary Minecraft content creator", "scraper_config": {"platform": "youtube", "channel_id": "UCelMeixAOTs2OQAAi9wU8sQ"}},

    # ═══════════════════════════════════════════
    # INTERNATIONAL GAMING STREAMERS
    # ═══════════════════════════════════════════
    {"name": "ibai", "url": "https://www.twitch.tv/ibai", "rss_feed_url": None, "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Spain's biggest gaming streamer and entertainer", "social_twitter": "https://twitter.com/IbaiLlanos", "social_youtube": "https://www.youtube.com/@IbaiLlanos", "scraper_config": {"platform": "twitch", "channel_name": "ibai"}},
    {"name": "Rubius", "url": "https://www.twitch.tv/rubius", "rss_feed_url": None, "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top Spanish-speaking gaming creator", "social_twitter": "https://twitter.com/Rubiu5", "social_youtube": "https://www.youtube.com/@Rubiu5", "scraper_config": {"platform": "twitch", "channel_name": "rubius"}},
    {"name": "Gaules", "url": "https://www.twitch.tv/gaules", "rss_feed_url": None, "language": "pt", "region": "BR", "country": "Brazil", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Brazil's biggest CS2 streamer and caster", "social_twitter": "https://twitter.com/Gaules", "scraper_config": {"platform": "twitch", "channel_name": "gaules"}},
    {"name": "Loud Coringa", "url": "https://www.twitch.tv/loudcoringa", "rss_feed_url": None, "language": "pt", "region": "BR", "country": "Brazil", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Member of LOUD, Brazil's top gaming org", "social_twitter": "https://twitter.com/LOUDCoringa", "scraper_config": {"platform": "twitch", "channel_name": "loudcoringa"}},
    {"name": "Joueur Du Grenier", "url": "https://www.youtube.com/@joueurdugrenier", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC_yP2DpIgs5Y1uWC0T03Chw", "language": "fr", "region": "FR", "country": "France", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top French retro gaming YouTuber", "social_twitter": "https://twitter.com/JoueurDuGrenier", "scraper_config": {"platform": "youtube", "channel_id": "UC_yP2DpIgs5Y1uWC0T03Chw"}},
    {"name": "Sardoche", "url": "https://www.twitch.tv/sardoche", "rss_feed_url": None, "language": "fr", "region": "FR", "country": "France", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "French gaming streamer known for LoL content", "social_twitter": "https://twitter.com/Sardoche", "scraper_config": {"platform": "twitch", "channel_name": "sardoche"}},
    {"name": "Stylishnoob", "url": "https://www.twitch.tv/stylishnoob4", "rss_feed_url": None, "language": "ja", "region": "JP", "country": "Japan", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top Japanese FPS gaming streamer", "social_twitter": "https://twitter.com/stylishnoob", "scraper_config": {"platform": "twitch", "channel_name": "stylishnoob4"}},
    {"name": "SaudiGamer (صلوح)", "url": "https://www.youtube.com/@SaudiGamer", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCKSrEK2FMXUeMvrjb-fHHjg", "language": "ar", "region": "SA", "country": "Saudi Arabia", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top Arabic gaming YouTuber", "scraper_config": {"platform": "youtube", "channel_id": "UCKSrEK2FMXUeMvrjb-fHHjg"}},
    {"name": "CarryMinati", "url": "https://www.youtube.com/@CarryMinati", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCj22tfcQrWMFIGCRTolIwFg", "language": "hi", "region": "IN", "country": "India", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "India's biggest gaming and entertainment YouTuber", "social_twitter": "https://twitter.com/CarryMinati", "scraper_config": {"platform": "youtube", "channel_id": "UCj22tfcQrWMFIGCRTolIwFg"}},
    {"name": "Mortal (Naman Mathur)", "url": "https://www.youtube.com/@MortaLyt", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCkGi1jbKwveqPgeULuFJnRQ", "language": "hi", "region": "IN", "country": "India", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Indian BGMI/PUBG gaming streamer and esports star", "social_twitter": "https://twitter.com/MortaLyt", "scraper_config": {"platform": "youtube", "channel_id": "UCkGi1jbKwveqPgeULuFJnRQ"}},

    # ═══════════════════════════════════════════
    # MORE TWITCH — TOP EN STREAMERS
    # ═══════════════════════════════════════════
    {"name": "NICKMERCS", "url": "https://www.twitch.tv/nickmercs", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Top Warzone and Fortnite competitive streamer", "social_twitter": "https://twitter.com/NICKMERCS", "social_youtube": "https://www.youtube.com/@NICKMERCS", "scraper_config": {"platform": "twitch", "channel_name": "nickmercs"}},
    {"name": "Asmongold", "url": "https://www.twitch.tv/asmongold", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "World of Warcraft and MMORPG king on Twitch", "social_twitter": "https://twitter.com/Asmongold", "social_youtube": "https://www.youtube.com/@AsmongoldTV", "scraper_config": {"platform": "twitch", "channel_name": "asmongold"}},
    {"name": "MoistCr1TiKaL", "url": "https://www.twitch.tv/moistcr1tikal", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "penguinz0 — variety gaming and commentary creator with massive YouTube presence", "social_twitter": "https://twitter.com/MoistCr1TiKaL", "social_youtube": "https://www.youtube.com/@penguinz0", "scraper_config": {"platform": "twitch", "channel_name": "moistcr1tikal"}},
    {"name": "HasanAbi", "url": "https://www.twitch.tv/hasanabi", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Variety streamer and political commentary creator", "social_twitter": "https://twitter.com/hasanthehun", "social_youtube": "https://www.youtube.com/@HasanAbi", "scraper_config": {"platform": "twitch", "channel_name": "hasanabi"}},
    {"name": "Tyler1", "url": "https://www.twitch.tv/loltyler1", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "League of Legends' most iconic and energetic streamer", "social_twitter": "https://twitter.com/loltyler1", "social_youtube": "https://www.youtube.com/@tyler1", "scraper_config": {"platform": "twitch", "channel_name": "loltyler1"}},
    {"name": "Tfue", "url": "https://www.twitch.tv/tfue", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Elite Fortnite competitive player and streaming star", "social_twitter": "https://twitter.com/TTfue", "social_youtube": "https://www.youtube.com/@Tfue", "scraper_config": {"platform": "twitch", "channel_name": "tfue"}},
    {"name": "Sodapoppin", "url": "https://www.twitch.tv/sodapoppin", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Veteran variety streamer known for WoW and entertainment", "social_twitter": "https://twitter.com/Sodapoppin", "scraper_config": {"platform": "twitch", "channel_name": "sodapoppin"}},
    {"name": "LIRIK", "url": "https://www.twitch.tv/lirik", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Long-running variety gaming streamer on Twitch", "social_twitter": "https://twitter.com/LIRIK", "scraper_config": {"platform": "twitch", "channel_name": "lirik"}},
    {"name": "CohhCarnage", "url": "https://www.twitch.tv/cohh_carnage", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "RPG and AAA game specialist, Twitch veteran", "social_twitter": "https://twitter.com/CohhCarnage", "social_youtube": "https://www.youtube.com/@CohhCarnage", "scraper_config": {"platform": "twitch", "channel_name": "cohh_carnage"}},
    {"name": "ImperialHal", "url": "https://www.twitch.tv/imperialhal", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top Apex Legends competitive player and streamer", "social_twitter": "https://twitter.com/ImperialHal", "social_youtube": "https://www.youtube.com/@ImperialHal", "scraper_config": {"platform": "twitch", "channel_name": "imperialhal"}},
    {"name": "Bugha", "url": "https://www.twitch.tv/bugha", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Fortnite World Cup 2019 champion and streamer", "social_twitter": "https://twitter.com/bugha", "social_youtube": "https://www.youtube.com/@bugha", "scraper_config": {"platform": "twitch", "channel_name": "bugha"}},
    {"name": "Pestily", "url": "https://www.twitch.tv/pestily", "rss_feed_url": None, "language": "en", "region": "APAC", "country": "Australia", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Escape from Tarkov specialist and guide creator", "social_twitter": "https://twitter.com/Pestily", "social_youtube": "https://www.youtube.com/@Pestily", "scraper_config": {"platform": "twitch", "channel_name": "pestily"}},
    {"name": "Philza", "url": "https://www.twitch.tv/ph1lza", "rss_feed_url": None, "language": "en", "region": "EU", "country": "United Kingdom", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Minecraft hardcore legend and Dream SMP member", "social_twitter": "https://twitter.com/Ph1LzA", "social_youtube": "https://www.youtube.com/@Ph1LzA", "scraper_config": {"platform": "twitch", "channel_name": "ph1lza"}},
    {"name": "Quackity", "url": "https://www.twitch.tv/quackity", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Minecraft and variety streamer, Dream SMP creator", "social_twitter": "https://twitter.com/QuackityHQ", "social_youtube": "https://www.youtube.com/@Quackity", "scraper_config": {"platform": "twitch", "channel_name": "quackity"}},
    {"name": "Loserfruit", "url": "https://www.twitch.tv/loserfruit", "rss_feed_url": None, "language": "en", "region": "APAC", "country": "Australia", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Australian variety gaming streamer and Fortnite creator", "social_twitter": "https://twitter.com/Loserfruit", "social_youtube": "https://www.youtube.com/@Loserfruit", "scraper_config": {"platform": "twitch", "channel_name": "loserfruit"}},
    {"name": "SypherPK", "url": "https://www.twitch.tv/sypherpk", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Top Fortnite educator and competitive content creator", "social_twitter": "https://twitter.com/SypherPK", "social_youtube": "https://www.youtube.com/@SypherPK", "scraper_config": {"platform": "twitch", "channel_name": "sypherpk"}},
    {"name": "Pirate Software", "url": "https://www.twitch.tv/piratesoftware", "rss_feed_url": None, "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 3, "category": "gaming_streamer", "description": "Ex-Blizzard dev turned streamer teaching game development live", "social_twitter": "https://twitter.com/PirateSoftware", "social_youtube": "https://www.youtube.com/@PirateSoftware", "scraper_config": {"platform": "twitch", "channel_name": "piratesoftware"}},

    # ═══════════════════════════════════════════
    # MORE YOUTUBE GAMING CREATORS
    # ═══════════════════════════════════════════
    {"name": "Dream", "url": "https://www.youtube.com/@Dream", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCTkXRDQl0luXxVQrRQvWS6w", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Minecraft speedrunner and Dream SMP creator", "social_twitter": "https://twitter.com/dreamwastaken", "scraper_config": {"platform": "youtube", "channel_id": "UCTkXRDQl0luXxVQrRQvWS6w"}},
    {"name": "TommyInnit", "url": "https://www.youtube.com/@TommyInnit", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCq0OueAsdoHio8JZe4K83BQ", "language": "en", "region": "EU", "country": "United Kingdom", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "UK Minecraft creator and Dream SMP star with 14M subscribers", "social_twitter": "https://twitter.com/tommyinnit", "scraper_config": {"platform": "youtube", "channel_id": "UCq0OueAsdoHio8JZe4K83BQ"}},
    {"name": "DanTDM", "url": "https://www.youtube.com/@DanTDM", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCS5Oz6CHmeoF7vSad0qqXfw", "language": "en", "region": "EU", "country": "United Kingdom", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Minecraft and family-friendly gaming YouTuber", "social_twitter": "https://twitter.com/dantdm", "scraper_config": {"platform": "youtube", "channel_id": "UCS5Oz6CHmeoF7vSad0qqXfw"}},
    {"name": "VanossGaming", "url": "https://www.youtube.com/@VanossGaming", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCCwLl21jBEkVWQnGCGjMXHA", "language": "en", "region": "NA", "country": "Canada", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Comedy gaming highlights creator, 26M subscribers", "social_twitter": "https://twitter.com/VanossGaming", "scraper_config": {"platform": "youtube", "channel_id": "UCCwLl21jBEkVWQnGCGjMXHA"}},
    {"name": "LazarBeam", "url": "https://www.youtube.com/@LazarBeam", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCWaJFDFjC4pHcgI7cQ0tCcQ", "language": "en", "region": "APAC", "country": "Australia", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Australian Fortnite and comedy gaming creator", "social_twitter": "https://twitter.com/LazarBeamYT", "scraper_config": {"platform": "youtube", "channel_id": "UCWaJFDFjC4pHcgI7cQ0tCcQ"}},
    {"name": "GrayStillPlays", "url": "https://www.youtube.com/@GrayStillPlays", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCJLZe9s6SdnfOsnMPNFCpLA", "language": "en", "region": "NA", "country": "United States", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Chaos sandbox and simulation gaming creator, 13M subscribers", "social_twitter": "https://twitter.com/GrayStillPlays", "scraper_config": {"platform": "youtube", "channel_id": "UCJLZe9s6SdnfOsnMPNFCpLA"}},
    {"name": "Ali-A", "url": "https://www.youtube.com/@Ali-A", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCLSo1UcMHzRiE9DBQF0BVOA", "language": "en", "region": "EU", "country": "United Kingdom", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "UK Call of Duty and Fortnite gaming YouTuber", "social_twitter": "https://twitter.com/OMGitsAliA", "scraper_config": {"platform": "youtube", "channel_id": "UCLSo1UcMHzRiE9DBQF0BVOA"}},

    # ═══════════════════════════════════════════
    # ESPORTS & COMPETITIVE
    # ═══════════════════════════════════════════
    {"name": "Faker", "url": "https://www.twitch.tv/faker", "rss_feed_url": None, "language": "ko", "region": "KR", "country": "South Korea", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Greatest League of Legends player of all time, T1 midlaner", "social_twitter": "https://twitter.com/faker", "scraper_config": {"platform": "twitch", "channel_name": "faker"}},
    {"name": "auronplay", "url": "https://www.twitch.tv/auronplay", "rss_feed_url": None, "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Spain's most-followed Twitch streamer", "social_twitter": "https://twitter.com/auronplay", "social_youtube": "https://www.youtube.com/@auronplay", "scraper_config": {"platform": "twitch", "channel_name": "auronplay"}},

    # ═══════════════════════════════════════════
    # SPANISH — ADDITIONAL
    # ═══════════════════════════════════════════
    {"name": "TheGrefg", "url": "https://www.twitch.tv/thegrefg", "rss_feed_url": None, "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Spanish streamer who broke the Twitch viewership record", "social_twitter": "https://twitter.com/TheGrefg", "social_youtube": "https://www.youtube.com/@TheGrefg", "scraper_config": {"platform": "twitch", "channel_name": "thegrefg"}},
    {"name": "Vegetta777", "url": "https://www.youtube.com/@VEGETTA777", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCim0GGt5lsNPbTFwXP_uRHQ", "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Minecraft and variety gaming legend, 33M subscribers", "social_twitter": "https://twitter.com/Vegetta777", "scraper_config": {"platform": "youtube", "channel_id": "UCim0GGt5lsNPbTFwXP_uRHQ"}},
    {"name": "Willyrex", "url": "https://www.youtube.com/@Willyrex", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC4IJknQKDTHVAfJFGK3ENEQ", "language": "es", "region": "ES", "country": "Spain", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Spanish Minecraft and FPS gaming creator", "social_twitter": "https://twitter.com/Willyrex", "scraper_config": {"platform": "youtube", "channel_id": "UC4IJknQKDTHVAfJFGK3ENEQ"}},
    {"name": "Spreen", "url": "https://www.twitch.tv/spreen", "rss_feed_url": None, "language": "es", "region": "LATAM", "country": "Argentina", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Argentina's biggest gaming streamer, Minecraft SMP creator", "social_twitter": "https://twitter.com/iSpreen", "social_youtube": "https://www.youtube.com/@Spreen", "scraper_config": {"platform": "twitch", "channel_name": "spreen"}},
    {"name": "Cellbit", "url": "https://www.twitch.tv/cellbit", "rss_feed_url": None, "language": "pt", "region": "BR", "country": "Brazil", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Brazilian narrative and horror game streamer", "social_twitter": "https://twitter.com/cellbit", "social_youtube": "https://www.youtube.com/@cellbit", "scraper_config": {"platform": "twitch", "channel_name": "cellbit"}},

    # ═══════════════════════════════════════════
    # FRENCH — ADDITIONAL
    # ═══════════════════════════════════════════
    {"name": "Squeezie", "url": "https://www.youtube.com/@Squeezie", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCMEGfFkfDGSJPRmZo4qvr-A", "language": "fr", "region": "FR", "country": "France", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "France's biggest gaming YouTuber, 18M subscribers", "social_twitter": "https://twitter.com/Squeezie", "scraper_config": {"platform": "youtube", "channel_id": "UCMEGfFkfDGSJPRmZo4qvr-A"}},
    {"name": "ZeratoR", "url": "https://www.twitch.tv/zerator", "rss_feed_url": None, "language": "fr", "region": "FR", "country": "France", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "French StarCraft II and variety gaming streamer, ZLAN organizer", "social_twitter": "https://twitter.com/ZeratoR", "social_youtube": "https://www.youtube.com/@ZeratoR", "scraper_config": {"platform": "twitch", "channel_name": "zerator"}},

    # ═══════════════════════════════════════════
    # GERMAN — ADDITIONAL
    # ═══════════════════════════════════════════
    {"name": "Gronkh", "url": "https://www.youtube.com/@Gronkh", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCIiDTKEhTj6C2FQCDrFQGQA", "language": "de", "region": "EU", "country": "Germany", "scraper_type": "streamer", "priority": 1, "category": "gaming_streamer", "description": "Germany's most iconic gaming YouTuber and streamer", "social_twitter": "https://twitter.com/Gronkh", "scraper_config": {"platform": "youtube", "channel_id": "UCIiDTKEhTj6C2FQCDrFQGQA"}},
    {"name": "HandOfBlood", "url": "https://www.twitch.tv/handofblood", "rss_feed_url": None, "language": "de", "region": "EU", "country": "Germany", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "German Twitch streamer and gaming entertainer", "social_twitter": "https://twitter.com/HandOfBlood", "social_youtube": "https://www.youtube.com/@HandOfBlood", "scraper_config": {"platform": "twitch", "channel_name": "handofblood"}},

    # ═══════════════════════════════════════════
    # ASIA-PACIFIC — ADDITIONAL
    # ═══════════════════════════════════════════
    {"name": "Kuzuha", "url": "https://www.youtube.com/@KuzuhaChannel", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCENtdFdGMVBZFAG5aDozR7g", "language": "ja", "region": "JP", "country": "Japan", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Nijisanji VTuber and top Apex Legends player in Japan", "social_twitter": "https://twitter.com/kuzuha_1919", "scraper_config": {"platform": "youtube", "channel_id": "UCENtdFdGMVBZFAG5aDozR7g"}},
    {"name": "Pekora", "url": "https://www.youtube.com/@PekoraChannel", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC0rs_GxRSMCuipS7Dm8bYcg", "language": "ja", "region": "JP", "country": "Japan", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Hololive VTuber, one of YouTube's most-watched live streamers", "social_twitter": "https://twitter.com/usadapekora", "scraper_config": {"platform": "youtube", "channel_id": "UC0rs_GxRSMCuipS7Dm8bYcg"}},
    {"name": "Gawr Gura", "url": "https://www.youtube.com/@GawrGura", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCoSrY_IQQVpmIRZ9Xf-y93g", "language": "en", "region": "JP", "country": "Japan", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "Hololive EN VTuber, most-subscribed VTuber in the West", "social_twitter": "https://twitter.com/gawrgura", "scraper_config": {"platform": "youtube", "channel_id": "UCoSrY_IQQVpmIRZ9Xf-y93g"}},
    {"name": "Dynamo Gaming", "url": "https://www.youtube.com/@DynamoGaming", "rss_feed_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCCKZnFNSg9KCNXFSwLiNMtw", "language": "hi", "region": "IN", "country": "India", "scraper_type": "streamer", "priority": 2, "category": "gaming_streamer", "description": "India's top PUBG Mobile and battle royale content creator", "social_twitter": "https://twitter.com/DynamoGamingYT", "scraper_config": {"platform": "youtube", "channel_id": "UCCKZnFNSg9KCNXFSwLiNMtw"}},
]


def seed_streamer_sources(db: Session) -> int:
    """Seed the database with gaming streamer sources. Returns the number of new sources added."""
    added = 0
    for source_data in GAMING_STREAMER_SOURCES:
        existing = db.query(GamingOutlet).filter(GamingOutlet.url == source_data["url"]).first()
        if not existing:
            outlet = GamingOutlet(**source_data)
            db.add(outlet)
            added += 1
    db.commit()
    return added
