"""AI-generated pitch emails for investors, streamers, and outlets."""
from datetime import datetime, timezone

from sqlalchemy import Column, Integer, String, Text, DateTime, JSON, Float, ForeignKey
from sqlalchemy.orm import relationship

from app.database import Base


class GeneratedPitch(Base):
    """
    A complete pitch email generated by Claude AI using company + contact profiles.
    Different from MessagePersonalization which rewrites user-drafted messages.
    """
    __tablename__ = "generated_pitches"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("company_profiles.id"), nullable=False, index=True)

    # Target
    target_type = Column(String(20), nullable=False)  # vc | streamer | outlet
    target_id = Column(Integer, nullable=False)
    target_name = Column(String(500), nullable=False)

    # Type & config
    pitch_type = Column(String(30), nullable=False)
    # investment | sponsorship | press_coverage | review_key
    tone = Column(String(20), default="professional")
    # formal | casual | enthusiastic | professional
    user_instructions = Column(Text, nullable=True)

    # Snapshots for reproducibility
    company_snapshot = Column(JSON, nullable=True)
    contact_snapshot = Column(JSON, nullable=True)

    # Output
    subject_line = Column(String(1000), nullable=True)
    body = Column(Text, nullable=True)
    claude_model_used = Column(String(50), nullable=True)
    generation_tokens = Column(Integer, nullable=True)

    # Lifecycle
    status = Column(String(20), default="generating")
    # generating | completed | failed | approved | sent
    error_message = Column(Text, nullable=True)
    approved_at = Column(DateTime, nullable=True)
    sent_via_campaign_id = Column(Integer, ForeignKey("campaigns.id"), nullable=True)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
